### ISSUE TITLE
新功能建议：微信委托扣款

### ISSUE THREAD

**Issue by almas1992** [w7corp/easywechat#1248]
## 我用的环境

PHP 版本：
overtrue/wechat 版本：
是否使用了框架？框架名称：

## 问题及现象

微信委托扣款可应用于定期扣款或需事后扣款以提高效率的场景。例如但不限于：会员制缴费、水电煤缴费、黄钻绿钻增值服务、打车类软件、停车场或高速公路无人缴费、理财通基金定投、信用卡还款等通过用户授权给商户，进行委托扣款的场景。

开发文档链接： https://pay.weixin.qq.com/wiki/doc/api/pap.php?chapter=18_1&index=1

**Comment by 10v3** [comment]
+1

**Comment by mayunfeng0614** [comment]
+1

**Comment by overtrue** [comment]
如果没有人贡献 PR 将放到下一个大版本添加，因为目前这块没有使用经验，可能不会设计得比较好用。欢迎大家贡献 PR 并提供使用说明。
