### ISSUE TITLE
公众号开发时的一些想法

### ISSUE THREAD

**Issue by Lin07ux** [w7corp/easywechat#1254]
## 我用的环境

PHP 版本：7.1.15
overtrue/wechat 版本：4.0.30
是否使用了框架？框架名称：Laravel 5.6

## 问题及现象

1. 在微信公众号开发中，所有的事件的处理方法都是注册在`Message::Event`类型上，那么就需要在这个处理方法中再进行分类处理，还是会有一些未完全分离。是否有可能将每种事件消息根据其事件类别进行分类？然后再根据不同的事件进行事件注册。在处理消息的时候，需要根据消息的`MsgType`和`Event`字段共同确认消息类别。

> 下面几条是针对`src/Kernel/ServerGuard.php`类的公众号相关的 Guard 类来说的。

2. 公众号验证只有在接入的时候验证一次，而相关的处理逻辑(`EchoStrHandler`)却在每次微信服务器的推送中都存在，并被调用。能否在微信公众号的消息处理中，单独针对接入进行验证，可以通过请求的方法是不是`get`来判断是否为验证请求：只有验证请求是 get 方式的。

3. `handleRequest()`方法中，变量`$messageArray`的赋值可以检查下`$castedMessage`是否已经是数组格式，是的话就不需要对`$castedMessage`变量再进行一次相同的处理了。

4. `getMessage()`方法是否应该对获取到的 message 数组进行缓存？避免每次获取 message 的时候都要重新生成一次。而 message 并没有太大。

以上是我的一些想法，我没有通读整个 sdk 的代码，考虑的可能有失偏颇，或者破坏了 sdk 的统一思想，仅作参考。

**Comment by Jacksans** [comment]
请问怎样在公众号写一些好的代码？
