### ISSUE TITLE
建议返回的Response 选用实现了Psr 7 的类库

### ISSUE THREAD

**Issue by assert6** [w7corp/easywechat#1389]

**Comment by overtrue** [comment]
1. https://github.com/overtrue/wechat/blob/master/src/Kernel/Http/Response.php#L24
2. https://github.com/guzzle/psr7/blob/f5b8a8512e2b58b0071a7280e39f14f72e05d87c/src/Response.php#L10

哪里没有实现 Psr7 呢？

**Comment by zcmzc** [comment]
有歧义, 是继承 \Psr\Http\Message\ResponseInterface 接口的类库

**Comment by overtrue** [comment]
接口是实现不是继承，server 这里确实有问题。

**Comment by zcmzc** [comment]
是的 , 所以标题说的实现可能有歧义, 应该是server 返回的Response 没实现
