### ISSUE TITLE
消息处理器调用链的一些看法

### ISSUE THREAD

**Issue by FlyingBlazer** [w7corp/easywechat#1454]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.1.17
是否使用了框架？框架名称：Laravel 5.7

## 问题及现象

1. 通常情况下需要`EchoStrHandler`处理的消息并不需要开发者来处理，而使用FinallyResult时这个消息仍会进入消息处理器的调用链中，如果改为`TerminateResult`是不是更好。
2. `\EasyWeChat\Kernel\Traits\Observable::notify`里switch语句中的`break 2`是否应该改为`break 3`，这样才能符合文档中的`如果中间某一个 handler 返回值 false, 则将终止整个调用链，不会调用后续的 handlers`。
3. `\EasyWeChat\Kernel\Traits\Observable::notify`能否只用一层循环，相应的对`\EasyWeChat\Kernel\Traits\Observable::$handlers`的结构进行一定的修改，现在在一些特殊情况下无法保证处理器的执行顺序是按照push的顺序进行的，第二点中的问题也可以一并解决。

第三点中`$handlers`的结构大概可以改成以下的样子：

```php
[
    0 => ['\First\Handler', Message::TEXT],
    1 => ['\Second\Handler', Message::TEXT|Message::IMAGE],
    2 => ['\Third\Handler', Message::TEXT],
    3 => ['\Fourth\Handler', '*'],
]
```

**Comment by overtrue** [comment]
@mingyoung 是不是你上次的修改有问题 😆

**Comment by mingyoung** [comment]
@FlyingBlazer 现在的问题是并没有按照 push 的顺序去处理么？

**Comment by FlyingBlazer** [comment]
最开始我是在检查前两点的问题，翻代码的时候才发现第三点的问题

**Comment by great-zh** [comment]
常驻内存的框架 push会一直累积，每次push都会增加一次 希望能兼容常驻内存的框架
