### ISSUE TITLE
[6.0] 规划

### ISSUE THREAD

**Issue by overtrue** [w7corp/easywechat#1468]
- [x] PHP 8 +
- [x] <del>优化 service provider 注册逻辑 #1432 </del>
- [x] 优化 server 部分 #1454, #1389, #1254
- [x]  <del>提供请求和响应修改器入口</del>
- [x] 添加 SDK User-Agent
- [x] 统一命名方式：动名词
- [x] PSR 规范
  - [x] [PSR-7: HTTP message interfaces](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md)
  - [x] [PSR-14: EventDispatcher](https://github.com/php-fig/fig-standards/blob/master/proposed/event-dispatcher.md)
  - [x] [PSR-15: HTTP Server Request Handlers](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-15-request-handlers.md)
  - [x] [PSR-12: Extended Coding Style](https://www.php-fig.org/psr/psr-12/)
- [x] 依赖包升级
  - [x] PHPUnit 9+
- [x] 返回值签名验证
- [x] 添加原始接口内容获取方法
- [x] Server handler 移除 $condition 统一改为 where 条件表达式
- [x] <del>增加测试套件，简化测试用例编写</del>
- [x] 移除全局 helper<del>改为 Helper class</del>.
- [x] 移除不必要的依赖
- [x] 支持自定义缓存 key #1990 
- [x] 不再封装业务接口，只做基础接口
- [x] 链式调用  API 
- [x] 提供接口可替换相关模块
- [x] 移除 service container 模式

**Comment by mingyoung** [comment]
666

安正超 <notifications@github.com>于2019年2月15日 周五09:48写道：

**Comment by almas1992** [comment]
超哥威武~期待5.0

**Comment by longcnn** [comment]
V5

**Comment by zengshiran** [comment]
# It is the best SDK in the world for developing WeChat App!

**Comment by daowojia** [comment]
微信物流助手加上了说明却没发布程序, 害我空欢喜

**Comment by overtrue** [comment]
@daowojia 你在说啥呢？
![image](https://user-images.githubusercontent.com/1472352/54513294-edc97800-4991-11e9-8b34-2311f2fbd9a3.png)

**Comment by daowojia** [comment]
> @daowojia你在说啥呢？
> ![图片](https://user-images.githubusercontent.com/1472352/54513294-edc97800-4991-11e9-8b34-2311f2fbd9a3.png)
升到4.1.20最新了,真没找到 express,不信你看看源码

**Comment by mingyoung** [comment]
https://github.com/overtrue/wechat/blob/825fe019e8a0ae5ad1878e1fd53c50856350f49c/src/MiniProgram/Application.php#L58

@daowojia

**Comment by qq861229715** [comment]
请考虑支持一下小程序开放平台

**Comment by tans** [comment]
考虑一下统一http代理配置的问题？ 第三方平台的接口ip受限不方便本地开发调试。

**Comment by overtrue** [comment]
@tans 代理从3版本起就已经支持配置了哈，属于 guzzle 的配置参数

**Comment by MaymayJay** [comment]
发现了几个疑惑的点：获取js ticket，追查源码发现不满足企业微信服务商应用。因为授权安装应用的企业微信有很多，不同的corp_id，生成的ticket缓存是以只会以$this->app['config']->get('app_id') 为key。导致可用的永远只有一个。不知可否加入优化。
ps:改了源码感觉不合适
![image](https://user-images.githubusercontent.com/24680551/58524305-694d6e00-81fa-11e9-977a-134b745ce7d3.png)

**Comment by almas1992** [comment]
> 发现了几个疑惑的点：获取js ticket，追查源码发现不满足企业微信服务商应用。因为授权安装应用的企业微信有很多，不同的corp_id，生成的ticket缓存是以只会以$this->app['config']->get('app_id') 为key。导致可用的永远只有一个。不知可否加入优化。
> ps:改了源码感觉不合适
> ![image](https://user-images.githubusercontent.com/24680551/58524305-694d6e00-81fa-11e9-977a-134b745ce7d3.png)

为何在5.0规划中提issue，新开一个不好麽？

**Comment by zhmuyu** [comment]
希望超哥添加微信分账模块！

**Comment by overtrue** [comment]
@zhmuyu 没有那么多商户号可以演示啊亲

**Comment by TheNorthMemory** [comment]
> @zhmuyu 没有那么多商户号可以演示啊亲

分账接收方可以是商户号、个人微信号（及openid）、银行卡号，可以考虑给个人分账撒

**Comment by almas1992** [comment]
> > @zhmuyu 没有那么多商户号可以演示啊亲
> 
> 分账接收方可以是商户号、个人微信号（及openid）、银行卡号，可以考虑给个人分账撒

微信支付官方有提供这些形式的分账接口？

**Comment by zhmuyu** [comment]
> > > @zhmuyu没有那么多商户号可以演示啊亲
> > 
> > 
> > 分账接收方可以是商户号，个人微信号（及的OpenID），银行卡号，可以考虑给个人分账撒
> 
> 微信支付官方有提供这些形式的分账接口？
微信分账模块需要一个服务商户号，一个特约商户号

**Comment by TheNorthMemory** [comment]
> > > > @zhmuyu没有那么多商户号可以演示啊亲
> > > 
> > > 
> > > 分账接收方可以是商户号，个人微信号（及的OpenID），银行卡号，可以考虑给个人分账撒
> > 
> > 
> > 微信支付官方有提供这些形式的分账接口？
> > 微信分账模块需要一个服务商户号，一个特约商户号

官方文档见[这里](https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=24_1&index=1)，目前可自主开通 30% 的资金分账计划，高比例分账需要联系微信支付官方BD开通。

**Comment by liuyami** [comment]
开放平台增加了很多提交审核、发布小程序的接口，希望能加上

**Comment by kitchunwu** [comment]
希望超哥考虑qq小程序

**Comment by overtrue** [comment]
@kitchunwu 没有那么多精力哈，个人还要照顾很多方面的事情

**Comment by tq102412** [comment]
5.0中希望不要使用全局变量获取数据或者提供interface并且可以配置，以后会使用常驻内存的方式，感谢超哥

**Comment by overtrue** [comment]
这个 SDK 从一开始就没有过 “使用全局变量获取数据”

**Comment by tq102412** [comment]
![image](https://user-images.githubusercontent.com/28283435/64313811-750db500-cfdf-11e9-9fb8-96c2b9d4c386.png)
好的，我看了源码确实基本没有使用，但是有几个function获取了$_SERVICE，虽然有其他方式可以处理但是一开始使用的时候报错了还是会有点担心怕和cli模式不兼容

**Comment by overtrue** [comment]
@tq102412 好的

**Comment by leafmirror** [comment]
可以考虑swoole协程支持

**Comment by leafmirror** [comment]
> @tq102412 好的

可以考虑swoole协程支持@

**Comment by overtrue** [comment]
@leafmirror 不会考虑 PHP 官方外的其它环境适配

**Comment by Birjemin** [comment]
这个能报名参与么？

**Comment by overtrue** [comment]
报名？开源项目任何人可以贡献代码哈

**Comment by Birjemin** [comment]
好的，我觉得分包是很好的主意，因为随着功能完善，代码也变得很重，建议再增加一个common包，因为很多功能其实有类似的操作，可以同一封装，然后在各个包内实现具体细节

**Comment by Yurunsoft** [comment]
类似 `EasyWeChat\BasicService\Jssdk\Client::getTicket()` 这样的方法，可能会同时有请求进来，多个请求都没获取到缓存，都去调用接口重新获取 `ticket`，会导致接口调用次数很快用完。
最好的实现是做个定时更新的逻辑，目前我使用 Swoole 开发，正式打算这么做的。
希望可以有选项设定`ticket`、`AccessToken`缓存的行为。比如不希望自动调用接口更新

**Comment by overtrue** [comment]
@Yurunsoft 4.0 开始就可以自己设置缓存行为：

https://www.easywechat.com/docs/4.1/customize/access_token
https://www.easywechat.com/docs/4.1/customize/replace-service
https://www.easywechat.com/docs/4.1/customize/cache

**Comment by doododo** [comment]
特约商户进件这部分功能还会在4.x版本添加吗？还是直接到5.0拆包开发 @overtrue

**Comment by uyson** [comment]
希望封装一下纯签约方面的接口， 辛苦了

**Comment by liuyibao** [comment]
想知道 symfony/http-client 的优点 @overtrue

**Comment by mingyoung** [comment]
@liuyibao 
https://symfony.com/blog/new-in-symfony-4-3-httpclient-component#features

**Comment by yangtongbing** [comment]
分账模块发现添加接收方、删除接收方、单次分账、多次分账、查询分账结果、完结分账这些都有了,希望加一下分账回退的操作,毕竟,这样分账流程才完善,现在测试过程中忽然发现client里面没有分账回退,猛的不敢测试了,哈哈,支付完退不了全款,测多少搭进去多少😂😂😂

**Comment by bravist** [comment]
是不是可以接入微信支付官网的V3版本了

**Comment by chengxiansheng** [comment]
超哥 5.0什么时候出来呢

**Comment by qwqoffice** [comment]
小程序直播接口可以整合
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer
1. 获取直播房间列表
2. 获取回放源视频
3. 创建直播间

https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/commodity-api.html
1. 商品添加并提审
2. 撤回审核
3. 重新提交审核
4. 删除商品
5. 更新商品
6. 获取商品状态
7. 获取商品列表
8. 往指定直播间导入已入库商品

**Comment by larvacent** [comment]
easywechat/kernel 倒是开工啊。哈哈！

**Comment by lockdown56** [comment]
新的规划有没有些具体说明，最近工作不忙，可以一搞

**Comment by holamgor** [comment]
刚上线的对话能力考虑整合一下呗

**Comment by bangbangda** [comment]
@overtrue 
超哥，我看了下 6.0 的规划，现在完成那些模块了？
一直在用享受带来的便利，我们团队可以参与一下开发，比如
- 返回值签名验证
- 添加原始接口内容获取方法

可以沟通下具体什么功能，我们参与一下。

**Comment by superlbr** [comment]
还有[合并支付](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/combine/chapter3_2.shtml)

**Comment by lzhlo** [comment]
微信4月30后就下线模板消息了  唉

**Comment by lzhlo** [comment]
微信4月30后就下线模板消息了  唉

**Comment by skyliwq** [comment]
合单支付 这个功能很重要

**Comment by van-chin** [comment]
6.0.0-beta.1 版本 有更新日志说明么 @overtrue

**Comment by suyar** [comment]
目前有发布计划吗

**Comment by overtrue** [comment]
@suyar 可以先安装 beta 版帮忙测试

**Comment by linshuboy** [comment]
正式环境里面用了6.0.0 悲剧了，找到一个BUG在哪提交？fork 下来没有6.0的分支

**Comment by linshuboy** [comment]
\EasyWeChat\Kernel\Traits\InteractWithHandlers::handle  第一行代码应移到最后一个执行，不然的话被覆盖没有意义

**Comment by overtrue** [comment]
@linshuboy develop 分支

**Comment by overtrue** [comment]
@linshuboy 不太明白，有代码示意吗？或者加我 Q 44294631
