### ISSUE TITLE
小程序通过code获取openid时,偶尔出现GuzzleHttp请求出错导致未响应

### ISSUE THREAD

**Issue by yizenghui** [w7corp/easywechat#1546]
## 我用的环境 ubuntu16.04.1  nginx   php7.2-fpm

PHP 版本：PHP 7.2.16
overtrue/wechat 版本："overtrue/laravel-wechat": "~4.0",
框架名称：laravel 5.5

## 问题及现象

检查nginx错误日志时发现，在获取access_token时，GuzzleHttp6 偶尔会报错。(底下是报错日志)

怀疑是因为微信接口端返回不完整的响应而GuzzleHttp6认为响应异常而且放弃兼容。

备选方案：
1.目前小程序只使用了获取openid和获取用户信息两个接口，考虑自行调用微信api (差)
2.更换服务器再测试一段时间，目前还处于内测阶段，可更换服务器，但知道能不能解决问题 (差)
3.尝试更改源码，GuzzleHttp6.2退回GuzzleHttp5.3.0 

请问是否有前辈踩过相同的坑？

这个问题线下线上一样的代码，表现出来的结果不一致，正在努力解决中，如果有了解决办法，我会及时更新。
参考问题链接：
https://github.com/guzzle/guzzle/issues/1432

<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain
Date: Mon, 13 May 2019 23:13:45 GMT
Content-Length: 82

{"session_key":"AuXWQ0I6j6PUdLJqkHaykg==","openid":"oqzR35BT4jcMqbyar9w56CqQXhC4"}
--------
NULL" while reading response header from upstream, client: 223.74.69.175, server: readfollow.com, request: "GET /api/v1/gettoken?code=033kwuKc2ZdKCF0spoNc2MkkKc2kwuKM HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "readfollow.com", referrer: "https://servicewechat.com/wxa94ddd94358b2d1d/14/page-frame.html"
2019/05/14 07:58:25 [error] 27615#27615: *1230245 FastCGI sent in stderr: "PHP message: [2019-05-14 07:58:24] NULL.INFO: >>>>>>>>
GET /sns/jscode2session?access_token=21_oFc16ZFgP-psqHal8ZwePRbJXjKpOxRazKvyfCSdJFjScWlmEKnPmV3X8wp-BkvtCe7_rXrcts6CU3jO4LIA4X2X-uFDoKKflSbWsyqu6_Jt8LZXrFMMhQ_Q2TcCW1jayoxyn2JRgLCatoPdAJLdAIAHQS&appid=wxa94ddd94358b2d1d&secret=7ab4140f7b53b185a7afc32c2bcc0e30&js_code=033SjMHp0B1Nym1rGVJp0K9vHp0SjMH6&grant_type=authorization_code HTTP/1.1
Host: api.weixin.qq.com
User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.2.16-1+ubuntu16.04.1+deb.sury.org+1

<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain
Date: Mon, 13 May 2019 23:58:24 GMT
Content-Length: 82

{"session_key":"XyKwQeuFd11LZgFi1uHHAQ==","openid":"oqzR35LNYEGaXs6JWEgaxC_CKCvY"}
--------
NULL" while reading response header from upstream, client: 117.136.33.162, server: readfollow.com, request: "GET /api/v1/gettoken?code=033SjMHp0B1Nym1rGVJp0K9vHp0SjMH6 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "readfollow.com", referrer: "https://servicewechat.com/wxa94ddd94358b2d1d/14/page-frame.html"
2019/05/14 09:13:17 [error] 27616#27616: *1233527 FastCGI sent in stderr: "PHP message: [2019-05-14 09:13:17] NULL.INFO: >>>>>>>>
GET /sns/jscode2session?access_token=21_XagGs-ATB-fXH0H_MWfbGe0sjTO0TUOZ8GhKHmmhFHHBMLozRc6cI6Qtkha5eg2l4NYQrFjNzQZwqI1XCKh7jghekzxxlSskMIbZSI71nSNn-NB_JcRdvFwvHhYJNOaADATXY&appid=wxa94ddd94358b2d1d&secret=7ab4140f7b53b185a7afc32c2bcc0e30&js_code=023c1HVM18l7J71ZL1YM1M7QVM1c1HVQ&grant_type=authorization_code HTTP/1.1
Host: api.weixin.qq.com
User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.2.16-1+ubuntu16.04.1+deb.sury.org+1

**Comment by moxueyu** [comment]
应该和GuzzleHttp版本无关，EasyWeChat的SDK使用时你有做日志配置吗？

**Comment by overtrue** [comment]
应该是你服务器网络问题吧

**Comment by moxueyu** [comment]
应该和GuzzleHttp版本无关，需要在使用EasyWeChat的SDK时做日志配置

**Comment by yizenghui** [comment]
我也怀疑是网络问题，这是日志记录

[2019-07-13 14:29:43] NULL.INFO: >>>>>>>>
GET /sns/jscode2session?access_token=23_zu_Jayyl9nSFct4jyveEmhW6t8qNV6XvfIKlgc0_9W-MVrdcRAc0rLaQLGVl3S_ltfAx4F_L07Hyk9gp_j9BnFp0QYND93bR9WMLpkpfKeAiNdxMV1nNCx9agV5IAS0QC4L0ISi97bjy3O42LIDbAEADAV&appid=wxa94ddd94358b2d1d&secret=7ab4140f7b53b185a7afc32c2bcc0e30&js_code=043fhL8U1yCWkY0ulu7U1CwV8U1fhL8H&grant_type=authorization_code HTTP/1.1
Host: api.weixin.qq.com
User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.2.19-1+ubuntu16.04.1+deb.sury.org+1


<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain
Date: Sat, 13 Jul 2019 06:29:43 GMT
Content-Length: 82

{"session_key":"lndpgiJhCO+AJ9TkbN6kAw==","openid":"oqzR35Egd7Iwplv70G9QH6Vi57Qs"}
--------
NULL  
[2019-07-13 14:29:48] NULL.INFO: >>>>>>>>
GET /sns/jscode2session?access_token=23_zu_Jayyl9nSFct4jyveEmhW6t8qNV6XvfIKlgc0_9W-MVrdcRAc0rLaQLGVl3S_ltfAx4F_L07Hyk9gp_j9BnFp0QYND93bR9WMLpkpfKeAiNdxMV1nNCx9agV5IAS0QC4L0ISi97bjy3O42LIDbAEADAV&appid=wxa94ddd94358b2d1d&secret=7ab4140f7b53b185a7afc32c2bcc0e30&js_code=043dZE6z0jO4We1KdC3z0RfB6z0dZE62&grant_type=authorization_code HTTP/1.1
Host: api.weixin.qq.com
User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.2.19-1+ubuntu16.04.1+deb.sury.org+1


<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain
Date: Sat, 13 Jul 2019 06:29:48 GMT
Content-Length: 82

{"session_key":"lndpgiJhCO+AJ9TkbN6kAw==","openid":"oqzR35Egd7Iwplv70G9QH6Vi57Qs"}
--------
NULL  
[2019-07-13 15:37:28] NULL.INFO: >>>>>>>>
GET /sns/jscode2session?access_token=23_zu_Jayyl9nSFct4jyveEmhW6t8qNV6XvfIKlgc0_9W-MVrdcRAc0rLaQLGVl3S_ltfAx4F_L07Hyk9gp_j9BnFp0QYND93bR9WMLpkpfKeAiNdxMV1nNCx9agV5IAS0QC4L0ISi97bjy3O42LIDbAEADAV&appid=wxa94ddd94358b2d1d&secret=7ab4140f7b53b185a7afc32c2bcc0e30&js_code=071iffdu0j03qj1BIjbu0Xwidu0iffdH&grant_type=authorization_code HTTP/1.1
Host: api.weixin.qq.com
User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.2.19-1+ubuntu16.04.1+deb.sury.org+1


<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain
Date: Sat, 13 Jul 2019 07:37:28 GMT
Content-Length: 82

{"session_key":"V7M3172avNsSx2ih69DB3g==","openid":"oqzR35IqgH9b9yY8Hne71hiCM4vw"}
--------
NULL
