### ISSUE TITLE
请问一下有没有合单支付的功能？

### ISSUE THREAD

**Issue by FFFEGG** [w7corp/easywechat#1573]
最近想做一个合单支付，就是一次支付多个订单那种

**Comment by overtrue** [comment]
微信官方有吗？

**Comment by FFFEGG** [comment]
https://pay.weixin.qq.com/wiki/doc/api/combine.php?chapter=24_5&index=6

**Comment by overtrue** [comment]
目前没有做相关封装哦，你可以仿照已经有的写法 PR

**Comment by dqenix** [comment]
请问这个功能之后会支持吗？做多商户购物车统一付款需要用到
