### ISSUE TITLE
小微商户的获取证书报错异常

### ISSUE THREAD

**Issue by yecao007** [w7corp/easywechat#1696]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：master
* 是否使用了框架？框架名称：thinkphp

## 问题及现象
小微商户提交前要获取证书，如果参数错误的话，报错会抛出一个本框架捕捉异常时的bug,
$response = $app->certficates->get($returnRaw); 当中如果报错， 
在命名空间EasyWeChat\MicroMerchant\Certficates;下的Client.php 63行
 
                    'Failed to get certificate. result_err_code_des: "%s" .',$response['result_code'].'('.$response['err_code'].'['.$response['err_code_des'].'])'
                
微信官方返回的$response对象当中的字段是err_code_desc 而框架是获取err_code_des ，请及时修改这个小概率bug

**Comment by overtrue** [comment]
他们文档上所有地方都是 err_code_des https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1

**Comment by overtrue** [comment]
官方 SDK 代码里也一样：

![image](https://user-images.githubusercontent.com/1472352/65828601-29dd7e00-e2cf-11e9-8b40-d055e0cd2d72.png)

**Comment by yecao007** [comment]
返回的部分接口却是err_code_desc

**Comment by overtrue** [comment]
@yecao007 麻烦提供具体接口，我才方便去查问题。

**Comment by overtrue** [comment]
这边联系到官方，需要提供一下详细信息，包含商户 ID 等，请加我 Q 44294631

**Comment by yecao007** [comment]
$response = $app->certficates->get(false);小微商户的申请入驻，在调用获取证书的时候（未填写apiv3_key的时候才会报错），才返回err_code_desc,商户ID 1556941721

**Comment by yecao007** [comment]
具体证书接口调用是https://api.mch.weixin.qq.com/risk/getcertficates

**Comment by overtrue** [comment]
抱歉，同事没回复，不晓得现在是否已经改过了？

**Comment by yecao007** [comment]
其实，只要获取证书的还是不出错的话，倒是不会出现那个异常
