### ISSUE TITLE
分账功能生成接收方对象的时候中文编码问题

### ISSUE THREAD

**Issue by nine-city** [w7corp/easywechat#1697]
## 我用的环境

* PHP 版本：PHP7.2
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：TP5

## 问题及现象
下面这个JSON对象传给profitsharing的share方法时，如果description是中文，最后生成的XML中的receivers则是空的。description为英文则没有这个问题。使用的EasyChat版本更新到最新了。

$receiver = [
                    "type"           => $type,
                    "account"        => $user['openid'],
                    "amount"         => (int)$amount,
                    "description"    => "分享",
];

![QQ图片20191004001513](https://user-images.githubusercontent.com/20138490/66144776-0d797280-e63c-11e9-9cd4-f25bab3dedbc.png)

**Comment by overtrue** [comment]
确认你使用 UTF-8 编码
