### ISSUE TITLE
开放平台代公众号实现JsSdk问题

### ISSUE THREAD

**Issue by wuyan94zl** [w7corp/easywechat#1701]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：laravel6

## 问题及现象
文档 https://www.easywechat.com/docs/4.1/open-platform/authorizer-delegate
代码如下
```
    $appId = $business->app_id;
    $config = config('app.open_config');
    $openPlatform = Factory::openPlatform($config);
    $info = $openPlatform->getAuthorizer($appId);
    $refreshToken = $info['authorization_info']['authorizer_refresh_token'];
    $app = $openPlatform->officialAccount($appId,$refreshToken);
    return $app->jssdk->buildConfig(['checkJsApi'], false);
```
![image](https://user-images.githubusercontent.com/20943661/66731162-7f498b80-ee88-11e9-904d-230bb9b98202.png)

**Comment by passerbyxp** [comment]
同样的版本同样的操作，同样的错误，只不过我并没有使用框架：
