### ISSUE TITLE
小程序消息推送设置没有文档，请问这一块怎么弄？

### ISSUE THREAD

**Issue by kl521516** [w7corp/easywechat#1770]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：thinkphp

## 问题及现象
小程序消息推送设置没有找到对应的文档，请问这一块怎么弄？
按照公众号去配置，发现用不了

$this->wechat_app = Factory::miniProgram($this->config_wechat);

$this->wechat_app->server->push(function($message){
return "收到消息";
}

**Comment by violetice** [comment]
使用客服消息
```
$app->server->push(function ($message) use ($app) {
    $app->customer_service->message(new Text('你在说啥，我不懂..'))
        ->to($message['FromUserName'])->send();
});
```
