### ISSUE TITLE
官方似乎把小微商户入驻接口给停了

### ISSUE THREAD

**Issue by zuxue** [w7corp/easywechat#1774]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：
Laravel
## 问题及现象
今天发现微信把小微商户进件的功能给停了
因为提交资料给入驻接口时返回
“特约商户进件API已升级，服务商可直接进件个体户/企业“
详情请看https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/applyment4sub/chapter1_1.shtml

询问其他PHP开发者后，都说存在这个情况。但是java开发的却不存在，不知道问题在哪。
之前项目正常运转有将近半年没问题。所以怀疑是微信官方关停`小微入驻`，可能需要开发`特约商户入驻`，不知道你们有没有兴趣更新一下呢。

**Comment by einsqing** [comment]
我们也被停了，求官方升级

**Comment by etoup** [comment]
有相同需求，请官方升级！

**Comment by q889518** [comment]
有相同需求，期待官方升级！

**Comment by chenyoufu** [comment]
太难了，我们太难了
