### ISSUE TITLE
消息发送类型能否新增一个markdown类型?

### ISSUE THREAD

**Issue by phper666** [w7corp/easywechat#1775]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：hyperf

## 问题及现象
企业微信消息发送接口已经支持markdown类型，但是查看easywechat里面还没有这个类型，能否加上这个类型呢？
企业微信发送消息接口地址：https://work.weixin.qq.com/api/doc/90000/90135/90236#markdown%E6%B6%88%E6%81%AF

**Comment by her-cat** [comment]
可以试试这个：
`EasyWeChat\Work\GroupRobot\Messages\Markdown`

参考：https://www.easywechat.com/docs/4.1/wework/group-robot#heading-h2-2

**Comment by phper666** [comment]
@her-cat 感谢，可以用

**Comment by her-cat** [comment]
:smile:
