### ISSUE TITLE
【JSSDK】未知原因access_token失效，引起getTicket返回-1000

### ISSUE THREAD

**Issue by lain1936** [w7corp/easywechat#1780]
## 我用的环境

* PHP 版本：7.1
* overtrue/wechat 版本："overtrue/laravel-wechat": "~4.0",
* 是否使用了框架？框架名称： laravel

## 问题及现象

未知原因access_token失效，引起getTicket返回 "-1000",  "system error hints"

`[2020-01-05 08:00:48] local.ERROR: Undefined index: expires_in {"exception":"[object] (ErrorException(code: 0): Undefined index: expires_in at /****/overtrue/wechat/src/BasicService/Jssdk/Client.php:100)
[stacktrace]
`

临时解决方式，手动刷新access_token

`if(isset($result['expires_in'])){
            $this->getCache()->set($cacheKey, $result, $result['expires_in'] - 500);
        };

$t = $this->getTicket();    
        if(isset($t['ticket'])){
            return [
                'appId' => $this->getAppId(),
                'nonceStr' => $nonce,
                'timestamp' => $timestamp,
                'url' => $url,
                'signature' => $this->getTicketSignature($this->getTicket()['ticket'], $nonce, $timestamp, $url),
            ];
        }else{
            return [
                'appId' => $this->getAppId(),
                'nonceStr' => $nonce,
                'timestamp' => $timestamp,
                'url' => $url,
                'signature' => false,
            ];
      };

//业务代码
 $data = $app->jssdk->buildConfig($request->jsApiList, $debug = true,false,false);
      if(!$data['signature']){
         $t = $app->access_token->getToken(true);
         $data = $app->jssdk->buildConfig($request->jsApiList, $debug = true,false,false);
      }`

**Comment by youruan** [comment]
我也遇到相同的问题
