### ISSUE TITLE
公众号使用统一管理的access_token后oauth提示缺少app secret。

### ISSUE THREAD

**Issue by unizhu** [w7corp/easywechat#1782]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0.23
* 是否使用了框架？框架名称：Laravel

## 问题及现象

因为公众号使用了统一管理的access token，所以无法配置app secret。
所以在初始化的时候：
```php
$app = Factory::officialAccount(config('wechat.official_account.xxx'));
$app['access_token']->setToken('从集中管理的地方获取的token');
```
但是在调用 $app->oauth->user()->toJSON() 的时候，提示出现了：
```json
{"errcode":41004,"errmsg":"appsecret missing, hints: [ req_id: GHDaftXIRa-NWbLqa ]"}
```

请问这个问题该如何解决？谢谢。

**Comment by overtrue** [comment]
Oauth 的token 和接口token 是完全不一样的两个东西，建议了解清楚先

unisback <notifications@github.com>于2020年1月8日 周三下午5:14写道：

**Comment by unizhu** [comment]
@overtrue 的确是2个token，那请问oauth的时候可以setToken吗？

**Comment by overtrue** [comment]
参考：https://github.com/overtrue/socialite#get-user-with-access-token
