### ISSUE TITLE
小微商户已经升级到V3什么时候支持一下

### ISSUE THREAD

**Issue by q889518** [w7corp/easywechat#1812]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/applyment4sub/chapter3_1.shtml 
目前存在的接口已经不能使用了，会提示
![QQ图片20200310094532](https://user-images.githubusercontent.com/19340962/76271686-391c1b00-62b4-11ea-8f12-9eab02f25dac.jpg)

**Comment by c4ys** [comment]
目前只能根据文档开发了：
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/applyment4sub/chapter3_1.shtml
https://wechatpay-api.gitbook.io/wechatpay-api-v3/

官方提供了一个PHP SDK ：
https://wechatpay-api.gitbook.io/wechatpay-api-v3/kai-fa-gong-ju
