### ISSUE TITLE
是否支持微信支付V3 API

### ISSUE THREAD

**Issue by mike2001** [w7corp/easywechat#1816]
## 我用的环境

* PHP 版本：7.0.2
* overtrue/wechat 版本：3.3
* 是否使用了框架？框架名称：TP6.0

## 问题及现象

是否支持微信支付V3 API

**Comment by mingyoung** [comment]
暂不支持

**Comment by TheNorthMemory** [comment]
The `wechatpay-guzzle-middleware` is almost production ready now.

**Comment by ilchin** [comment]
期待中...
