### ISSUE TITLE
建议  WeChatProvider buildAuthUrlFromBase 从配置文件读取路径

### ISSUE THREAD

**Issue by dlsimple** [w7corp/easywechat#1831]
## 建议

Overtrue\Socialite\Providers\WeChatProvider

中 

`    /**
     * {@inheritdoc}.
     */
    protected function getAuthUrl($state)
    {
        $path = 'oauth2/authorize';

        if (in_array('snsapi_login', $this->scopes)) {
            $path = 'qrconnect';
        }

        return $this->buildAuthUrlFromBase("https://open.weixin.qq.com/connect/{$path}", $state);
    }
`

https://open.weixin.qq.com/connect/ 是否可以考虑从配置文件里面读取，

因为多域名的关系，要用到 [get-weixin-code.html ](https://github.com/HADB/GetWeixinCode)

**Comment by mingyoung** [comment]
就算改了那其他流程也走不通吧？这些特殊的方法建议自己封装逻辑

**Comment by dlsimple** [comment]
我只是替换了地址，在oauth2/authorize 是走的通的， 另一个qrconnect 没有测试。
