### ISSUE TITLE
微信端用户授权页URL 少了参数导致出错

### ISSUE THREAD

**Issue by bruceleedrupal** [w7corp/easywechat#1842]
## 我用的环境

* PHP 7.4：
* overtrue/wechat 版本：4.2
* 是否使用了框架？框架名称：symfony

## 问题及现象

获取用户授权页 URL
$openPlatform->getMobilePreAuthorizationUrl('https://easywechat.com/callback'); 

用户在微信里点击上面的链接会出错，如下图：

![S00505-22032826](https://user-images.githubusercontent.com/7478954/81076157-e65e8880-8f1d-11ea-839c-b7a015150387.jpg)

发现在少了auth_type 这个参数，对应代码在
src/OpenPlatform/Application.php 146行函数getMobilePreAuthorizationUrl中，以下修改后增加
auth_type=>3即可,如下所示:
`
 /**
     * Return the pre-authorization login page url (mobile).
     *
     * @param string            $callbackUrl
     * @param string|array|null $optional
     *
     * @return string
     */
    public function getMobilePreAuthorizationUrl(string $callbackUrl, $optional = []): string
    {
        // 兼容旧版 API 设计
        if (\is_string($optional)) {
            $optional = [
                'pre_auth_code' => $optional,
            ];
        } else {
            $optional['pre_auth_code'] = $this->createPreAuthorizationCode()['pre_auth_code'];
        }

        $queries = \array_merge($optional, [
            'component_appid' => $this['config']['app_id'],
            'redirect_uri' => $callbackUrl,
            'action' => 'bindcomponent',
            'no_scan' => 1,
            'auth_type' => 3,
        ]);

        return 'https://mp.weixin.qq.com/safe/bindcomponent?'.http_build_query($queries).'#wechat_redirect';
}`

**Comment by pensacola1989** [comment]
同样这个问题。貌似还没修复？
