### ISSUE TITLE
偶发性无法获取缓存中的access_token

### ISSUE THREAD

**Issue by MaymayJay** [w7corp/easywechat#1860]
## 我用的环境

* PHP 版本：7.1
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：lumen5.7

## 问题及现象

开放平台替换缓存为redis之后,偶发性出现无法获取授权方（如小程序）的access_token。
![image](https://user-images.githubusercontent.com/24680551/83585415-61967700-a57c-11ea-8a35-cf33e381f220.png)

## 排查过程

1. redis中对应的小程序access_token的key是有值的但是这个值无法正常解析
2. 查看了框架底层替换之后的cache模块为 `Symfony\Component\Cache\Simple\RedisCache`，set的时候实际上是调用了 `Symfony\Component\Cache\Marshaller\DefaultMarshaller` 中的 `marshall`
3. `marshall`中默认用的是 `serialize`：
![image](https://user-images.githubusercontent.com/24680551/83585856-7b848980-a57d-11ea-86da-3ed3ca459c5d.png)

所以怀疑是因为 `serialize`请求获取的access_token数据（可能包含某种特殊字符），导致存入redis中的value有问题导致后续的 `unserialize`失败。
所以想请教下怎么解决
[ps:在这里也看到了一个相同情况但是被closed的issue](https://github.com/overtrue/wechat/issues/1815)

**Comment by MaymayJay** [comment]
测试环境安装了igbinary 貌似就没出现类似得问题。。继续观察ing

**Comment by ZengJJ** [comment]
我这边是Yii 框架，也是偶发性出现这个问题；缓存写入不成功。
导致停摆，大概10分钟左右会自动恢复。
之前是文件缓存，后面修改为redis 缓存，同样出现。

**Comment by overtrue** [comment]
@ZengJJ 试试在写入缓存后立即读取

**Comment by ZengJJ** [comment]
@overtrue  

好的。目前无法重现这个问题，属于偶发性，等下次出现的时候尝试看看。

之前出现故障的时候，重启过服务器的nginx，php-fpm，redis。均无效。

看到旧版本有人出现过类似问题，升级版本后就解决了；但是我这边本身就是新版本。

以下是日志的报错信息：
![QQ图片20200722171402](https://user-images.githubusercontent.com/4024657/88158622-dca41180-cc3e-11ea-9060-97415b839d8c.png)

**Comment by overtrue** [comment]
@ZengJJ 嗯，这个东西也不好查，用的都是开源组件，所以只能辛苦能重现的帮忙查了

**Comment by ZengJJ** [comment]
@overtrue 好的，感谢

**Comment by mogody** [comment]
我用Hyperf 也有这个问题，排查到发现set到cache中的，有概率出现value前面加了两个空格的情况，导致取出来后unserialize报错

**Comment by mogody** [comment]
https://github.com/hyperf/hyperf/issues/2225

**Comment by overtrue** [comment]
各位看看 4.2.31 版本，@limingxinleo 提交了已个 PR 也许是这个问题导致

**Comment by MaymayJay** [comment]
> 各位看看 4.2.31 版本，@limingxinleo 提交了[一个 PR](https://github.com/overtrue/wechat/pull/1916) 也许是这个问题导致

应该不是，之前我有看过redis中对应的缓存，其实缓存中是有值，只是数据格式无法正确unserialize出来，返回的是空。

**Comment by limingxinleo** [comment]
@MaymayJay 如果你是序列化的问题，可能是这个问题 https://github.com/hyperf/hyperf/issues/2225

你是不是也是多个项目公用一个 Redis 获取 Token，而多个项目里，有的 Redis 设置了序列化规则

**Comment by MaymayJay** [comment]
> @MaymayJay 如果你是序列化的问题，可能是这个问题 [hyperf/hyperf#2225](https://github.com/hyperf/hyperf/issues/2225)
> 
> 你是不是也是多个项目公用一个 Redis 获取 Token，而多个项目里，有的 Redis 设置了序列化规则

我这个是和这个[issue](https://github.com/overtrue/wechat/issues/1815)

ps:老哥你那个提交还可以优化成一个lua脚本  就原子性了

**Comment by limingxinleo** [comment]
@MaymayJay 那应该还是多个项目共用一个 Redis，但是 Cache 序列化不一致导致的。

**Comment by lonestonewy** [comment]
> 我这边是Yii 框架，也是偶发性出现这个问题；缓存写入不成功。
> 导致停摆，大概10分钟左右会自动恢复。
> 之前是文件缓存，后面修改为redis 缓存，同样出现。

跟我情况完全一致。尝试过了自定义缓存接口到Yii本身缓存，用过了memcached和file后端，都出现这种偶发性问题，去缓存看数据确实是存在的，过期时间也都没问题。
现在我是怀疑setCache后立即getCache可能会拿不到数据，我将这段getCache判断抛异常的代码注释掉了，再观察下。
这个问题真头疼。

**Comment by sn01615** [comment]
`sudo chmod 777 -R /tmp/symfony-cache`😁

**Comment by MaymayJay** [comment]
> @MaymayJay 那应该还是多个项目共用一个 Redis，但是 Cache 序列化不一致导致的。

我还是觉得不是，目前没有公用一个redis ，这个就是比正常的序列化之后的字符串，前面多了几个字符。难受，但是目前又没有出现过了

**Comment by MaymayJay** [comment]
> @MaymayJay 那应该还是多个项目共用一个 Redis，但是 Cache 序列化不一致导致的。

**Comment by optonc** [comment]
是不是负载均衡开启多台服务器，然后没有同步缓存？

**Comment by awanganddong** [comment]
php 版本 7.2.33 
overtrue 版本 5.1

还是偶发性出现这个问题，为了不影响项目，把缓存从文件换成redis
但是这个问题应该还是存在的

**Comment by laraveler** [comment]
在symfony 的 DefaultMarshaller 中，会根据情况判断当前环境有没有安装igbinary，如果安装了会使用igbinary_serialize序列化数据，而igbinary_serialize序列化的数据就是如果你用serialize()就会不正确，或者你开发环境和正式环境不一样，也会千万不稳定，你可以new RedisAdapter()的时候把第4个构造函数参数使用 new DefaultMarshaller(false)，关掉igbinary_serialize，使用php的serialize()，或者可以实现MarshallerInterface接口，然后实现里面的方法，自定义序列化方案，比如自定义JsonMarshaller类，然后在new RedisAdapter()的时候做为第4个参数传入，redis缓存里面就是json。

**Comment by MaymayJay** [comment]
![image](https://user-images.githubusercontent.com/24680551/100580814-99ab2680-3321-11eb-87d5-7e09239b107b.png)
这个就是目前无法获取的数据，因为无法解析，所以获取不到，但是key存在

**Comment by MaymayJay** [comment]
> 在symfony 的 DefaultMarshaller 中，会根据情况判断当前环境有没有安装igbinary，如果安装了会使用igbinary_serialize序列化数据，而igbinary_serialize序列化的数据就是如果你用serialize()就会不正确，或者你开发环境和正式环境不一样，也会千万不稳定，你可以new RedisAdapter()的时候把第4个构造函数参数使用 new DefaultMarshaller(false)，关掉igbinary_serialize，使用php的serialize()，或者可以实现MarshallerInterface接口，然后实现里面的方法，自定义序列化方案，比如自定义JsonMarshaller类，然后在new RedisAdapter()的时候做为第4个参数传入，redis缓存里面就是json。

方案是有很多种，但是目前想的是为什么会出现这个，以及如何修复这个。为后面的朋友，不需要增加额外的代码逻辑 开箱即用

**Comment by laraveler** [comment]
> > 在symfony 的 DefaultMarshaller 中，会根据情况判断当前环境有没有安装igbinary，如果安装了会使用igbinary_serialize序列化数据，而igbinary_serialize序列化的数据就是如果你用serialize()就会不正确，或者你开发环境和正式环境不一样，也会千万不稳定，你可以new RedisAdapter()的时候把第4个构造函数参数使用 new DefaultMarshaller(false)，关掉igbinary_serialize，使用php的serialize()，或者可以实现MarshallerInterface接口，然后实现里面的方法，自定义序列化方案，比如自定义JsonMarshaller类，然后在new RedisAdapter()的时候做为第4个参数传入，redis缓存里面就是json。
> 
> 方案是有很多种，但是目前想的是为什么会出现这个，以及如何修复这个。为后面的朋友，不需要增加额外的代码逻辑 开箱即用

如果你php安装了igbinary，symfony封装的序列化用的是igbinary_serialize，反序列化也是使用igbinary_unserialize就能成功，但如果你单独从缓存中读取了缓存，使用unserialize反序列化，那就会失败，要使用igbinary_unserialize来操作。

**Comment by MaymayJay** [comment]
> > > 在symfony 的 DefaultMarshaller 中，会根据情况判断当前环境有没有安装igbinary，如果安装了会使用igbinary_serialize序列化数据，而igbinary_serialize序列化的数据就是如果你用serialize()就会不正确，或者你开发环境和正式环境不一样，也会千万不稳定，你可以new RedisAdapter()的时候把第4个构造函数参数使用 new DefaultMarshaller(false)，关掉igbinary_serialize，使用php的serialize()，或者可以实现MarshallerInterface接口，然后实现里面的方法，自定义序列化方案，比如自定义JsonMarshaller类，然后在new RedisAdapter()的时候做为第4个参数传入，redis缓存里面就是json。
> > 
> > 
> > 方案是有很多种，但是目前想的是为什么会出现这个，以及如何修复这个。为后面的朋友，不需要增加额外的代码逻辑 开箱即用
> 
> 如果你php安装了igbinary，symfony封装的序列化用的是igbinary_serialize，反序列化也是使用igbinary_unserialize就能成功，但如果你单独从缓存中读取了缓存，使用unserialize反序列化，那就会失败，要使用igbinary_unserialize来操作。

实际的问题就是，在没有安装igbinary，使用的的serialize，在这一步出现了问题，存入redis 的数据中包含特殊字符，最后导致unserialize无法正常解析数据，导致获取失败。

**Comment by renjunchi** [comment]
![image](https://user-images.githubusercontent.com/7802934/111858177-cf782780-8971-11eb-850d-09f7a8d4a6ef.png)
Yii2.0.14也是无法写入，系统版本是CentOS8.2

**Comment by awanganddong** [comment]
直接存redis里边


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月20日(周六) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [w7corp/easywechat] 偶发性无法获取缓存中的access_token (#1860)




 

 Yii2.0.14也是无法写入，系统版本是CentOS8.2
 
&mdash;

**Comment by Abner1995** [comment]
php -m | grep 'igbinary'

> 测试环境安装了igbinary 貌似就没出现类似得问题。。继续观察ing
还是会出现的
