### ISSUE TITLE
关于微信支付委托代扣 API 变更的相关问题

### ISSUE THREAD

**Issue by reallyli** [w7corp/easywechat#1880]
## 使用扩展包

- https://github.com/overtrue/wechat/

## 版本

- "overtrue/laravel-wechat":"~5.0"

## API

- 微信支付 - 申请扣款 API
- https://github.com/overtrue/wechat/blob/2d2ec7088d2186415773900937cd97e844a7f205/src/Payment/Contract/Client.php#L92

```
public function apply(array $params)
{
        $params['appid'] = $this->app['config']->app_id;

        return $this->safeRequest('papay/pappayapply', $params);
}
```

## 微信官方

| 请求Url | https://api.mch.weixin.qq.com/pay/pappayapply |
| 是否需要证书 | 否 |
| 请求方式 | post |
| 返回参数说明 | 扣款接口请求成功，返回success仅代表扣款申请受理成功，不代表扣款成功。扣款是否成功以支付通知的结果为准。 |

## API 版本不兼容

![Laravel](https://cdn.learnku.com/uploads/images/202007/01/11918/G5sWgONVqb.png!large)

![Laravel](https://cdn.learnku.com/uploads/images/202007/01/11918/zbPIU2pJlN.png!large)

## 待解决

- [@overtrue](https://learnku.com/users/76) 是否有时间可以兼容这个 API 的变更

## 疑问

- 微信支付的 API 变更，新版本和旧版本文档大家哪里可以看到

**Comment by reallyli** [comment]
@overtrue  抽空帮忙看看，感谢

**Comment by overtrue** [comment]
他们改 API 都不发通知的吗

**Comment by reallyli** [comment]
> 他们改 API 都不发通知的吗

是啊 我也纳闷呢 其他几个有的没改，还是 papay 🙄

**Comment by ilchin** [comment]
这个Api网址还没有修复过来嘛？我更新到最新的版本还是报404错误呢。

**Comment by ilchin** [comment]
官方的Api网址为
`https://api.mch.weixin.qq.com/pay/pappayapply`
也就是说
`pay/pappayapply`
现在SDK里面请求的则是
`papay/pappayapply`
希望修正过来呢。

**Comment by overtrue** [comment]
@ilchin  你所谓的最新版是多少？ https://github.com/overtrue/wechat/blob/4.x/src/Payment/Contract/Client.php#L84
