### ISSUE TITLE
目前是否支持微信分账接口? , 没有找到对应的API

### ISSUE THREAD

**Issue by akuang1** [w7corp/easywechat#1938]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：5.0
* 是否使用了框架？框架名称：laravel

## 问题及现象
是否支持微信分账

**Comment by akuang1** [comment]
已找到相关文档 , 谢谢!

**Comment by akuang1** [comment]
https://github.com/EasyWeChat/docs/blob/master/payment/ProfitSharing.md

**Comment by osangma** [comment]
文档地址404了，老铁

**Comment by overtrue** [comment]
https://github.com/EasyWeChat/docs/blob/master/payment/profit-sharing.md

**Comment by akuang1** [comment]
谢谢

安正超 <notifications@github.com> 于2020年11月27日周五 下午12:34写道：
