### ISSUE TITLE
tp5.0设置的config没有生效

### ISSUE THREAD

**Issue by zengliang2608** [w7corp/easywechat#1964]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：是 tp5.0

## 问题及现象

<img width="519" alt="WX20201116-191807@2x" src="https://user-images.githubusercontent.com/16098411/99246866-f64a1400-2840-11eb-925c-1cfba1018f6b.png">

**Comment by zengliang2608** [comment]
$config = array(
            'app_id' => 'wx47fd3a4236bd',
            'secret' => '4cfe39f3f2f9917ec7512e30d',
            'token'     => 'easywechat',
            'log' => [
                'level' => 'debug',
                'file'  => '/tmp/easywechat.log',
            ],
        );

        $app = Factory::MiniProgram($config);

**Comment by overtrue** [comment]
配置问题请自行解决哈
