### ISSUE TITLE
swoole 框架在微信支付回调拿不到数据 Invalid request XML

### ISSUE THREAD

**Issue by ftlh2005** [w7corp/easywechat#1974]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：imiphp 

## 问题及现象
handlePaidNotify
Invalid request XML

**Comment by her-cat** [comment]
麻烦提供相关的使用代码。

**Comment by overtrue** [comment]
swoole 不是 fpm 模式，请自行适配。

**Comment by ftlh2005** [comment]
> swoole 不是 fpm 模式，请自行适配。

能不能提供一个DEMO

**Comment by overtrue** [comment]
@ftlh2005 我不用 swoole ...

**Comment by jonny77** [comment]
> ## 我用的环境
> * PHP 版本：7.2
> * overtrue/wechat 版本：
> * 是否使用了框架？框架名称：imiphp
> 
> ## 问题及现象
> handlePaidNotify
> Invalid request XML

解决了吗?我用的hyperf也不行

**Comment by Lance-93** [comment]
swoole框架需要重新绑定request,例子：hyperf框架 参考：
`use Symfony\Component\HttpFoundation\Request;
`


`     $get = $this->request->getQueryParams();
        $post = $this->request->getParsedBody();
        $cookie = $this->request->getCookieParams();
        $files = $this->request->getUploadedFiles();
        $server = $this->request->getServerParams();
        $xml = $this->request->getBody()->getContents();

        $app['request'] = new Request($get, $post, [], $cookie, $files, $server, $xml);

        $response = $app->handlePaidNotify(function ($message, $fail) use ($app) {
        //收到回调
       });
       $response->send();
`
