### ISSUE TITLE
php8  libxml_disable_entity_loader() is deprecated 

### ISSUE THREAD

**Issue by lee1031** [w7corp/easywechat#1982]
## 我用的环境

* PHP 版本：8.0.0

## 问题及现象

ERROR: Invalid message content:(0) Function libxml_disable_entity_loader() is deprecated {"exception":"[object] (EasyWeChat\\Kernel\\Exceptions\\BadRequestException(code: 0): Invalid message content:(0) Function libxml_disable_entity_loader() is deprecated at /var/www/html/vendor/w7corp/easywechat/src/Kernel/ServerGuard.php:339)

**Comment by involvements** [comment]
4.0同样有此问题，是否能将此commit发布到4.0？
