### ISSUE TITLE
5.2.0以后的更新没有推到https://packagist.org/

### ISSUE THREAD

**Issue by carlwangx** [w7corp/easywechat#1983]
## 我用的环境

* PHP 版本：PHP8
* overtrue/wechat 版本：5.2.0
* 是否使用了框架？框架名称：lumen

## 问题及现象

5.2.0以后的更新没有推到https://packagist.org/，没法安装到

**Comment by overtrue** [comment]
https://packagist.org/packages/overtrue/wechat 好了
