### ISSUE TITLE
4.x版本的小程序怎么获取用户信息

### ISSUE THREAD

**Issue by zeroone2005** [w7corp/easywechat#1986]
请问 4.x版本的小程序怎么获取用户信息，有这个方法吗

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/4.x/mini-program/auth

**Comment by overtrue** [comment]
再结合服务端解密部分拿： https://developers.weixin.qq.com/miniprogram/dev/api/open-api/user-info/wx.getUserInfo.html

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/5.x/mini-program/decrypt
