### ISSUE TITLE
not support php8.0

### ISSUE THREAD

**Issue by haohetao** [w7corp/easywechat#1987]
## 我用的环境

* PHP 版本：8.0.0
* overtrue/wechat 版本：4.3.2
* 是否使用了框架？框架名称：yii2

## 问题及现象

2020-12-07 10:33:46 [192.168.31.23][-][-][error][yii\base\ErrorException:64] yii\base\ErrorException: Method EasyWeChat\Kernel\Support\Collection::__set_state() must take exactly 1 argument in /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/Kernel/Support/Collection.php:343
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2020-12-07 10:33:45 [192.168.31.23][-][-][info][application] $_GET = []

$_POST = []

$_FILES = []

$_COOKIE = [
    'php-console-server' => '5'
]

$_SERVER = [
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi'
    'HOSTNAME' => 'ab0d9be0d188'
    'PHP_INI_DIR' => '/usr/local/etc/php'
    'HOME' => '/var/www'
    'PHP_LDFLAGS' => '-Wl,-O1 -pie'
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    'PHP_VERSION' => '8.0.0'
    'GPG_KEYS' => '1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F'
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    'PHP_ASC_URL' => 'https://www.php.net/distributions/php-8.0.0.tar.xz.asc'
    'PHP_URL' => 'https://www.php.net/distributions/php-8.0.0.tar.xz'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'LANG' => 'zh_CN.utf8'
    'PHPIZE_DEPS' => 'autoconf          dpkg-dev                file            g++             gcc             libc-dev                make            pkg-config              re2c'
    'PWD' => '/var/www/html'
    'PHP_SHA256' => 'b5278b3eef584f0c075d15666da4e952fa3859ee509d6b0cc2ed13df13f65ebb'
    'USER' => 'www-data'
    'HTTP_HOST' => 'api.yunshop.youtuoapp.com'
    'HTTP_REFERER' => 'http://api.yunshop.youtuoapp.com/site/gett'
    'HTTP_COOKIE' => 'php-console-server=5'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
    'HTTP_POSTMAN_TOKEN' => '9fe11f05-6d28-4d63-aaff-42b51e3c2509'
    'HTTP_CACHE_CONTROL' => 'no-cache'
    'HTTP_ACCEPT' => '*/*'
    'HTTP_USER_AGENT' => 'PostmanRuntime/7.26.8'
    'HTTP_AUTHORIZATION' => '***'
    'HTTP_STORE_NO' => '32203336'
    'PATH_INFO' => ''
    'SCRIPT_FILENAME' => '/var/www/yunshop-yunshop/api/web/index.php'
    'REDIRECT_STATUS' => '200'
    'SERVER_NAME' => 'api.yunshop.youtuoapp.com'
    'SERVER_PORT' => '443'
    'SERVER_ADDR' => '192.168.10.11'
    'REMOTE_PORT' => '51692'
    'REMOTE_ADDR' => '192.168.31.23'
    'SERVER_SOFTWARE' => 'nginx/1.18.0'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'HTTPS' => 'on'
    'REQUEST_SCHEME' => 'https'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/var/www/yunshop-yunshop/api/web'
    'DOCUMENT_URI' => '/index.php'
    'REQUEST_URI' => '/site/gett'
    'SCRIPT_NAME' => '/index.php'
    'CONTENT_LENGTH' => ''
    'CONTENT_TYPE' => ''
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1607308425.8746
    'REQUEST_TIME' => 1607308425
    'argv' => []
    'argc' => 0
]

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/4.3.3

**Comment by Mitirrli** [comment]
packagist上没有4.3.3

composer require w7corp/easywech
at:4.3.3 -vvv 提示
____________________________
[InvalidArgumentException]          
  Could not find package w7corp/easy  
  wechat in a version matching 4.3.3

**Comment by overtrue** [comment]
可以了哈

**Comment by Mitirrli** [comment]
可以了 谢谢
