### ISSUE TITLE
[自定义缓存]不能够用cache_key区分是什么缓存

### ISSUE THREAD

**Issue by xiashaung** [w7corp/easywechat#1990]
## 我用的环境

* PHP 版本：7.4.5
* overtrue/wechat 版本：5.0
* 是否使用了框架？框架名称：laravel 8

## 问题及现象
自定义缓存服务
我们是使用了python开发了所有获取token及ticket的服务.在使用报过程中发现获取component_access_token和authorizer_access_token时缓存的key是<easywechat.kernel.access_token.>开头的
希望能做到
         component_access_token  缓存key   easywechat.open_platform.component_access_token.
         authorizer_access_token  缓存key   easywechat.open_platform.authorizer_access_token.
类似于上面那样距离的区分

**Comment by overtrue** [comment]
6.x 已支持，5.x 暂不做破坏性变更，如果有更好的建议可以 PR。
