### ISSUE TITLE
EasyWechat默认日志输出到CGI，导致502

### ISSUE THREAD

**Issue by YaRauy** [w7corp/easywechat#1993]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：4.3.1
* 是否使用了框架？框架名称：Yii2.0
* 服务器：Nginx

## 问题及现象

项目接口调用 `openPlatform->code_template->list()`获取获取小程序模板列表时，报502错误。

检查过fpm网关和Nginx日志，发现，接口返回的header里把微信接口返回的信息带上了，导致header过长，无法正常返回：
```
upstream sent too big header while reading response header from upstream
```

### 代码片段：
配置：
```php
       $config = [
            'app_id' => 'xxx',
            'secret' =>  'xxx',
            'token' => 'xxx',
            'aes_key' =>  'xxx',
        ];
        
        $this->openPlatform = Factory::openPlatform($config);
```

接口调用（关键代码）：
```php
$result = $this->openPlatform->code_template->list();
$result['template_list'] = [current($result['template_list'])];
//在此处写入log到数据库，result数据正常写入
//...此处省略写数据库log查错的代码
return $result;

```

在配置中添加日志配置`log`后，问题才得到解决。

## 希望做以下修改：
1. 默认不要开启debug
2. 日志不要输出到cgi

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/4.3.4

**Comment by haohetao** [comment]
这个应该是nginx也有bug
https://github.com/docker-library/php/issues/878
