### ISSUE TITLE
response_type设为object一列系调用会报错

### ISSUE THREAD

**Issue by haohetao** [w7corp/easywechat#1995]
## 我用的环境

* PHP 版本：7.4.13
* overtrue/wechat 版本：4.3.4
* 是否使用了框架？框架名称：yii2

## 问题及现象
config配置response_type为object，就会出现一列系接口报错，目前发现的有如下
$openPlatform->getPreAuthorizationUrl()
$openPlatform->server->serve()
错误日志如下:
>2020-12-22 21:37:59 [172.23.0.10][-][-][error][Error] Error: Cannot use object of type stdClass as array in /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/OpenPlatform/Server/Handlers/VerifyTicketRefreshed.php:42
Stack trace:
#0 /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/Kernel/Traits/Observable.php(250): EasyWeChat\OpenPlatform\Server\Handlers\VerifyTicketRefreshed->handle(Object(stdClass))
#1 [internal function]: EasyWeChat\Kernel\ServerGuard->EasyWeChat\Kernel\Traits\{closure}(Object(stdClass))
#2 /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/Kernel/Traits/Observable.php(213): call_user_func_array(Object(Closure), Array)
#3 /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/Kernel/Traits/Observable.php(150): EasyWeChat\Kernel\ServerGuard->callHandler(Object(Closure), Object(stdClass))
#4 /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/Kernel/Traits/Observable.php(128): EasyWeChat\Kernel\ServerGuard->notify('component_verif...', Object(stdClass))
#5 /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/OpenPlatform/Server/Guard.php(47): EasyWeChat\Kernel\ServerGuard->dispatch('component_verif...', Object(stdClass))
#6 /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/Kernel/ServerGuard.php(105): EasyWeChat\OpenPlatform\Server\Guard->resolve()
#7 /var/www/yunshop-yunshop/merchant/controllers/WechatPlatformController.php(9): EasyWeChat\Kernel\ServerGuard->serve()
#8 [internal function]: merchant\controllers\WechatPlatformController->actionCreate()

> 2020-12-22 21:49:08 [172.23.0.10][-][-][error][Error] Error: Cannot use object of type stdClass as array in /var/www/yunshop-yunshop/vendor/overtrue/wechat/src/OpenPlatform/Application.php:112
Stack trace:
#0 /var/www/yunshop-yunshop/merchant/controllers/WechatPlatformController.php(2): EasyWeChat\OpenPlatform\Application->getPreAuthorizationUrl('https://wx.shua...')
#1 [internal function]: merchant\controllers\WechatPlatformController->actionAuth('ZwAk+QkwrUsnbRe...', '2')
#2 /var/www/yunshop-yunshop/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/yunshop-yunshop/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/yunshop-yunshop/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('auth', Array)
#5 /var/www/yunshop-yunshop/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('wechat-platform...', Array)
#6 /var/www/yunshop-yunshop/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 /var/www/yunshop-yunshop/merchant/web/index.php(17): yii\base\Application->run()

## 建议

easywechat内部应根据response_type设置的类型解析并读取数据或始终用array方式解析数据

**Comment by haohetao** [comment]
@overtrue 
看一下能不能改

**Comment by haohetao** [comment]
@overtrue thanks

**Comment by overtrue** [comment]
客气

**Comment by haohetao** [comment]
@overtrue 
我这composer拉取不到呀，用4.x-dev也不行
https://packagist.org/packages/overtrue/wechat#4.x-dev

**Comment by overtrue** [comment]
请再试

**Comment by haohetao** [comment]
@overtrue 
可以了

**Comment by overtrue** [comment]
好的
