### ISSUE TITLE
希望能有golang版本的

### ISSUE THREAD

**Issue by Dante666999** [w7corp/easywechat#1998]
看了下，这个不错，但是，我现在用的是golang，要是能有go版本就好了，

**Comment by fideism** [comment]
https://github.com/fideism/golang-wechat

正在封，一起来写呀

**Comment by overtrue** [comment]
抱歉没那么多时间哦，有兴趣可以跟楼上组队玩。

**Comment by golang730** [comment]
> https://github.com/fideism/golang-wechat
> 
> 正在封，一起来写呀
好啊，我先下来看看
