### ISSUE TITLE
建议增加外部联系人userIdToOpenid的API

### ISSUE THREAD

**Issue by geekabin** [w7corp/easywechat#2007]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：4.x
* 是否使用了框架？框架名称：hyperf

## 问题及现象

外部联系人openid转换
https://work.weixin.qq.com/api/doc/90000/90135/92323

**Comment by aa24615** [comment]
已经有了
https://www.easywechat.com/docs/4.x/wework/contacts#heading-h3-7

**Comment by geekabin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
