### ISSUE TITLE
公众号服务器验证直接就没有做校验？

### ISSUE THREAD

**Issue by zhao0229** [w7corp/easywechat#2008]
## laravel 8

* PHP 版本：7.3
* overtrue/wechat 版本：5.1
* 是否使用了框架？框架名称：laravel 8

## 问题及现象

公众号填写到微信后台的服务器地址没有对收到的参数进行校验？我自己请求那个地址时，乱填都能通过，还是我搞错了？

`        $OfficialAccount = $this->getOfficialAccount($oaID);
        $config = [
            'app_id'=>$OfficialAccount->AppId,
            'secret'=>$OfficialAccount->AppSecret,
            'token'=>$OfficialAccount->Token,
            'aes_key'=>$OfficialAccount->EncodingAESKey,
            'response_type'=>'array',
        ];
        $app = Factory::officialAccount($config);
        $response = $app->server->serve();
        return $response;
`

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/blob/develop/src/Kernel/ServerGuard.php#L107
https://github.com/w7corp/easywechat/blob/develop/src/Kernel/ServerGuard.php#L119-L133
https://github.com/w7corp/easywechat/blob/develop/src/Kernel/ServerGuard.php#L348-L352
