### ISSUE TITLE
建议新增微信开放平台网页授权登录

### ISSUE THREAD

**Issue by dongyao8** [w7corp/easywechat#2020]
开发网页扫码登录时候，需要用到微信第开放平台的网页授权应用，发现easywechat文档没有相关内容，建议新增

**Comment by shirne** [comment]
大佬的socialite库有这个功能。
https://github.com/overtrue/socialite#wechat

**Comment by greedying** [comment]
有是有，就是不够方便。建议是和微信公众号的 oauth 对齐
