### ISSUE TITLE
第三方代公众号实现网页授权 报40001，component_access_token最新

### ISSUE THREAD

**Issue by zhangzheng7856** [w7corp/easywechat#2026]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.4
* 是否使用了框架？框架名称：Thinkphp5.1

## 问题及现象
第三方代公众号实现网页授权 报40001，token刷新无数次，由于是小项目，把easywechat版本回退到4.X，php版本切换到7.2，方可正常使用，还有就是api变化，以前是$oauth->user(); 现在是$oauth->userFromCode();折腾了一个晚上，新版本还是有点问题的

**Comment by overtrue** [comment]
大版本号变化，方法名变化是正常的哈，不然也不会发大版本。另外 token 刷新无数次请检查你的缓存写入情况。

**Comment by millsguo** [comment]
还是建议写个兼容4.X的方法，这样体验更好点

> 大版本号变化，方法名变化是正常的哈，不然也不会发大版本。另外 token 刷新无数次请检查你的缓存写入情况。
