### ISSUE TITLE
小程序的UrlScheme调用不起来

### ISSUE THREAD

**Issue by keventseng** [w7corp/easywechat#2027]
$app = Factory::miniProgram($config);
$response = $app->url_scheme->generate($data);

Fatal error: Uncaught Pimple\Exception\UnknownIdentifierException: Identifier "url_scheme" is not defined.

**Comment by overtrue** [comment]
哪个版本？麻烦提问的时候按模板填写，谢谢合作。

**Comment by keventseng** [comment]
实在不好意思~没按模板填写。

name     : overtrue/wechat
descrip. : 微信SDK
keywords : easywechat, sdk, wechat, weixin, weixin-sdk
versions : * 5.4.0
type     : library

**Comment by overtrue** [comment]
确认你本地是否有这些文件先：https://github.com/w7corp/easywechat/tree/5.x/src/MiniProgram/UrlScheme

**Comment by keventseng** [comment]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/5266604/105476919-2b109680-5cdc-11eb-9798-329005e0b004.png">
有的

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/5.4.1

**Comment by keventseng** [comment]
我在提问前已经尝试修改注册这个服务，但仍然不可用。

**Comment by overtrue** [comment]
@keventseng 怎么修改的？

**Comment by keventseng** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/5266604/105480559-dfacb700-5ce0-11eb-878c-1b5a4d096799.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/5266604/105480588-e804f200-5ce0-11eb-8008-fb353983a89e.png">

**Comment by overtrue** [comment]
更新版本后试试吧
