### ISSUE TITLE
微信公众号已经全线回收了“摇一摇周边”能力，相关功能代码和文档可以移除了。

### ISSUE THREAD

**Issue by manhere** [w7corp/easywechat#2032]
## 我用的环境

* PHP 版本：all
* overtrue/wechat 版本：all
* 是否使用了框架？框架名称：all

## 问题及现象

> 你好，基于平台运营策略考虑，近期我们将对公众号的摇一摇周边、连Wi-Fi能力进行回收，预计一月后正式生效，为避免对你的业务产生影响，建议提早进行调整和切换。

但，**似乎企业微信的不受影响**？待确认。

![yao1yao](https://user-images.githubusercontent.com/580122/105954934-6c27f280-60b0-11eb-8215-4ac827bf1cd2.png)

> 由于公众平台将回收“摇一摇周边”的能力，现不再支持该接口，请使用小程序->API->设备->iBeacon自行实现iBeacon相关功能。

**Comment by overtrue** [comment]
没关系，大版本再移除就好了哈。
