### ISSUE TITLE
'reg_template_id'这是什么东东？

### ISSUE THREAD

**Issue by zxh1220** [w7corp/easywechat#2035]
企业微信参数中，'reg_template_id'      => '注册定制化模板ID',这是什么参数，在哪获取，什么作用，找了一下，没有找到这个参数

**Comment by overtrue** [comment]
哪里来的？

**Comment by zxh1220** [comment]
https://www.easywechat.com/docs/4.x/open-work/index

**Comment by overtrue** [comment]
![Uploading image.png…]()

**Comment by overtrue** [comment]
![image](https://user-images.githubusercontent.com/1472352/106112592-69003580-6188-11eb-9aef-6e5ae72453cd.png)
推广包 ID

**Comment by overtrue** [comment]
https://open.work.weixin.qq.com/api/doc/90001/90143/90581

**Comment by zxh1220** [comment]
可以留空不设置吗

**Comment by overtrue** [comment]
你看一下文档上是否允许为空

**Comment by overtrue** [comment]
如果你不用这个二维码接口看起来就不是必须的

**Comment by zxh1220** [comment]
这推广包ID是自己定义的吧？

**Comment by overtrue** [comment]
抱歉这个我就不清楚了
