### ISSUE TITLE
框架有没有计划支持一下异步请求呢？

### ISSUE THREAD

**Issue by liuxiaojinla** [w7corp/easywechat#2041]
我们这有个业务场景，是同步微信公众号粉丝，如果公众号下的粉丝有1000人左右需要同步10分钟左右，我看了下框架底层使用的GuzzleHttp网络请求库，然后我改造了下框架代码使用异步请求模式的话只需要1分钟左右

**Comment by overtrue** [comment]
这个你应该考虑使用队列去做这类事情，我们的业务每次推送都是10万+，也只需要几分钟而已。
