### ISSUE TITLE
多公众号支付回调如何动态选择appid

### ISSUE THREAD

**Issue by yulin1115** [w7corp/easywechat#2042]
项目里可以配置多个小程序，不同的小程序支付回调通知，如何能对应到相关小程序的appid，文档上的回调通知是在通知之前就配置appid了
$config = [
    // 必要配置
    'app_id'             => 'xxxx',
    'mch_id'             => 'your-mch-id',
    'key'                => 'key-for-signature',   // API 密钥

    // 如需使用敏感接口（如退款、发送红包等）需要配置 API 证书路径(登录商户平台下载 API 证书)
    'cert_path'          => 'path/to/your/cert.pem', // XXX: 绝对路径！！！！
    'key_path'           => 'path/to/your/key',      // XXX: 绝对路径！！！！

    'notify_url'         => '默认的订单回调地址',     // 你也可以在下单时单独设置来想覆盖它
];
$app = Factory::payment($config);
$response = $app->handlePaidNotify(function ($message, $fail) {
    // 你的逻辑
    return true;
    // 或者错误消息
    $fail('Order not exists.');
});

$response->send();

**Comment by overtrue** [comment]
你可以在通知 URL 上下功夫哈

**Comment by yulin1115** [comment]
> 你可以在通知 URL 上下功夫哈

多谢，我手动从xml中获取appid了

**Comment by overtrue** [comment]
也可以的，URL 会比较简单一点
