### ISSUE TITLE
为什么公众号不提供  $app->auth->session(string $code); 接口

### ISSUE THREAD

**Issue by nirvana72** [w7corp/easywechat#2044]
为什么公众号不提供  $app->auth->session(string $code); 接口

**Comment by overtrue** [comment]
麻烦问微信噢，我也不知道为啥

**Comment by nirvana72** [comment]
瞧你这回复的， 微信有，easywechat没有我才问的

公众号开发， 确实也需要用到这个接口， 业务开发openid总是必须的吧
![image](https://user-images.githubusercontent.com/15214079/111242426-1bf1f900-863a-11eb-840f-2907cd9d9dba.png)

小程序模块有这个功能， 公众号开发也需要这个功能啊， 
![image](https://user-images.githubusercontent.com/15214079/111242692-a2a6d600-863a-11eb-8334-a0f51c54af65.png)

我想问的是， 腾讯对于小程序和公众号都有https://api.weixin.qq.com/sns/oauth2/access_token接口
为啥easywechat只为小程序写了$app->auth->session(string $code);  而没有为公众号写

**Comment by overtrue** [comment]
1. 请贴出微信有 code2session 接口的证明。
2. 请贴出小程序有 oauth2/access_token 的证明。

谢谢老板！

**Comment by nirvana72** [comment]
![image](https://user-images.githubusercontent.com/15214079/111246668-a68a2680-8641-11eb-8528-615f7fffa23a.png)
![image](https://user-images.githubusercontent.com/15214079/111246757-cb7e9980-8641-11eb-8191-9ca6de420e90.png)

接口名字不同，但参数和功能使用场景都相同

**Comment by overtrue** [comment]
接口不同就有不同的方法调用啊，https://www.easywechat.com/docs/5.x/official-account/oauth 网页授权就是网页授权，网页授权是 OAuth 协议，小程序授权并不是 OAuth, 凭啥要搞成一样？OAuth 就用 OAuth 的用法就用好了。

**Comment by nirvana72** [comment]
算了，我就想问下， 想来应该是我理解不够吧， 不知道你哪来这么大反应， 你就当是我个菜鸟， 甭理我了

**Comment by overtrue** [comment]
菜不菜没关系，但是不应该先下定论，而是先了解差异，不是上来先给对方定个错一般的讨论。

**Comment by nirvana72** [comment]
牛人就是不一样， 见识了，谢谢老板

**Comment by overtrue** [comment]
文档首页就说了：1. 先熟悉微信的官方文档。 概念搞清楚了再动手，不然每天都 N 个人来问的话，我哪里来这么多时间回复呢？互相理解一下。
