### ISSUE TITLE
php 8 Function libxml_disable_entity_loader() is deprecated

### ISSUE THREAD

**Issue by badazhou** [w7corp/easywechat#2050]
## 我用的环境

* PHP 版本：php8
* overtrue/wechat 版本：4.4.0
* 是否使用了框架？框架名称：laravel

## 问题及现象

php 8 Function libxml_disable_entity_loader() is deprecated

File: overtrue/wechat/src/Kernel/Support/XML.php

**Comment by ziyoren** [comment]
我也遇到这个问题了
