### ISSUE TITLE
最近有计划把微信小商店加入框架里面吗？

### ISSUE THREAD

**Issue by liuxiaojinla** [w7corp/easywechat#2052]
微信小商店：https://developers.weixin.qq.com/miniprogram/dev/framework/ministore/minishopopencomponent/guideline.html

**Comment by elim051** [comment]
同求

**Comment by elim051** [comment]
也不知道有计划了吗？

**Comment by overtrue** [comment]
新版(v6)将支持全部接口，v5 暂时还没有哦。

**Comment by liuxiaojinla** [comment]
v6的接口调用当然变化大吗？发自我的华为手机-------- 原始邮件 --------发件人： 安正超 ***@***.***>日期： 2021年6月15日周二 16:10收件人： w7corp/easywechat ***@***.***>抄送： 刘小晋啦 ***@***.***>, Author ***@***.***>主    题： Re: [w7corp/easywechat] 最近有计划把微信小商店加入框架里面吗？ (#2052)

新版(v6)将支持全部接口，v5 暂时还没有哦。

**Comment by elim051** [comment]
@overtrue , 新版（v6）大概什么时候发布呢？谢谢。

**Comment by overtrue** [comment]
8月吧

> @overtrue , 新版（v6）大概什么时候发布呢？谢谢。

**Comment by elim051** [comment]
期待。。。

**Comment by ty-team** [comment]
> 8月吧
> 
> > @overtrue , 新版（v6）大概什么时候发布呢？谢谢。

已经到8月了。计划是哪一天发布呢

**Comment by overtrue** [comment]
@ty-team 你已经可以开始体验beta 版本了：

```php
$ composer require w7corp/easywechat:6.0.0-beta.1
```

**Comment by ty-team** [comment]
> @ty-team 你已经可以开始体验beta 版本了：
> 
> ```
> $ composer require w7corp/easywechat:6.0.0-beta.1
> ```

好的。我体验下，谢谢
