### ISSUE TITLE
自从卖给微擎以后更新就变慢了，回答也慢了

### ISSUE THREAD

**Issue by ljyljy0211** [w7corp/easywechat#2053]
自从卖给微擎以后更新就变慢了，回答也慢了，大家有没有发现

**Comment by overtrue** [comment]
1. 开源产品不收费也没有义务回答问题，更没有义务保证回复的效率。
2. 和卖不卖没关系，是个人都要生存，我有我的工作和生活，做开源是空闲时间的事情，大家都有忙有闲，我并不是每天在家坐着就负责处理这个项目的事情。
3. 开源产品，开源共建，任何人都可以提交合理的改进建议，并不只是伸手。
4. 感谢理解。
