### ISSUE TITLE
上传临时素材含中文文件名报错

### ISSUE THREAD

**Issue by huzhangzheng** [w7corp/easywechat#2054]
## 我用的环境

* PHP 版本：7.2.22
* overtrue/wechat 版本：5.1.0
* 是否使用了框架？框架名称：lumen

## 问题及现象
```  
//  获取实例
$app = Factory::work($config);
 // 上传临时文件素材
$media = $app->media->uploadFile("http://baidu.com/中文.pdf");
```

1.在使用本包上传中文素材异常，追踪到EasyWeChat\Kernel\BaseClient::httpUpload()方法112行
fopen报错

2.之后对url中中文部分做了编码，可以上传了，推送给用户企业微信消息后，文件名是编码后的文件名。我们的需求还是要中文名称。

请问：如何在不编码中文的情况下上传素材？感谢。

**Comment by overtrue** [comment]
临时素材你要中文名干嘛？上传后又看不见

**Comment by huzhangzheng** [comment]
> 临时素材你要中文名干嘛？上传后又看不见
我要推送企业微信小程序文件消息呀，不是必须要先上传临时素材吗？我的文件名是中文的

**Comment by overtrue** [comment]
那就 url encode 再传咯

**Comment by huzhangzheng** [comment]
![image](https://user-images.githubusercontent.com/12509847/113657735-22234480-96d1-11eb-8241-3283fa387b09.png)
确实上传上去了，可是他这个消息里收到的文件名也被编码了，我们需要中文名称。

**Comment by overtrue** [comment]
这个消息是你自己推送的把？自己推的就自己处理一下啊
