### ISSUE TITLE
通过netstat命令发现大量CLOSE_WAIT，连接没有关闭

### ISSUE THREAD

**Issue by linyaosnsd** [w7corp/easywechat#2057]
## 我用的环境

* PHP 版本：7.4.12
* overtrue/wechat 版本：4.x
* 是否使用了框架？框架名称：yii2

## 问题及现象

```php
use EasyWeChat\Factory;

$app = Factory::payment([
            // 必要配置
            'app_id' => '**********',
            'mch_id' => '**********',
            'key' => '**********',
            'cert_path' => '**********',
            'key_path' => '**********',
        ]);
$app->order->unify([
            'body' => '订单支付',
            'out_trade_no' => '**********',
            'total_fee' => '**********',
            'notify_url' => '**********',
            'openid' => '**********',
            'trade_type' => 'JSAPI',
        ]);
```
通过netstat命令发现
```php
tcp       32      0 192.168.0.152:35530     210.22.240.140:443      CLOSE_WAIT  20466/ai:worker0
```
连接没有关闭

**Comment by overtrue** [comment]
这个逻辑就是普通的 PHP curl 调用而已。

**Comment by linyaosnsd** [comment]
可是不关闭的话，服务器迟早会因为端口堵塞而崩溃的吧。
我网上查了一下资料，貌似需要在header设置Connection:close。

**Comment by overtrue** [comment]
你怎么确认你的 CLOSE_WAIT 是上面这段代码跑出来的？

**Comment by overtrue** [comment]
请求量大的时候 CLOSE_WAIT 是正常的，除非这个连接一直这个状态持续很久，否则你可能看到的是大量的下单请求在逐渐关闭而已。

**Comment by overtrue** [comment]
不过你最好先确定是上面这段代码的 fpm 造成的先。

**Comment by linyaosnsd** [comment]
那条tcp记录对应的pid，我查了一下端口，我能够确定只有我在测试使用。
这条tcp记录我是上午测试的，到目前为止还一直存在。
我还发现一点，就是guzzlehttp/guzzle这个包，我在别的地方也有使用，发现了同样connect没有关闭的情况，我去这个包的github下面，发现issue里面已经有提到过。https://github.com/guzzle/guzzle/issues/1977#issuecomment-351448808

**Comment by linyaosnsd** [comment]
还有一点就是，这个问题应该只是出现在swoole的项目上，我试了一下，在正常的lnmp环境下，是没有这个问题的。在swoole的微服务架构项目上出现了这个问题。
0.0。。。。。

**Comment by overtrue** [comment]
swoole 你就需要自己解决了哈。
