### ISSUE TITLE
网页授权报错 41008 请问怎么搞定呢？

### ISSUE THREAD

**Issue by 422835426** [w7corp/easywechat#2061]
## 我用的环境

* PHP 版本：  php7.3
* overtrue/wechat 版本：5.1
* 是否使用了框架？框架名称：laravel8.0 

## 问题及现象

![image](https://user-images.githubusercontent.com/8399296/114162879-1d25f580-995c-11eb-847d-72e01c784173.png)

**Comment by overtrue** [comment]
报错信息不是写了 missing code 吗？回调的 code 丢了。

**Comment by 422835426** [comment]
这个不是自动走中间件验证的么？我没有写其他的代码

**Comment by overtrue** [comment]
检查一下浏览器跳转过程 URL 是否回调的时候有 code

**Comment by 422835426** [comment]
![image](https://user-images.githubusercontent.com/8399296/114164699-3039c500-995e-11eb-8b2b-3698ee0ecd3f.png)
您好，是不是这里排除了之后就带不过来了呢？

**Comment by overtrue** [comment]
没关系

**Comment by overtrue** [comment]
目测是你的 NGINX 配置有问题，贴一下

**Comment by 422835426** [comment]
您好，code是有的
![image](https://user-images.githubusercontent.com/8399296/114328315-cba18480-9b6e-11eb-9ed7-56841227c8d2.png)

这是nginx配置

  location / {
      try_files $uri @laravels;
  }
  
  location @laravels {
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout 120s;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_pass http://127.0.0.1:5201;
    }

    location ~* \.php$ {
        return 404;
    }
    # Http和WebSocket共存，Nginx通过location区分
    # !!! WebSocket为/ws
    # Javascript: var ws = new WebSocket("ws://laravels.com/ws");
    location =/ws {
        # proxy_connect_timeout 60s;
        # proxy_send_timeout 60s;
        # proxy_read_timeout
        proxy_read_timeout 60s;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header Server-Protocol $server_protocol;
        proxy_set_header Server-Name $server_name;
        proxy_set_header Server-Addr $server_addr;
        proxy_set_header Server-Port $server_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://127.0.0.1:5201;
    }
}

**Comment by 422835426** [comment]
AbstractProvider 文件的user方法 ：
$this->getCode() 获取不到code值，用Request()->all() 可以获取到
$token = $token ?: $this->getAccessToken($this->getCode()); 
$this->getCode()替换为Request()->get('code') 可以解决此问题

**Comment by overtrue** [comment]
sorry, 这个 SDK 不是为  swoole 定制的哈，没法用 request() 函数哦。
