### ISSUE TITLE
为什么要支持7.4？？？7.3不能用了吗

### ISSUE THREAD

**Issue by a6965921** [w7corp/easywechat#2064]
为什么要支持7.4？？？7.3不能用了吗

**Comment by bref0** [comment]
为什么要升级php7,php5不能用了吗

**Comment by ZhangChengLin** [comment]
为什么要维护项目？？？不能用了吗

**Comment by TheNorthMemory** [comment]
哪有那么多「为什么」，干就是了～

**Comment by overtrue** [comment]
> 为什么要升级php7,php5不能用了吗

你可以不用的，没人强迫你

**Comment by ZhangChengLin** [comment]
> > 为什么要升级php7,php5不能用了吗
> 
> 你可以不用的，没人强迫你

认真了啊，看不出来说的是反话么？？
该怼的楼主好不？！！！

**Comment by overtrue** [comment]
@ZhangChengLin 我的锅，早上开车没细看。

总之就是一句话，没那么多为什么，你觉得不合适就找自己合适的用好了。
