### ISSUE TITLE
分账完结接口的问题

### ISSUE THREAD

**Issue by chenliq** [w7corp/easywechat#2065]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.4.0
* 是否使用了框架？框架名称：yaf+equolent

## 问题及现象

分账完结的接口，官方有如下字段：

商户号 | mch_id | 是 | string(32) | 1900000100 | 微信支付分配的商户号
-- | -- | -- | -- | -- | --

文档示例：
$params = [
    "transaction_id" => "",
    "out_order_no"   => "",
    "description"    => ""
];
$payment->profit_sharing->markOrderAsFinished($params);
没有这个mch_id，会造成报错：分账接收方与原请求不一致

**Comment by overtrue** [comment]
@ClouderSky 求 review

**Comment by chenliq** [comment]
> ## 我用的环境
> * PHP 版本：7.4
> * overtrue/wechat 版本：5.4.0
> * 是否使用了框架？框架名称：yaf+equolent
> 
> ## 问题及现象
> 分账完结的接口，官方有如下字段：
> 
> 商户号	mch_id	是	string(32)	1900000100	微信支付分配的商户号
> 文档示例：
> $params = [
> "transaction_id" => "",
> "out_order_no" => "",
> "description" => ""
> ];
> $payment->profit_sharing->markOrderAsFinished($params);
> 没有这个mch_id，会造成报错：分账接收方与原请求不一致

不好意思，找到问题了，是程序BUG，造成接收方值为null。
