### ISSUE TITLE
多个小程序配置  access_token会异常使用

### ISSUE THREAD

**Issue by shishunyi** [w7corp/easywechat#2069]
## 我用的环境

* PHP 版本：7.1
* overtrue/wechat 版本：4.X
* 是否使用了框架？框架名称：thinkphp

## 问题及现象

配置
![image](https://user-images.githubusercontent.com/36780891/116368031-82be2100-a83a-11eb-852e-0b7b6596cb00.png)
实例
![image](https://user-images.githubusercontent.com/36780891/116368099-95385a80-a83a-11eb-90c2-d1c012c36980.png)
根据不同配置实例化类  再根据不同配置获取出来的access_token是同一个，能不能分开存储一下token

**Comment by shishunyi** [comment]
浮现过程
![Uploading image.png…]()

**Comment by shishunyi** [comment]
![image](https://user-images.githubusercontent.com/36780891/116368818-4d660300-a83b-11eb-97d8-ad51aef2e422.png)
浮现过程代码

**Comment by bangbangda** [comment]
我是非常认真的看了下源码，发现不会有这样的问题。
回过头在看你的截图，你打印的 token 也不一样啊。😓
