### ISSUE TITLE
关于缓存 prefix 问题？

### ISSUE THREAD

**Issue by yadgen** [w7corp/easywechat#2072]
## 我用的环境

* PHP 版本：7.3.27
* overtrue/wechat 版本：5.1
* 是否使用了框架？框架名称：Laravel Framework 6.20.22

## 问题及现象
有两套系统，A和B。
第三方平台，授权小程序，授权逻辑在A系统，业务在B系统，redis cache 前缀不一致，会取不到component_verify_ticket。
现在临时的解决方案，只有将两套系统的前缀设置为一致的。

请问如何在使用的时候，动态设置 redis prefix？查了很多相关的资料，均没有找到有效的方法。

```
$openPlatform = app('wechat.open_platform');

config(['database.redis.options.prefix' => 'test']);
$predis = app('redis')->connection()->client();
$cache = new RedisAdapter($predis);
$openPlatform->rebind('cache', $cache);
```

这样似乎无效？

**Comment by yadgen** [comment]
默默的等待大佬回复~

**Comment by overtrue** [comment]
你的 prefix 修改得时候是在 redis 实例创建后吧，这么改应该没用，或者你改完重新实例化一次缓存对象才能用
