### ISSUE TITLE
接口 异步请求

### ISSUE THREAD

**Issue by jackbon8** [w7corp/easywechat#2076]
公众号有10w粉丝 
利用公众号 【消息模板】给10w用户推送通知消息
遍历十万粉丝  逐条请求发送模板消息接口有点慢
请问是否可以考虑 支持异步请求呢

**Comment by overtrue** [comment]
队列多进程自己在业务里去分发就可以了哦，和 SDK 没啥关系的。

**Comment by jackbon8** [comment]
> 
> 
> 队列多进程自己在业务里去分发就可以了哦，和 SDK 没啥关系的。

发送请求不是利用的curl吗？    curl的异步用到了吗

**Comment by jackbon8** [comment]
> 
> 
> 队列多进程自己在业务里去分发就可以了哦，和 SDK 没啥关系的。

好的 谢谢
