### ISSUE TITLE
有办法获取

### ISSUE THREAD

**Issue by a6965921** [w7corp/easywechat#2077]
https://www.easywechat.com/docs/4.x/official-account/user
accesstoken有办法用自己获取的吗 不要用easywechat再生成一次  因为我统一放在数据库中的  然后几个应用都统一用这个的

**Comment by JimChenWYU** [comment]
https://easywechat.com/docs/4.x/customize/access_token

自行实现AccessToken的契约，然后重新绑定自己的类实例就可以了
