### ISSUE TITLE
多进程处理 帮忙看一下有问题吗

### ISSUE THREAD

**Issue by jackbon8** [w7corp/easywechat#2078]
![图片](https://user-images.githubusercontent.com/43921493/117275115-4c168500-ae90-11eb-8740-e7ece5a00151.png)

执行报错：cURL error 35: A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot

**Comment by declandragon** [comment]
用一个不带 NSS 的 curl 库来重新编译 php ？


https://stackoverflow.com/questions/26452755/php-curl-with-nss-is-probably-using-sslv3-instead-of-tls-when-connecting-to-ht#answer-26453701

**Comment by overtrue** [comment]
和 SDK 无关，请自行解决。
