### ISSUE TITLE
该方法没有处理对小程序MiniProgramPage消息的支持

### ISSUE THREAD

**Issue by elim051** [w7corp/easywechat#2081]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：4.x

## 问题及现象
EasyWeChat\Kernel\ServerGuard  
public function buildResponse(string $to, string $from, $message)

https://github.com/w7corp/easywechat/blob/ebe0932d4837f635c96fb8601cde73c02ea9360f/src/Kernel/ServerGuard.php#L226

该方法没有处理针对小程序卡片消息（MiniProgramPage）的处理：
如果给用户发送小程序卡片消息，在执行到buildResponse方法时，会有异常抛出。

[EasyWeChat\Kernel\Exceptions\InvalidArgumentException]
EasyWeChat\Kernel\Exceptions\InvalidArgumentException: Invalid
Messages type "array". in
/webroot/vendor/overtrue/wechat/src/Kernel/ServerGuard.php:239

**Comment by overtrue** [comment]
请正确提问

**Comment by overtrue** [comment]
贴你的代码

**Comment by elim051** [comment]
`$msg = new MiniProgramPage([
        'title' => 'MyTitle',
        'appid' => 'my_app_id',
        'pagepath' => 'pages/index/index',
        'thumb_media_id' => 'media_id',
    ]);
    return $app->customer_service->message($msg)->to($message['FromUserName'])->send();
`
用户关注公众号发送小程序卡片消息，就会抛异常。但是消息会成功发送的

**Comment by overtrue** [comment]
你别 return 就得了啊

**Comment by overtrue** [comment]
但是你的代码 return 的是客服消息的发送结果啊，不是 server->serve() 的结果

**Comment by elim051** [comment]
我完整的代码是这样的：
`$app->server->push(function ($message) {
     $msg = new MiniProgramPage([ 
'title' => 'MyTitle', 'appid' => 'my_app_id', 'pagepath' => 'pages/index/index', 'thumb_media_id' => 'media_id', ]);
 return $app->customer_service->message($msg)->to($message['FromUserName'])->send();
});

$response = $server->serve();`

**Comment by overtrue** [comment]
把你 function 里的 return 去掉。。。

**Comment by elim051** [comment]
> 把你 function 里的 return 去掉。。。

好的，谢谢
