### ISSUE TITLE
laravel-wechat 不能自定义accesstoken 

### ISSUE THREAD

**Issue by a6965921** [w7corp/easywechat#2082]
laravel-wechat 不能自定义accesstoken     
怎么引用自带的获取accesstoken 用我自己的方式获取 不想看源码

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/customize/access_token

**Comment by overtrue** [comment]
不想看源码您倒是看一眼文档啊

**Comment by a6965921** [comment]
> 不想看源码您倒是看一眼文档啊

https://github.com/w7corp/easywechat/issues/2082#issuecomment-839561545  这个方法没用的  我还是会触发easywechat自带的 getaccesstoken  我要把他自带的替换掉啊

**Comment by a6965921** [comment]
https://github.com/w7corp/easywechat/issues/2082#issuecomment-839561545

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/customize/replace-service

**Comment by a6965921** [comment]
> https://easywechat.com/docs/5.x/customize/replace-service

不会用。。。有例子说明吗
