### ISSUE TITLE
循环依赖的问题

### ISSUE THREAD

**Issue by limingxinleo** [w7corp/easywechat#2093]
现在有个问题。。。

就是常驻内存的项目，需要每次实例化Application，而Application的设计是 Container，就是app里有某个service，而这个service又有app，导致了循环依赖。

后面的迭代，有计划修改这里么？

可能最主要的麻烦，是request这里，因为注入到app里了，所以不方便常驻内存，但我这里没有看全部的代码，是否还有其他的位置，不能被常驻内存。

**Comment by jonny77** [comment]
> 现在有个问题。。。
> 
> 就是常驻内存的项目，需要每次实例化Application，而Application的设计是 Container，就是app里有某个service，而这个service又有app，导致了循环依赖。
> 
> 后面的迭代，有计划修改这里么？
> 
> 可能最主要的麻烦，是request这里，因为注入到app里了，所以不方便常驻内存，但我这里没有看全部的代码，是否还有其他的位置，不能被常驻内存。

$payApp = Factory::payment($payConfig);
        $request = di(RequestInterface::class);
        $payApp->rebind('request',$request); hf里面 request的问题 我是这样写的.不知道跟你说的是不是一样的问题

**Comment by limingxinleo** [comment]
是的，我也是这个情况，但因为里面有循环引用，所以这个application不会被释放。。当然，因为也是按需实例化，所以长得不快

**Comment by jonny77** [comment]
> 是的，我也是这个情况，但因为里面有循环引用，所以这个application不会被释放。。当然，因为也是按需实例化，所以长得不快

你是后面会导致内存增长很大?我目前这个用法不知道会不会有问题

**Comment by limingxinleo** [comment]
没有很大，因为php的垃圾回收，也会去收集这一块的内存。不过整体来看，肯定是慢慢增长。如果你们又用了max_request的逻辑，其实不用太担心，我这边max_request设置为0，所以比较尴尬。。。

**Comment by overtrue** [comment]
@limingxinleo 6.x 应该不存在这个问题了。
