### ISSUE TITLE
4.1版本支付结果通知返回true后，微信还是在通知消息

### ISSUE THREAD

**Issue by lovelike123** [w7corp/easywechat#2118]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.1
* 是否使用了框架？框架名称：easyswoole（版本3.3）

## 问题及现象
我在回调地址调用handlePaidNotify，return true后微信还是一直往回调地址通知消息
` $response = $xcxpay->handlePaidNotify(function($message, $fail){
            return true; // 返回处理完成
        });
        $response->send();`

**Comment by bangbangda** [comment]
```
// 试试这样呢
return $response->send();

**Comment by lovelike123** [comment]
return $response->send();这样我试了还是不行 @bangbangda

**Comment by jonny77** [comment]
easyswoole 你能获取到数据? 不是说swoole体系需要自己改动一下request吗
