### ISSUE TITLE
公众号个人信息返回值中没有‘unionid’字段

### ISSUE THREAD

**Issue by ycg9732** [w7corp/easywechat#2119]
## 我用的环境

* PHP 版本：7.1
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：yii2.0

## 问题及现象
公众号个人信息返回值中没有‘unionid’字段

返回值实例：
    "subscribe": 1,
    "openid": "",
    "nickname": "道道",
    "sex": 1,
    "language": "zh_CN",
    "city": "黔江",
    "province": "重庆",
    "country": "中国",
    "headimgurl": "http://thirdwx.qlogo.cn/mm",
    "subscribe_time": 1621345,
    "remark": "",
    "groupid": 0,
    "tagid_list": [],
    "subscribe_scene": "ADD_LINK",
    "qr_scene": 0,
    "qr_scene_str": ""

**Comment by overtrue** [comment]
麻烦看清楚微信文档再用
