### ISSUE TITLE
第三方平台，微信公众号，自动回复视频消息~

### ISSUE THREAD

**Issue by yadgen** [w7corp/easywechat#2124]
## 我用的环境

* PHP 版本："php": "^7.2",
* overtrue/wechat 版本："overtrue/laravel-wechat": "^5.1"
* 是否使用了框架？框架名称："laravel/framework": "^6.0",

## 问题及现象

用户向公众号发送一条视频消息，公众号自动回复此视频消息。
会提示`该公众号提供的服务出现故障，请稍后再试`
图文和语音都可以，通过[微信公众平台接口调试工具](https://mp.weixin.qq.com/debug/cgi-bin/apiinfo?t=index&type=%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95&form=%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95%E5%88%9B%E5%BB%BA%E6%8E%A5%E5%8F%A3%20/menu/creat)调试也是正常的。
查看日志 `Server response created` 返回正常。

代码如下:
```php
public function handle($payload = null)
{
    try {
        $attributes = [
            'thumb_media_id' => $payload['ThumbMediaId'],
            'title' => 'title',
            'description' => 'description',
        ];
        $media = new Media($payload['MediaId'], 'mpvideo', $attributes);

        return $media;
    } catch (\Exception $e) {
        logger(__CLASS__ . '@' . __FUNCTION__ . ': ' . $e->getMessage() . ' at line ' . $e->getLine());
    }
}
```

**Comment by yadgen** [comment]
经测试，发现用户发送的视频并没有保存到临时素材。
通过[新增临时素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/New_temporary_materials.html)上传的临时素材，可以回复。
还发现一个问题，参数不支持mpvideo，使用video即可。

**Comment by overtrue** [comment]
@yadgen 

微信文档上明明写着 `video` 啊 https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html#3

**Comment by yadgen** [comment]
@overtrue 
官方文档写的是`mpvideo`。
属性设置`title`和`description `，未生效。
<img width="1497" alt="WX20210621-114503@2x" src="https://user-images.githubusercontent.com/1206012/122704375-2994cb80-d286-11eb-9c3f-8d3a2a8c5379.png">

**Comment by overtrue** [comment]
![image](https://user-images.githubusercontent.com/1472352/122705101-a1172a80-d287-11eb-907b-dc4a05cf65b8.png)
请认真阅读

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/overview
![image](https://user-images.githubusercontent.com/1472352/122705414-4205e580-d288-11eb-8218-e79411aa931a.png)

**Comment by yadgen** [comment]
@overtrue 
👍
