### ISSUE TITLE
支付回调异常不抛出信息??

### ISSUE THREAD

**Issue by jonny77** [w7corp/easywechat#2136]
protected function validate(array $message)
    {
        $sign = $message['sign'];
        unset($message['sign']);

        if (Support\generate_sign($message, $this->app->getKey()) !== $sign) {
            throw new InvalidSignException();
        }
    }

以上是库里面的源代码.故意将回调里面的sign改掉.
就算我在外面无论怎么try catch 都没结果. throw new InvalidSignException(); 里面写点字,比如sign error不就好了?

**Comment by TheNorthMemory** [comment]
- 不是`故意`，而是接口要求`sign`字典不参与签名
- `InvalidSignException` 这个字面量都已经告诉你是啥错了，`instanceof InvalidSignException` 一下可好？

**Comment by jonny77** [comment]
> * 不是`故意`，而是接口要求`sign`字典不参与签名
> * `InvalidSignException` 这个字面量都已经告诉你是啥错了，`instanceof InvalidSignException` 一下可好？

你理解错我的意思了. 我是在测试的时候,故意将sign字段更改.然后去捕获异常. 无奈捕获不到.  虽然我知道字面意思已经很名表了.但是我总不能让接口报500吧.所以要捕获到异常并返回给前端
我这样是没有效果的,
```php
$payApp->handlePaidNotify(function ($message, $fail) use ($event, $payApp) {
                try {


                }catch (InvalidSignException $exception){
                     
                }
            });

**Comment by TheNorthMemory** [comment]
https://github.com/w7corp/easywechat/blob/c5c0adcc9063d78f453da5cc7061fbddca197831/src/Payment/Notify/Handler.php#L186-L194

参考代码：

```php
<?php
namespace T {
	class InvalidArgumentException extends \Exception {}
}
namespace T\X {
	class InvalidSignException extends \Exception {}
}

namespace Notify {
	try {
		throw new \T\InvalidArgumentException();
		throw new \T\X\InvalidSignException();
	} catch (\T\InvalidArgumentException $e) {
		echo 1, PHP_EOL;
	} catch (\T\X\InvalidSignException $ep) {
		echo 2, PHP_EOL;
	} finally {
		echo 3, PHP_EOL;
	}
}
```

试试运行下，找找`catch`感觉

> > * 不是`故意`，而是接口要求`sign`字典不参与签名
> > * `InvalidSignException` 这个字面量都已经告诉你是啥错了，`instanceof InvalidSignException` 一下可好？
> 
> 你理解错我的意思了. 我是在测试的时候,故意将sign字段更改.然后去捕获异常. 无奈捕获不到. 虽然我知道字面意思已经很名表了.但是我总不能让接口报500吧.所以要捕获到异常并返回给前端
> 我这样是没有效果的,
> 
> ```
> $payApp->handlePaidNotify(function ($message, $fail) use ($event, $payApp) {
>                 try {
> 
> 
>                 }catch (InvalidSignException $exception){
>                      
>                 }
>             });
> ```

https://github.com/w7corp/easywechat/blob/c5c0adcc9063d78f453da5cc7061fbddca197831/src/Payment/Notify/Handler.php#L186-L194

参考代码：

```php
<?php
namespace T {
	class InvalidArgumentException extends \Exception {}
}
namespace T\X {
	class InvalidSignException extends \Exception {}
}

namespace Notify {
	try {
		throw new \T\InvalidArgumentException();
		throw new \T\X\InvalidSignException();
	} catch (\T\InvalidArgumentException $e) {
		echo 1, PHP_EOL;
	} catch (\T\X\InvalidSignException $ep) {
		echo 2, PHP_EOL;
	} finally {
		echo 3, PHP_EOL;
	}
}
```

试试运行下，找找`catch`感觉。

**Comment by overtrue** [comment]
> > * 不是`故意`，而是接口要求`sign`字典不参与签名
> > * `InvalidSignException` 这个字面量都已经告诉你是啥错了，`instanceof InvalidSignException` 一下可好？
> 
> 你理解错我的意思了. 我是在测试的时候,故意将sign字段更改.然后去捕获异常. 无奈捕获不到. 虽然我知道字面意思已经很名表了.但是我总不能让接口报500吧.所以要捕获到异常并返回给前端
> 我这样是没有效果的,
> 
> ```
> $payApp->handlePaidNotify(function ($message, $fail) use ($event, $payApp) {
>                 try {
> 
> 
>                 }catch (InvalidSignException $exception){
>                      
>                 }
>             });
> ```

贴你的文件头 use 部分，InvalidSignException use 了么？

**Comment by jonny77** [comment]
> > > * 不是`故意`，而是接口要求`sign`字典不参与签名
> > > * `InvalidSignException` 这个字面量都已经告诉你是啥错了，`instanceof InvalidSignException` 一下可好？
> > 
> > 
> > 你理解错我的意思了. 我是在测试的时候,故意将sign字段更改.然后去捕获异常. 无奈捕获不到. 虽然我知道字面意思已经很名表了.但是我总不能让接口报500吧.所以要捕获到异常并返回给前端
> > 我这样是没有效果的,
> > ```
> > $payApp->handlePaidNotify(function ($message, $fail) use ($event, $payApp) {
> >                 try {
> > 
> > 
> >                 }catch (InvalidSignException $exception){
> >                      
> >                 }
> >             });
> > ```
> 
> 贴你的文件头 use 部分，InvalidSignException use 了么？

use了啊


<?php
declare(strict_types=1);

namespace App\Listener\PayListener;

use App\Event\Pay\PayNotifyEvent;
use App\Model\Dao\OrderDao;
use App\Service\OrderService;
use EasyWeChat\Kernel\Exceptions\HttpException;
use EasyWeChat\Kernel\Support\XML;
use EasyWeChat\Payment\Kernel\Exceptions\InvalidSignException;

**Comment by overtrue** [comment]
1. 先确认 `EasyWeChat\Payment\Kernel\Exceptions\InvalidSignException` 是否有抛出；
2. 如果有抛出，则 catch 时使用正确的类名肯定就能抓得到。
