### ISSUE TITLE
弱弱的问一下. 缓存存到哪里去了

### ISSUE THREAD

**Issue by jonny77** [w7corp/easywechat#2137]
主项目用的是redis.我也没见access_token存入到redis

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/customize/cache

**Comment by Paladinhanxiao** [comment]
404了

> https://easywechat.com/docs/5.x/customize/cache

**Comment by Paladinhanxiao** [comment]
https://www.easywechat.com/5.x/customize/cache.html#%E4%BB%A5-redis-%E4%B8%BA%E4%BE%8B 应该是这个
