### ISSUE TITLE
关于access token 中央服务器

### ISSUE THREAD

**Issue by HarriesCC** [w7corp/easywechat#2144]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.0
* 是否使用了框架？框架名称：laravel

## 问题及现象

因为微信的限制 在获取Access Token的时候需要讲IP加入白名单，但是因为现在多台机器 而且滚动发布的时候IP会变，所以目前采用了一台中央服务器来管理所有的token 能否支持单独设置access token 而不是必须通过官方的API去获取token

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/customize/access_token

**Comment by HarriesCC** [comment]
```
$app = Factory::officialAccount([]);

$app->access_token->setToken("sdfsd", "");
```

这样写token确实是被更换了，但是不写app id和 secret的话 初始化过不去，如果写了app id的话就会报 IP不在白名单的错误，现在没法走到第二步

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/customize/replace-service 用这个方式拉

**Comment by HarriesCC** [comment]
感谢老哥极速回复

**Comment by overtrue** [comment]
😄

**Comment by HarriesCC** [comment]
resolved
