### ISSUE TITLE
微信公众号自定义菜单跳转网页授权（snsapi_base）报错，openid获取不了说api没授权,设置为snsapi_userinfo没问题

### ISSUE THREAD

**Issue by xpy2017** [w7corp/easywechat#2170]
## 我用的环境

* PHP 版本：php7.4
* overtrue/wechat 版本：5.5.4
* 是否使用了框架？框架名称：thinkphp6

## 问题及现象
网页授权snsapi_base方式获取的code 发送到后台获取open_id 为空，snsapi_userinfo方式获取的code发送到后台可以正常获取open_id

**Comment by wilbur-yu** [comment]
> ## 我用的环境
> * PHP 版本：php7.4
> * overtrue/wechat 版本：5.5.4
> * 是否使用了框架？框架名称：thinkphp6
> 
> ## 问题及现象
> 网页授权snsapi_base方式获取的code 发送到后台获取open_id 为空，snsapi_userinfo方式获取的code发送到后台可以正常获取open_id

解决了吗? 我也遇到了这个问题

**Comment by overtrue** [comment]
这个和 SDK 无关。
