### ISSUE TITLE
调用小程序内容安全，图片安全内容检测接口出现：resulted in a `412 Precondition Failed？请问这个问题是怎么处理的？

### ISSUE THREAD

**Issue by zhumanito** [w7corp/easywechat#2172]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

**Comment by overtrue** [comment]
用了 yield?

**Comment by zhumanito** [comment]
> 用了 yield?
用的是这个方法
 /**
     * 检测内容安全性（图片内容）
     */
    public function checkImage($image)
    {
        // 所传参数为要检测的图片文件的绝对路径，图片格式支持PNG、JPEG、JPG、GIF, 像素不超过 750 x 1334，同时文件大小以不超过 300K 为宜，否则可能报错
        $result = $this->app->content_security->checkImage($image);
        if($result['errcode'] == 87014)
        {
            $this->error('图片内容不合法！');
        } 
    }

**Comment by overtrue** [comment]
贴你的代码

**Comment by overtrue** [comment]
另外贴代码用 markdown 代码语法

**Comment by zhumanito** [comment]
> 另外贴代码用 markdown 代码语法



> 贴你的代码
文字检测是没有问题的，目前就图片检测有问题，难道这个和域名有关系吗？图片检测要绝对路径，目前用的域名是本地域名

 /**
     * 检测内容安全性（图片内容）
     */
    public function checkImage($image)
    {
        // 所传参数为要检测的图片文件的绝对路径，图片格式支持PNG、JPEG、JPG、GIF, 像素不超过 750 x 1334，同时文件大小以不超过 300K 为宜，否则可能报错
        $result = $this->app->content_security->checkImage($image);
        if($result['errcode'] == 87014)
        {
            $this->error('图片内容不合法！');
        } 
    }

**Comment by overtrue** [comment]
图片怎么传的？

**Comment by zhumanito** [comment]
> 图片怎么传的？

$this->checkImage('http://www.bottle.com/upload/images/8893797erfsdafdsfdsn88bn.png');

**Comment by overtrue** [comment]
麻烦认真阅读 “图片文件的绝对路径”  这几个字。”**路径**” 是 “/path/to/image.png” 这种才叫路径，你传的是 URL。

**Comment by zhumanito** [comment]
> 麻烦认真阅读 “图片文件的绝对路径” 这几个字。”**路径**” 是 “/path/to/image.png” 这种才叫路径，你传的是 URL。


问题解决了，多谢哦

**Comment by zhumanito** [comment]
问题已解决

**Comment by zhumanito** [comment]
问题已解决

**Comment by zhumanito** [comment]
问题已解决
