### ISSUE TITLE
6.0beta版测试企业微信开放平台API报错

### ISSUE THREAD

**Issue by ty-team** [w7corp/easywechat#2176]
## 我用的环境

* PHP 版本：8.0.2
* overtrue/wechat 版本：6.0.0.beta
* 是否使用了框架 否
* 框架名称：无

测试企业微信开放平台API报错
[error][EasyWeChat\Kernel\Exceptions\RuntimeException] EasyWeChat\Kernel\Exceptions\RuntimeException: EasyWeChat\OpenWork\Message not found. in ****\vendor\w7corp\easywechat\src\Kernel\Traits\InteractWithXmlMessage.php:33

**Comment by overtrue** [comment]
请更新到 beta.2
