### ISSUE TITLE
6.0.0.beta2体验企业微信开放平台API报错

### ISSUE THREAD

**Issue by ty-team** [w7corp/easywechat#2177]
## 我用的环境

* PHP 版本：8.0.2
* overtrue/wechat 版本：6.0.0
* 是否使用了框架？无
* 框架名称：无

刷新应用的ticket报错
[TypeError] TypeError: EasyWeChat\Kernel\Encryptor::decrypt(): Argument #4 ($timestamp) must be of type int, string given, called in vendor\w7corp\easywechat\src\Kernel\Message.php on line 77 and defined in vendor\w7corp\easywechat\src\Kernel\Encryptor.php:76
修复类型后报错：
[error][EasyWeChat\Kernel\Exceptions\RuntimeException] EasyWeChat\Kernel\Exceptions\RuntimeException: Invalid appId. in vendor\w7corp\easywechat\src\Kernel\Encryptor.php:95

**Comment by overtrue** [comment]
麻烦打码贴一下你的配置和代码

**Comment by ty-team** [comment]
> 麻烦打码贴一下你的配置和代码

<?php
$config = [
'corp_id' => '****',
        'provider_secret' => '***',
        'suite_id' => '***',
        'suite_secret' => '****-nIE',
        'token' => '***',
        'aes_key' => '***',
];
            $app = new Application($config);
            $server = $app->getServer();
            /*$server->handleSuiteTicketRefreshed(function ($message) {

            });*/

            return $server->serve();

**Comment by overtrue** [comment]
加我 Q 44294631
