### ISSUE TITLE
5.x版本配置log日记路径无效

### ISSUE THREAD

**Issue by diankemao** [w7corp/easywechat#2178]
5.x版本配置log日记路径无效

1、在Kernel\Log\LogManager.php修改为以下就可以：

    /**
     * Create an emergency log handler to avoid white screens of death.
     *
     * @return \Monolog\Logger
     *
     * @throws \Exception
     */
    protected function createEmergencyLogger()
    {
		$log = $this->app['config']->get('log');
		$path = \sys_get_temp_dir().'/easywechat/easywechat.log';
		if (isset($log['file']) && !empty($log['file'])) {
			$path = $log['file'];
		}
        return new Monolog('EasyWeChat', $this->prepareHandlers([new StreamHandler(
            $path,
            $this->level(['level' => 'debug'])
        )]));
    }

2、配置参数：
$config = [
    'corp_id' => 'xxxxxxxxxxxxxxxxx',

    'agent_id' => 100020, // 如果有 agend_id 则填写
    'secret'   => 'xxxxxxxxxx',

    // 指定 API 调用返回结果的类型：array(default)/collection/object/raw/自定义类名
    'response_type' => 'array',

    'log' => [
        'level' => 'debug',
        'file' => __DIR__.'/wechat.log',
    ],
];

**Comment by diankemao** [comment]
@overtrue @elim051 @bangbangda @moniang

**Comment by overtrue** [comment]
https://www.easywechat.com/docs/5.x/official-account/configuration

麻烦看清楚日志配置写法哦。

**Comment by diankemao** [comment]
> https://www.easywechat.com/docs/5.x/official-account/configuration
> 
> 麻烦看清楚日志配置写法哦。
感谢，已解决问题

**Comment by diankemao** [comment]
感谢，已解决问题
