### ISSUE TITLE
easywechat 公众号使用消息模板推送报错 Attribute "form_id" can not be empty!

### ISSUE THREAD

**Issue by ruanyihang** [w7corp/easywechat#2179]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.44
* 是否使用了框架？框架名称：thinkphp6

## 问题及现象

使用公众号模板消息推送后报错 Attribute "form_id" can not be empty!
![企业微信截图_1628565560526](https://user-images.githubusercontent.com/19322785/128803150-c22cda27-ff29-49ee-8193-6fb40cf0cb53.png)
代码如下
![image](https://user-images.githubusercontent.com/19322785/128803379-b3193fb8-5a5f-4749-98c7-ded8c875241b.png)

        $config = [
            'app_id' => '********',
            'secret' => '************',
            'response_type' => 'array',
            'log' => [
                'level' => 'debug',
                'file' => runtime_path().'/wechat.log',
            ],
            'http' => [
                'proxy'=>[
                    'http'  => '192.168.200.1:8889', // Use this proxy with "http"
                    'https'  => '192.168.200.1:8889'
                ]
            ]
        ];
        $app = Factory::miniProgram($config);
        $userId = '*********';
        $templateId = '***********';
        $url = '';
        $data = array(
            'first' => '测试用说明标题',
            'keyword1' => '测试报警时间2021-08-10 12:00:00',
            'keyword2' => '测试报警设备 海正岩头集中器1ph传感器',
            'keyword3' => '报警内容断线超过1个小时',
            'remark' => '测试异常详情说明。。。',
        );
        $result = $app->template_message->send([
            'touser' => $userId,
            'template_id' => $templateId,
            'url' => $url,
            'data' => $data,
        ]);

**Comment by elim051** [comment]
传参少了，看一下微信文档吧。 https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/template-message/templateMessage.send.html

**Comment by Anjaxs** [comment]
Factory::officialAccount($config);  兄弟你说的是公众号, 调用的应该是officialAccount 而不是miniProgram小程序
