### ISSUE TITLE
该公众号提供得服务出现故障

### ISSUE THREAD

**Issue by lxmwuchao1314** [w7corp/easywechat#2188]
## 我用的环境

* PHP 版本：7.3.4
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

## 问题及现象
回复用户消息时，出现该公众号提供的服务出现故障，截图如下：
![image](https://user-images.githubusercontent.com/45166702/130428181-f025478a-52a3-4d78-b698-aa2c3b6ebf54.png)
日志输出如下截图：
![image](https://user-images.githubusercontent.com/45166702/130428363-ed21ed97-5c79-458e-a3ba-783305bf4743.png)

**Comment by lxmwuchao1314** [comment]
忘了说了，使用了框架，thinkphp5.1.41 LTS版本

**Comment by teg1c** [comment]
捕获一下异常
```
 try {
            $response = $app->server->serve();
        } catch (\Throwable $e) {
            //打印日志看看是什么错误
        }
```
