### ISSUE TITLE
该公众号提供的服务出现故障

### ISSUE THREAD

**Issue by lxmwuchao1314** [w7corp/easywechat#2189]
## 我用的环境

* PHP 版本：7.3.4
* overtrue/wechat 版本：4.4.0
* 是否使用了框架？框架名称：thinkphp 5.1.4

## 问题及现象
验证通过了，发送消息提示“该公众号提供的服务出现故障”,
日志输出如下：
![image](https://user-images.githubusercontent.com/45166702/130540224-9ad727c7-8661-46cb-8937-850bb1a719f5.png)
代码如下：
![image](https://user-images.githubusercontent.com/45166702/130540638-3e0260c4-ebc9-468d-92b9-2ce16a589199.png)
调试输出如下：
![image](https://user-images.githubusercontent.com/45166702/130540690-387eff75-ee1b-42b2-be34-3bddc0762257.png)

**Comment by Endy-c** [comment]
先用明文或混合模式调试一下，可能是加解密的key没有设置正确导致。

**Comment by overtrue** [comment]
文档上貌似写了应该如何返回 $response 吧老哥？
![image](https://user-images.githubusercontent.com/1472352/131604268-dcf67c5a-9ca4-496b-9206-1e423f19498f.png)

```php
$app->server->send();exit;
```
