### ISSUE TITLE
官网 down 掉了，哪里找 API 帮助文档？

### ISSUE THREAD

**Issue by vodka0629** [w7corp/easywechat#2193]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：5.7
* 框架名称：Laravel 8

## 问题及现象

官网当掉了 https://www.easywechat.com/
在哪里找帮助文档？

```bash
curl -k --insecure https://www.easywechat.com/ -v
* About to connect() to www.easywechat.com port 443 (#0)
*   Trying 23.248.163.77...
* Connected to www.easywechat.com (23.248.163.77) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=www.easywechat.com
* 	start date: Jul 14 06:13:48 2021 GMT
* 	expire date: Oct 12 06:13:47 2021 GMT
* 	common name: www.easywechat.com
* 	issuer: CN=R3,O=Let's Encrypt,C=US
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.easywechat.com
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.18.0 (Ubuntu)
< Date: Sat, 28 Aug 2021 01:53:27 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 166
< Connection: keep-alive
< 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host www.easywechat.com left intact
```

**Comment by houguang** [comment]
> ## 我用的环境
> * PHP 版本：8.0
> * overtrue/wechat 版本：5.7
> * 框架名称：Laravel 8
> 
> ## 问题及现象
> 官网当掉了 https://www.easywechat.com/
> 在哪里找帮助文档？
> 
> ```shell
> curl -k --insecure https://www.easywechat.com/ -v
> * About to connect() to www.easywechat.com port 443 (#0)
> *   Trying 23.248.163.77...
> * Connected to www.easywechat.com (23.248.163.77) port 443 (#0)
> * Initializing NSS with certpath: sql:/etc/pki/nssdb
> * skipping SSL peer certificate verification
> * SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
> * Server certificate:
> * 	subject: CN=www.easywechat.com
> * 	start date: Jul 14 06:13:48 2021 GMT
> * 	expire date: Oct 12 06:13:47 2021 GMT
> * 	common name: www.easywechat.com
> * 	issuer: CN=R3,O=Let's Encrypt,C=US
> > GET / HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: www.easywechat.com
> > Accept: */*
> > 
> < HTTP/1.1 502 Bad Gateway
> < Server: nginx/1.18.0 (Ubuntu)
> < Date: Sat, 28 Aug 2021 01:53:27 GMT
> < Content-Type: text/html; charset=utf-8
> < Content-Length: 166
> < Connection: keep-alive
> < 
> <html>
> <head><title>502 Bad Gateway</title></head>
> <body>
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx/1.18.0 (Ubuntu)</center>
> </body>
> </html>
> * Connection #0 to host www.easywechat.com left intact
> ```
[EasyWeChat/docs](https://github.com/EasyWeChat/docs/tree/5.x)
