### ISSUE TITLE
官方文档 小程序使用 

### ISSUE THREAD

**Issue by puzzle9** [w7corp/easywechat#2199]
https://www.easywechat.com/6.x/mini-app/

![image](https://user-images.githubusercontent.com/13518196/132293534-61c407fc-d3f9-4e89-9b62-e2113d59f6e8.png)

应该是 `EasyWeChat\MiniApp\Application`

**Comment by overtrue** [comment]
感谢

**Comment by puzzle9** [comment]
> 感谢

莫非他真的错了 当时看到到那个 然后点进去看了下 继承的还是这个 我有过那么一会怀疑人生
