### ISSUE TITLE
企业微信发送文本卡片信息出现 No agentid specified.

### ISSUE THREAD

**Issue by lxmwuchao1314** [w7corp/easywechat#2206]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：5.x
* 是否使用了框架？框架名称：Thinkphp5.1.41 LTS

## 问题及现象

企业微信发送文本卡片信息出现 No agentid specified，只有在发送时调用ofAgent方法才不会出现这个错误。

![image](https://user-images.githubusercontent.com/45166702/133540083-1b78885f-e43e-4522-bb16-b8374a17f992.png)

![image](https://user-images.githubusercontent.com/45166702/133540104-63aa7cdc-857c-4e12-93a2-cae9bb9294fd.png)

**Comment by overtrue** [comment]
你配置的 agent_id 是错误的，agent_id 是数字，从企业微信后台拷贝，不是你随意写的。

**Comment by lxmwuchao1314** [comment]
安哥，我设置为数字还是出现这个错误呢，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 下午5:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [w7corp/easywechat] 企业微信发送文本卡片信息出现 No agentid specified. (#2206)





 
你配置的 agent_id 是错误的，agent_id 是数字，从企业微信后台拷贝，不是你随意写的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lxmwuchao1314** [comment]
设置成数字，还是会出现这个错误。

**Comment by lxmwuchao1314** [comment]
设置成数字还是会出现这个错误呢
