### ISSUE TITLE
PHP8.0.11错误

### ISSUE THREAD

**Issue by sunkaiyuan** [w7corp/easywechat#2218]
## 我用的环境

* PHP 版本：8.0.11
* overtrue/wechat 版本：5.7.3
* 是否使用了框架？框架名称：没有，自研框架

## 问题及现象
错误的等级 : 64
错误文件名 : vendor\overtrue\wechat\src\Kernel\Log\LogManager.php
错误所在行 : 457
错误信息 : Declaration of EasyWeChat\Kernel\Log\LogManager::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void
 
![image](https://user-images.githubusercontent.com/76044312/134856657-9949f5c7-a980-4626-bb1d-aa3d981c4795.png)

本来想装最新的6.X的，一看文档怎么没有发模板消息的啊

**Comment by overtrue** [comment]
6.x 不再封装具体业务接口，只封装必要的基础设施哈。

**Comment by sunkaiyuan** [comment]
可以修改下overtrue/wechat/src/Kernel/Log/LogManager.php 目录里面的 emergency，alert，critical，error，warning，notice，info，debug，log，函数么。

**Comment by sunkaiyuan** [comment]
public function debug(Stringable|string $message, array $context = []):void
    {
          $this->driver()->debug($message, $context);
    }
大概这个样子。Psr\Log\LoggerInterface 接口不返回了 。

**Comment by overtrue** [comment]
@sunkaiyuan 我本地没法复现你这个报错，我试试先复现

**Comment by sunkaiyuan** [comment]
$this->app->template_message->send  这个发送模板消息，触发的

**Comment by overtrue** [comment]
好

**Comment by overtrue** [comment]
@sunkaiyuan 升级下试试

**Comment by yakumo520** [comment]
大佬，是不是改出问题了，最新的代码说LogInterface有9个抽象方法，Logmanager继承了该接口，但是没有实现这9个方法

**Comment by overtrue** [comment]
> @overtrue
> 大佬，是不是改出问题了，最新的代码报错提示LogInterface有9个抽象方法，Logmanager继承了该接口，但是没有实现这9个方法
> 
> ![image](https://user-images.githubusercontent.com/11626304/134891349-7cb0f1cd-ade2-47b8-aba2-1c7478ea2f68.png)

擦，我的锅。。。
