### ISSUE TITLE
5.7.4在laravel8下的问题

### ISSUE THREAD

**Issue by yakumo520** [w7corp/easywechat#2219]
## 我用的环境

* PHP 版本：8.05
* overtrue/wechat 版本：5.7.4
* 是否使用了框架？框架名称：laravel

## 问题及现象

![image](https://user-images.githubusercontent.com/11626304/134892189-c2a23657-1ffc-480c-83ec-9c9763430733.png)

5.7.4在laravel8下报错，提示LogManager继承了LogInterface接口，但是没有实现LogInterface的9个方法，如上图所示

**Comment by overtrue** [comment]
确定你装的是5.7.4

**Comment by yakumo520** [comment]
> 确定你装的是5.7.4
非常确定哈,我的composer.json 
![image](https://user-images.githubusercontent.com/11626304/135012705-a7160152-715a-4ee6-bdcd-08727a3ff953.png)

报错如下

**Comment by overtrue** [comment]
已修复。。。 请升级到 5.7.5
