### ISSUE TITLE
可以收到Ticket 但是 缓存不成功 提示 Credential "component_verify_ticket" does not exist in cache. 

### ISSUE THREAD

**Issue by penglzy** [w7corp/easywechat#2224]
## 我用的环境
php版本7.4 
Laravel8.54
Laravel env 配置
BROADCAST_DRIVER=log
CACHE_DRIVER=redis
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

## 问题及现象

项目中能收到Ticket 但是不像文档上面说的会自己缓存在laravel的缓存里面  似乎use_laravel_cache' => true,这个选项似乎没用，自己用redis 存是可以的 但是  verify->setTicket($ticket) 设置的key: easywechat.open_platform.verify_ticket.wx2072b5d145e73a4a
 从代码里面应该是拿这个key对应的值可惜没有,不知道是不是bug

而且 EasyWeChat.EMERGENCY: Unable to create configured logger. Using emergency logger 提示log没有配置 但config/logging 已经配置了

![1633677975(1)](https://user-images.githubusercontent.com/16076894/136515522-9570254d-f606-4e15-a8bc-cde197b4b515.png)
![1633678024(1)](https://user-images.githubusercontent.com/16076894/136515656-eafa3f47-b535-4aee-988c-592231ce3e40.png)

**Comment by penglzy** [comment]
@overtrue

**Comment by overtrue** [comment]
无法复现
