### ISSUE TITLE
微信公众平台新增草稿箱和发布接口

### ISSUE THREAD

**Issue by willdoge** [w7corp/easywechat#2234]
## 我用的环境

* PHP 版本：7.1.30
* overtrue/wechat 版本：4.2.11
* 是否使用了框架？框架名称：lumen5.8.13

## 问题及现象

微信最近更新了草稿箱功能和相关接口，原图文素材相关接口预计在12月31日关闭

公告如下：

https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11632365691SkuD6&version=&lang=zh_CN&token=

麻烦需要跟进下这个目前灰度中的功能。

**Comment by elim051** [comment]
5.x版本代码已经提交，等发布tag即可使用了

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/5.12.0
