### ISSUE TITLE
4.4.2版本直播增加长期订阅相关接口

### ISSUE THREAD

**Issue by smile-magic** [w7corp/easywechat#2238]
## 我用的环境

* PHP 版本：7.3.31
* overtrue/wechat 版本：4.4.2
* 是否使用了框架？框架名称：YII

## 问题及现象

4.4.2 版本 望 增加下 直播->长期订阅相关接口

**Comment by overtrue** [comment]
4.x 已不再新增接口，你可以直接在该模块使用快捷方法调用对应的 API：

https://github.com/w7corp/easywechat/blob/0907070e17e4420c4ea73e6daac492ac74add9b9/src/Kernel/BaseClient.php#L66-L105

```php
$app->broadcasting->httpGet('API地址');
```
