### ISSUE TITLE
修改accesstoken问题

### ISSUE THREAD

**Issue by a6965921** [w7corp/easywechat#2245]
https://www.easywechat.com/4.x/customize/access_token.html#%E4%BF%AE%E6%94%B9-app-%E7%9A%84-access-token 
我按照如上文档操作
我随便设置了个accesstoken
`     $app    = Factory::officialAccount($config);
      
        $app['access_token']->setToken('21321');

        $tags = $app->user_tag->list();

        print_r($tags);`
        为什么还能输出 不报错？   修改了accesstoken没效果吗

**Comment by aa24615** [comment]
使用  $app->access_token->setToken('21321'); 试试
