### ISSUE TITLE
请教怎么在事件push里面回复文章类素材消息

### ISSUE THREAD

**Issue by hughcube** [w7corp/easywechat#2248]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：^5.0
* 是否使用了框架？框架名称：laravel

## 问题及现象
请教怎么在事件push里面回复文章类素材消息

**Comment by overtrue** [comment]
https://www.easywechat.com/5.x/official-account/messages.html#%E6%B6%88%E6%81%AF%E7%B1%BB%E5%9E%8B
