### ISSUE TITLE
调用微信客服相关api 返回 Identifier \"kf_account\" is not defined.

### ISSUE THREAD

**Issue by SuperPony** [w7corp/easywechat#2258]
## 我用的环境

* PHP 版本：7.4.2
* overtrue/wechat 版本：~5.0
* 是否使用了框架？框架名称：tp5.1

## 问题及现象

调用微信客服相关 api 返回 Identifier \"kf_account\" is not defined.
![code](https://user-images.githubusercontent.com/40234133/140849216-a3c05031-7f6b-423f-a590-bded0beadea3.png)

**Comment by overtrue** [comment]
看一下具体版本，或者升级到最新版：
```shell
$ composer info overtrue/wechat
```

**Comment by SuperPony** [comment]
> 看一下具体版本，或者升级到最新版：
> 
> ```shell
> $ composer info overtrue/wechat
> ```

可以了，原版本是5.7 多，升级到5.8 可以了。谢谢
