### ISSUE TITLE
企业微信获取客服链接的 url 现在与框架中的 url 不一致

### ISSUE THREAD

**Issue by SuperPony** [w7corp/easywechat#2260]
## 我用的环境

* PHP 版本：7.4.2
* overtrue/wechat 版本：5.8.0
* 是否使用了框架？框架名称：tp5.1

## 问题及现象

框架中多拼接了一个 /account/

![code1](https://user-images.githubusercontent.com/40234133/141217134-9355d4b9-21f2-4422-9acc-0e8dc4e0fe45.png)

![code2](https://user-images.githubusercontent.com/40234133/141217138-04377a07-fd6a-48cb-94c2-d5b5e7858448.jpg)

**Comment by overtrue** [comment]
@aa24615 你写的bug来啦

**Comment by aa24615** [comment]
@overtrue 大意了,我看他是同一目录的

**Comment by SuperPony** [comment]
> @aa24615 你写的bug来啦

你们在这开始搞相声了吗。。。。

**Comment by SuperPony** [comment]
> @aa24615 你写的bug来啦
预计什么时候能发布修复啊？

**Comment by aa24615** [comment]
@SuperPony 已经改了,要等待合并发版

**Comment by SuperPony** [comment]
> @SuperPony 已经改了,要等待合并发版

好的

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/5.8.1
