### ISSUE TITLE
3.x 有封装过小程序的订阅消息吗？

### ISSUE THREAD

**Issue by nbczw8750** [w7corp/easywechat#2262]
## 我用的环境

* PHP 版本： 5.6
* overtrue/wechat 版本： 3.3.34
* 是否使用了框架？框架名称： thinkphp5.1

## 问题及现象

3.x 有封装过小程序的订阅消息吗？
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html

**Comment by overtrue** [comment]
没有哈
