### ISSUE TITLE
企业微信服务商 suite_ticket 推送返回异常 

### ISSUE THREAD

**Issue by yilu-yj** [w7corp/easywechat#2264]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.0-beta5
* 是否使用了框架？框架名称：laravel

## 问题及现象

企业微信服务商 suite_ticket 推送返回异常 

原因：
EasyWeChat\Kernel\Traits\InteractWithXmlMessage::serve() 两次验证 msg_signature 
第二次验证 生成签名缺少 ciphertext 导致抛出错误 “Invalid request signature.”

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/6.0-beta6 用最新的试试
