### ISSUE TITLE
OpenWork\Application->suiteAccessToken cache driver不一致

### ISSUE THREAD

**Issue by yilu-yj** [w7corp/easywechat#2266]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.0-beta6
* 是否使用了框架？框架名称：

## 问题及现象
![image](https://user-images.githubusercontent.com/59158969/141940737-b5ab82a2-5b40-45f9-a678-85e009996f8c.png)

没有传入 cache driver

**Comment by overtrue** [comment]
感谢反馈，已发布 beta7。
