### ISSUE TITLE
这里的参数是不是有缺失？现在返回的结果与预期不符

### ISSUE THREAD

**Issue by hwbrzzl** [w7corp/easywechat#2271]
PHP 版本：7.2.28
overtrue/wechat 版本：5.0.9

https://github.com/w7corp/easywechat/blob/b15a91ac445fa843f30dbdc3484beacd5945894b/src/BasicService/ContentSecurity/Client.php#L42

[微信文档地址](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/sec-check/security.msgSecCheck.html)
![image](https://user-images.githubusercontent.com/24771476/143366471-f7dfad9e-983a-4e60-856f-a684507c6d3b.png)

**Comment by overtrue** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/security.msgSecCheck-v1.html 代码是按1.0写的，后来出 2.0 改了，欢迎 PR。

**Comment by hwbrzzl** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/framework/security.msgSecCheck-v1.html 代码是按1.0写的，后来出 2.0 改了，欢迎 PR。

好的，请问下列方案哪个更符合项目的规范？
1、另写 V2 方法，与 V1 并存；
2、改造现有方法，使之兼容 V1 与 V2；
3、改造现有方法，不再兼容V1；

**Comment by ranpro** [comment]
@hwbrzzl  https://github.com/w7corp/easywechat/pull/2333
