### ISSUE TITLE
企业微信获取访问用户信息时，会触发45009频率限制

### ISSUE THREAD

**Issue by xecrom** [w7corp/easywechat#2274]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.7

## 问题及现象

企业微信获取访问用户信息时，会触发45009频率限制，看源码发现每次都会重新获取access_token，需要手动调用$app->oauth->withApiAccessToken来绑定缓存的access_token

**Comment by overtrue** [comment]
麻烦提供更多的上下文信息，是哪个接口报的这个错误
