### ISSUE TITLE
Potentially polymorphic call.

### ISSUE THREAD

**Issue by jyxjjj** [w7corp/easywechat#2284]
## The environment i used:

* PHP version：8.0
* overtrue/wechat version：6.x
* Am i using framework？Framework Name：laravel

## Issue and appearance

The IDE reports:

> Potentially polymorphic call. The code may be inoperable depending on the actual class instance passed as the argument. 

When i use like this:
```
        $this->server->addEventListener('subscribe', function ($message, \Closure $next) use ($date) {
        });
        $this->server->addMessageListener('text', function ($message, \Closure $next) use ($date) {
        });
```

**Comment by jyxjjj** [comment]
Maybe i need submit this to easywechat docs instead of easywechat itself?

**Comment by jyxjjj** [comment]
When i track the code it shows
```
use EasyWeChat\Kernel\Contracts\Server as ServerInterface;
```
at
```
vendor/w7corp/easywechat/src/OfficialAccount/Application.php
```

Then i changed the use inside my own file:
From 
```
use EasyWeChat\Kernel\Contracts\Server
```
To
```
use EasyWeChat\OfficialAccount\Server;
```
Then i add
```
        /** @noinspection PhpFieldAssignmentTypeMismatchInspection */
```
before the line 
```
        $this->server = $this->app->getServer();
```
And
```
    /**
     * @throws InvalidArgumentException
     * @throws Throwable
     * @throws BadRequestException
     * @throws RuntimeException
     */
```
before the method which includes
```
        $this->server->addEventListener('subscribe', function ($message, \Closure $next) use ($date) {
        });
        $this->server->addMessageListener('text', function ($message, \Closure $next) use ($date) {
        });
```

It is solved.

**Comment by jyxjjj** [comment]
The same with 'with' too.:
```
Method 'with' not found in \EasyWeChat\Kernel\Contracts\Server 
```

**Comment by overtrue** [comment]
抱歉这么久才回复，这里确实会出现这种提示，因为在设计的时候考虑到开发者的自定义需求，在接口层仅做了最低可用性要求，比如 Server 仅仅 要求一个方法就是 `serve()`，但是文档是根据 SDK 默认提供的类来写的，所以在 SDK 内置的 Server 类里有 `with` 这些增强的方法。

**Comment by jyxjjj** [comment]
That doesn't matter, what matters is that my solution was not "elegant". Hope to resolve from your library.
