### ISSUE TITLE
小程序根据code获取手机号，找不到phone_number

### ISSUE THREAD

**Issue by mingliangge** [w7corp/easywechat#2305]
## 我用的环境

* PHP 版本：74
* overtrue/wechat 版本：5.10.3
* 是否使用了框架？框架名称：否

## 问题及现象
发现github上有小程序获取手机号的代码
![image](https://user-images.githubusercontent.com/51039043/146562261-a189db33-038e-476d-b2e9-703136b522cd.png)

但是composer下来的包并没有这个目录
![image](https://user-images.githubusercontent.com/51039043/146562431-d8692db4-4354-47d9-bfe8-01823f1271dd.png)

执行下面的时候，说找不到这个 phone_number 变量
`$app->phone_number->getUserPhoneNumber(string $code);`

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/5.11.0
