### ISSUE TITLE
官网打不开了？

### ISSUE THREAD

**Issue by chaituan** [w7corp/easywechat#2311]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

## 问题及现象

请问你们可以打开吗？  看不了文档了....

**Comment by overtrue** [comment]
官网域名备案中，临时域名：https://easywechat.vercel.app

**Comment by reader0421** [comment]
要不要官网源码也放在github上保险一点，好几次打不开了
