### ISSUE TITLE
官网无法访问啊？？？

### ISSUE THREAD

**Issue by garenlyu** [w7corp/easywechat#2313]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

**Comment by reader0421** [comment]
同问

**Comment by penndev** [comment]
dns 解析为 空，应该是域名出现了问题。

**Comment by penndev** [comment]
配置hosts        76.76.21.21 www.easywechat.com            可以解决问题。希望官方赶紧看下域名怎么回事。

**Comment by overtrue** [comment]
官网域名备案中，临时域名： https://easywechat.vercel.app/

Penn ***@***.***>于2021年12月22日 周三下午5:40写道：

**Comment by overtrue** [comment]
官网域名备案中，临时域名：https://easywechat.vercel.app/

**Comment by woldy** [comment]
> 官网域名备案中，临时域名：�[https://easywechat.vercel.app/�](https://easywechat.vercel.app/%02)

吓死我了

**Comment by overtrue** [comment]
备案已通过
