### ISSUE TITLE
官网备案中，暂时无法访问

### ISSUE THREAD

**Issue by overtrue** [w7corp/easywechat#2314]
官网域名备案中，暂停解析，临时域名

https://easywechat.vercel.app

**Comment by mofashi998** [comment]
临时域名无法访问

**Comment by overtrue** [comment]
@mofashi998 这可能是你网络问题了，目前只有你反馈无法访问

**Comment by mofashi998** [comment]
> @mofashi998这可能是你网络问题了，目前只有你反馈无法访问

挂VPN可以访问。

**Comment by overtrue** [comment]
备案已通过
