### ISSUE TITLE
6.0版本 替换guzz客户端疑问?

### ISSUE THREAD

**Issue by tw2066** [w7corp/easywechat#2328]
## 我用的环境

* PHP 版本：8.0.12
* overtrue/wechat 版本：6.0-beta10
* 是否使用了框架？框架名称：hyperf
* 环境 swoole 4.8.1

## 问题及现象

* 因为6.0没有使用guzz, 无法setHttpClient
* 直接运行
```
        $config = [
            'app_id' => 'wx3cf0f39249eb0exx',
            'secret' => 'f1c242f4f28f735d4687abb469072axx',
            'token' => 'easywechat',
            'aes_key' => '' // 明文模式请勿填写 EncodingAESKey
            //...
        ];

        $app = new Application($config);
        $app->getAccessToken()->getToken();
```
 默认会使用 `Symfony\Component\HttpClient\CurlHttpClient`

报错信息
```
TypeError: Symfony\Component\HttpClient\Response\CurlResponse::__construct(): Argument #2 ($ch) must be of type CurlHandle|string, Swoole\Coroutine\Curl\Handle given, called in /Users/t/WWW/php-service/vendor/symfony/http-client/CurlHttpClient.php on line 295(0) in /Users/t/WWW/php-service/vendor/symfony/http-client/Response/CurlResponse.php:46
Stack trace:
#0 /Users/t/WWW/php-service/vendor/symfony/http-client/CurlHttpClient.php(295): Symfony\Component\HttpClient\Response\CurlResponse->__construct(Object(Symfony\Component\HttpClient\Internal\CurlClientState), Object(Swoole\Coroutine\Curl\Handle), Array, NULL, 'GET', Object(Closure), 478977)
#1 /Users/t/WWW/php-service/vendor/overtrue/wechat/src/OfficialAccount/AccessToken.php(66): Symfony\Component\HttpClient\CurlHttpClient->request('GET', 'https://api.wei...', Array)
#2 /Users/t/WWW/php-service/runtime/container/proxy/App_Controller_WeChatController.proxy.php(55): EasyWeChat\OfficialAccount\AccessToken->getToken()
```

* \EasyWeChat\Kernel\Traits\InteractWithHttpClient::setHttpClient 是否可以兼容 Psr\Http\Client\ClientInterface

**Comment by overtrue** [comment]
暂时没有考虑支持，当然欢迎 PR。

**Comment by tw2066** [comment]
是否考虑直接使用 guzzle客户端?

`overtrue/socialite`包也是使用的guzzle客户端

**Comment by overtrue** [comment]
不考虑哈，前期调研过的

**Comment by awen1988** [comment]
easywechat有几乎100%的自定义能力，实际上因该可以通过替换client来解决这个问题，关于报错，我也遇到了经过测试，最新的swoole4.8版本都存在，但是升级swoole5.0.0-dev即可解决报错问题，成功代码如下：
`public function initApplication(PlatformModel $platformModel)
    {
        // 实例化应用
        $application = make(Application::class, [[
            'app_id' => $platformModel->app_id,
            'secret' => $platformModel->app_secret,
            'token' => $platformModel->app_token,
            'aes_key' => $platformModel->app_key
        ]]);

        // region 替换请求 +++++
        $request = ApplicationContext::getContainer()->get(RequestInterface::class);
        $application->setRequest($request);
        // endregion

        // region 替换缓存 +++++
        $cache = ApplicationContext::getContainer()->get(CacheInterface::class);
        $application->setCache($cache);
        // endregion

        return $application;
    }`
