### ISSUE TITLE
小微商户提交入驻的时候加密报错

### ISSUE THREAD

**Issue by chaituan** [w7corp/easywechat#2334]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.x
* 是否使用了框架？框架名称：CI

## 问题及现象

使用小微商户入驻接口，提示Encryption of sensitive information failed

检查发现openssl_public_encrypt 使用OPENSSL_NO_PADDING 返回的都是false

百度了一下说长度不够，加到128位也还是返回false。

请教一下这个如何解决？

**Comment by TheNorthMemory** [comment]
小微商户的敏感信息加密是 `OPENSSL_PKCS1_PADDING` 填充模式
