### ISSUE TITLE
企业微信三方，验证 corpid 无效

### ISSUE THREAD

**Issue by Deepseath** [w7corp/easywechat#2345]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.0-beta11
* 是否使用了框架？框架名称：tp6

## 问题及现象

刚开始用 easywechat。
新注册了企业微信进行企业微信三方开发调试，发现接收“应用管理员变更通知”的回调始终验证不通过，提示：“Invalid appId.”，看代码后发现是：src/Kernel/Encryptor.php 第 108 行，不通过

      if (trim(substr($plaintext, $contentLength + 4)) !== $this->appId) {
            throw new RuntimeException('Invalid appId.', self::ERROR_INVALID_APP_ID);
      }

看了代码，似乎是验证请求的是授权应用的企业微信 corpid 与应用的 suiteid 是否相同？一来这两个的 id 应该不是一个吧？二来现在企业微信返回的 corpid 并不是明文，而是每家服务商都不一样的值。

暂时我是把这段代码注释掉来用的。希望帮忙看看我理解的是否有问题。

**Comment by overtrue** [comment]
在企业微信场景下，确实在不同场景，这里的 4 字节内容代表的内容不一样：

> https://developer.work.weixin.qq.com/document/path/95373#%E5%AF%86%E6%96%87%E8%A7%A3%E5%AF%86%E5%BE%97%E5%88%B0msg%E7%9A%84%E8%BF%87%E7%A8%8B

关于你提到两个 ID 不是同一个，目前框架确实没错的，可参考：https://github.com/w7corp/easywechat/blob/master/src/OpenWork/Application.php#L82-L93

问题出在现在 “企业微信返回的 corpid 并不是明文” 这个后来他们的变更上，我来看看怎么处理它。

**Comment by Deepseath** [comment]
谢谢！！！大牛！！！

**Comment by davidtall** [comment]
5.0版本遇到同样的问题，请问5.0是不再修复这个问题了吗？
