### ISSUE TITLE
查询订单请求400

### ISSUE THREAD

**Issue by wolf-leo** [w7corp/easywechat#2350]
## 我用的环境

* PHP 版本：8.1.1
* overtrue/wechat 版本：6.0.16
* 是否使用了框架？框架名称：webman

## 问题及现象

`        
        $order_no='vip164307407412500220126LScwXpkI';

        $app      = $this->app;
        $data     = ['mchid' => (string)$app->getMerchant()->getMerchantId(),];
        $response = $app->getClient()->get("pay/transactions/out-trade-no/{$order_no}", [
            'query' => $data,
        ]);`

返回信息：

`Symfony\Component\HttpClient\Exception\ClientException: HTTP/1.1 400 Bad Request returned for "https://api.mch.weixin.qq.com/v3/pay/transactions/out-trade-no/vip164307407412500220126-l-scw-xpk-i?mchid=xxx".`

**Comment by overtrue** [comment]
@wolf-leo 麻烦检查最新的版本是否存在这个问题，看起来是之前的链式转换导致订单号错误，请使用最新的语法：

```php
    $order_no='vip164307407412500220126LScwXpkI';

    $response = $this->app->getClient()->get("v3/pay/transactions/out-trade-no/{$order_no}", [
        'query' => ['mchid' => (string)$app->getMerchant()->getMerchantId(),],
    ]);`
```
