### ISSUE TITLE
什么时候兼容laravel9

### ISSUE THREAD

**Issue by chen900804** [w7corp/easywechat#2363]
## 我用的环境

* PHP 版本：8
* overtrue/wechat 版本：最新版
* 是否使用了框架？框架名称 laravel9：

## 问题及现象

不兼容，无法通过compoer 在laravel9中安装

**Comment by overtrue** [comment]
贴错误

**Comment by zbage** [comment]
overtrue/laravel-wechat 能兼容laravel9 吗？

**Comment by overtrue** [comment]
@zbage 已经支持

**Comment by chen900804** [comment]
@overtrue  psr/simple-cache 这个不能匹配laravel9

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/wechat[5.16.0, ..., 5.x-dev] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires overtrue/wechat ^5.16 -> satisfiable by overtrue/wechat[5.16.0, 5.16.2, 5.16.3, 5.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require overtrue/wechat:*" to figure out if any version is installable, or "composer require overtrue/wechat:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`
