### ISSUE TITLE
使用overture/wechat 获取签名错误

### ISSUE THREAD

**Issue by feng505668236** [w7corp/easywechat#2369]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：4.5
* 是否使用了框架？框架名称：webman

## 问题及现象

###在统一下单JSAPI支付时，获取到的签名有问题

打印request签名参数：
```<xml>
<mch_id>1620652088</mch_id>
<nonce_str><![CDATA[620ca4163d2b4]]></nonce_str>
<body><![CDATA[音鳗钻石充值]]></body>
<out_trade_no><![CDATA[CZ1644995606212287166]]></out_trade_no>
<toe>600</total_fee>
<trade_type><![CDATA[JSAPI]]></trade_type>
<openid><![CDATA[osjES5-4TkM5lwBWN8ieuJ7qDEAU]]></openid>
<spbill_create_ip><![CDATA[192.168.1.110]]></spbill_create_ip>
<appid><![CDATA[wx026f58752b7377d3]]></appid>
<notify_url><![CDATA[http://app.test.talklife.cn/notify/wxpay]]></notify_url>
<sign><![CDATA[5FDE666EA1CB1C5A09BAFAB244557752]]></sign>
</xml>```

<toe>600</total_fee>,为什么是这样

**Comment by overtrue** [comment]
这就不清楚了，代码里没有修改这个玩意儿的地方哈。

**Comment by ruikc** [comment]
> ## 我用的环境
> * PHP 版本：7.4
> * overtrue/wechat 版本：4.5
> * 是否使用了框架？框架名称：webman
> 
> ## 问题及现象
> ###在统一下单JSAPI支付时，获取到的签名有问题
> 
> 打印request签名参数：
> 
> ```
> <mch_id>1620652088</mch_id>
> <nonce_str><![CDATA[620ca4163d2b4]]></nonce_str>
> <body><![CDATA[音鳗钻石充值]]></body>
> <out_trade_no><![CDATA[CZ1644995606212287166]]></out_trade_no>
> <toe>600</total_fee>
> <trade_type><![CDATA[JSAPI]]></trade_type>
> <openid><![CDATA[osjES5-4TkM5lwBWN8ieuJ7qDEAU]]></openid>
> <spbill_create_ip><![CDATA[192.168.1.110]]></spbill_create_ip>
> <appid><![CDATA[wx026f58752b7377d3]]></appid>
> <notify_url><![CDATA[http://app.test.talklife.cn/notify/wxpay]]></notify_url>
> <sign><![CDATA[5FDE666EA1CB1C5A09BAFAB244557752]]></sign>
> </xml>```
> 
> <toe>600</total_fee>,为什么是这样
> ```

你查一下用的是微信支付的哪个版本，v3版本的签名算法调整了，微信支付最新的文档是基于v3的，overtrue/wechat 版本4的程序是基于v2的，我之前费了好长时间才找到这个问题。
