### ISSUE TITLE
6.0 小程序消息 xml 解析错误

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2370]
## 我用的环境

* PHP 版本：8.0.6
* overtrue/wechat 版本：6.0-beta17
* 是否使用了框架？框架名称：Laravel 9.0

## 问题及现象

````
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found

simplexml_load_string(self::sanitize($xml), 'SimpleXMLElement', LIBXML_COMPACT | LIBXML_NOCDATA | LIBXML_NOBLANKS)
````

**Comment by overtrue** [comment]
打印一下`self::sanitize($xml)`

**Comment by TheNorthMemory** [comment]
> 打印一下`self::sanitize($xml)`

`Start tag expected, '&lt;' not found` 这明显是被CSRF给拦截转译了嘛。。。

**Comment by hihuangwei** [comment]
{
"ToUserName": "gh_bb7bff7fd6bd",
"FromUserName": "o26Qh0RJrGOQkJ6yqEKRUIdaF0Oo",
"CreateTime": 1646222724,
"MsgType": "text",
"Content": "666",
"MsgId": 23568243490745350
}

这是 json 格式，应该是格式识别错误导致的

**Comment by hihuangwei** [comment]
![微信截图_20220302201125](https://user-images.githubusercontent.com/3166799/156359349-0fa64638-b9b5-4f6b-83f8-c5cd92ff0187.png)
改为 xml 格式就可以了
