### ISSUE TITLE
5.x以下版本想用 MiniProgram/PhoneNumber 怎么办呢

### ISSUE THREAD

**Issue by hkui** [w7corp/easywechat#2372]
## 我用的环境

* PHP 版本：5.5
* overtrue/wechat 版本：3.6
* 是否使用了框架？框架名称：

## 问题及现象
我这个版本的想用获取手机号的怎么弄呢

**Comment by hkui** [comment]
> 要么升级，要么自己写吧

把5.x的MiniProgram/PhoneNumber 这个文件夹 直接复制进去改改 也不知道能用不，但下次升级就麻烦了估计

**Comment by overtrue** [comment]
应该不行哈，这个无解，版本差异太大。
