### ISSUE TITLE
能否适配一下php8.1.x 感谢

### ISSUE THREAD

**Issue by wordgege** [w7corp/easywechat#2384]
## 我用的环境

* PHP 版本：php8.1.3
* overtrue/wechat 版本：5.18.0
* 是否使用了框架？框架名称：webman

## 问题及现象
应该是/overtrue/socialite 这个没有适配php8.1.x

**Comment by wordgege** [comment]
![image](https://user-images.githubusercontent.com/29681588/156619562-de1c90e5-2fca-436d-9ca5-05fc9a4009a0.png)

**Comment by overtrue** [comment]
```bash
composer require overtrue/socialite:^3.5.1
```

**Comment by wordgege** [comment]
> ```shell
> composer require overtrue/socialite:^3.5.1
> ```

感谢
