### ISSUE TITLE
access_token 过期无法自动刷新

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2386]
## 我用的环境

* PHP 版本：8.0.6
* overtrue/wechat 版本：6.0
* 是否使用了框架？框架名称：Laravel 9.0

## 问题及现象

{
"errcode": 40001,
"errmsg": "invalid credential, access_token is invalid or not latest rid: 62247d33-0c0fb15c-7a1ed862"
}

access_token 过期无法自动刷新

**Comment by LeePillar** [comment]
仔细看看帮助文档上有~
