### ISSUE TITLE
添加 Response 装饰器

### ISSUE THREAD

**Issue by overtrue** [w7corp/easywechat#2393]
- 增加 `$response->toArray()`  xml 支持 
- 增加 `$response->toJson()` 
- 实现 ArrayAccess

**Comment by JimChenWYU** [comment]
超哥，review了下
https://github.com/w7corp/easywechat/blob/6.x/src/Kernel/HttpClient/Response.php#L60
这里是不是写错了，按照offsetExists定义只需要判断键值是否存在，应该是
```php
public function offsetExists(mixed $offset): bool
{
        return array_key_exists($offset, $this->toArray());
}
```

**Comment by overtrue** [comment]
@JimChenWYU 是的，我图省事复制粘贴了代码，但是为啥我本地的 phpstan 没报问题。。。感谢，我去检查并修复它。

**Comment by overtrue** [comment]
@JimChenWYU 修复啦，鼠标把告警级别跳到9级了
