### ISSUE TITLE
发送代理请求时是否可以自定义headers

### ISSUE THREAD

**Issue by yaqianghan** [w7corp/easywechat#2404]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat  #版本：~4.0
* 是否使用了框架？框架名称：laravel

## 问题及现象

    **/**
     * POST request.
     *
     * @param string $url
     * @param array  $data
     *
     * @return \Psr\Http\Message\ResponseInterface|\EasyWeChat\Kernel\Support\Collection|array|object|string
     *
     * @throws \EasyWeChat\Kernel\Exceptions\InvalidConfigException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function httpPost(string $url, array $data = [])
    {
        return $this->request($url, 'POST', ['form_params' => $data]);
    }
**

这一块是可以自定义headers 吗？

**Comment by overtrue** [comment]
你可以调用 `request` 方法，自定义信息

**Comment by overtrue** [comment]
或者全局配置，参考文档

**Comment by yaqianghan** [comment]
好的已经解决了，谢谢。不过自定义Host 会不生效
