### ISSUE TITLE
6.x-dev(2ee8964) $client->postJson() 不存在

### ISSUE THREAD

**Issue by jiangslee** [w7corp/easywechat#2424]
## 我用的环境

* PHP 版本：8.0.16
* overtrue/wechat 版本：6.x-dev(2ee8964)
* 是否使用了框架？框架名称：laravel 9.3.1

## 问题及现象
![image](https://user-images.githubusercontent.com/27892476/160526121-39806444-eb9b-45d6-8fa1-591a020cd122.png)
![image](https://user-images.githubusercontent.com/27892476/160526129-fc67f765-3ba9-419f-9fb4-29a06128bac8.png)
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/27892476/160526368-8ef4712f-49a6-4ac3-97a9-0cc85d705a33.png">

```
Call to undefined method Symfony\Component\HttpClient\CurlHttpClient::postJson()
```

$client->postJson() 不存在。

**Comment by sy-records** [comment]
getClient 获取到应该是`EasyWeChat\Kernel\HttpClient\AccessTokenAwareClient`

**Comment by jiangslee** [comment]
composer缓存问题。。
