### ISSUE TITLE
6.x 希望开放平台代调用内部处理authorizer_access_token

### ISSUE THREAD

**Issue by jiangslee** [w7corp/easywechat#2427]
## 我用的环境

* PHP 版本：8.0.16
* overtrue/wechat 版本：6.x-dev(937cac9)
* 是否使用了框架？框架名称：laravel 9.3.1

## 问题及现象
```php
use EasyWeChat\OpenPlatform\AuthorizerAccessToken;

$authorizerAppId = '授权的appid';
$authorizerRefreshToken = '授权后在缓存或数据库获取';

// *********以下是授权token及更新token后缓存的伪逻辑************
$token = cache()->get('xxxxx');
if(!token){
    $token = $app->refreshAuthorizerToken($authorizerAppId, $authorizerRefreshToken);
    // 开发者自行缓存 token伪代码。。。
    cache()->set('xxxxx', $token, 7200);
}
$authorizerAccessToken = new AuthorizerAccessToken($authorizerAppId, $token);
$officialAccount = $app->getOfficialAccount($authorizerAccessToken);
// ****************************************************************

// 调用公众号接口
$response = $officialAccount->getClient()->get('cgi-bin/users/list');
```

6.x 开放平台代调用时需要开发者自行处理authorizerAccessToken的请求及缓存，
框架是否考虑和5.x一样封装这部分的逻辑？
![image](https://user-images.githubusercontent.com/27892476/160573009-19361474-b234-4660-8757-e9cfbfb0611d.png)

这样开发者只需传入已授权的appid，就可以直接代调用了

例如：
```php
$app->officialAccount($appid)->getClient()->get('cgi-bin/users/list');

$app->miniApp($appid)->getClient()->get('cgi-bin/users/list');
```

抄得不好没PR，大概是这么个意思：
https://github.com/w7corp/easywechat/compare/6.x...jiangslee:6.x-openplatform-getXXXClient

**Comment by aa24615** [comment]
nb

**Comment by aa24615** [comment]
传 appid 与 refreshToken 完全ok 第三个参也可以直接传入 authorizerAccessToken

**Comment by overtrue** [comment]
https://www.easywechat.com/6.x/open-platform/index.html#%E4%BB%A3%E6%9B%BF%E5%85%AC%E4%BC%97%E5%8F%B7-%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%AF%B7%E6%B1%82-api
