### ISSUE TITLE
6.x微信支付v2不支持with这个方法?

### ISSUE THREAD

**Issue by LeePillar** [w7corp/easywechat#2439]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：
* 是否使用了框架？框架名称：

## 问题及现象

微信支付v2不支持with这个方法?支付通知结果接受不到。

**Comment by overtrue** [comment]
6.x 不打算支持 V2 回调了，可以自行读取请求信息处理完返回对应的内容即可，SDK  内置了 Xml 工具类，不会很麻烦。
