### ISSUE TITLE
开放平台，当componentAccessToken意外失效后，微信端component_verify_ticket推送，并不能使componentAccessToken恢复正常使用，需等待2小时或手动删除componentAccessToken缓存才能使用

### ISSUE THREAD

**Issue by DoctorWei** [w7corp/easywechat#2441]
## 我用的环境

* PHP 版本：8
* overtrue/wechat 版本：6
* 是否使用了框架？框架名称：Laravel8

## 问题及现象
开放平台，当componentAccessToken意外失效后，微信端component_verify_ticket推送，并不能使componentAccessToken恢复正常使用，需等待2小时或手动删除componentAccessToken缓存才能使用
```
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest rid: *************"}
```
希望每次接收到component_verify_ticket推送时，或API请求判断40001，自动更新componentAccessToken

**Comment by LeePillar** [comment]
没发现这个问题~~~稳定跑了好几天。正常

**Comment by DoctorWei** [comment]
你试下在其他地方（本地调试）获取componentAccessToken，制造意外，过一会你再看线上的业务是否正常

**Comment by overtrue** [comment]
> 你试下在其他地方（本地调试）获取componentAccessToken，制造意外，过一会你再看线上的业务是否正常

这种多推送地址，请自行setComponentAccessToken

**Comment by jiangslee** [comment]
> > 你试下在其他地方（本地调试）获取componentAccessToken，制造意外，过一会你再看线上的业务是否正常
> 
> 这种多推送地址，请自行setComponentAccessToken

开放平台好像没有多推送地址设置， @DoctorWei 你本地调试的verifyTicket是从线上CV下来再获取componentAccessToken的吗？
