### ISSUE TITLE
简化上传附件传参

### ISSUE THREAD

**Issue by jiangslee** [w7corp/easywechat#2445]
## 我用的环境

* PHP 版本：8.0.16
* overtrue/wechat 版本：6.x-dev(a878acf6)
* 是否使用了框架？框架名称：laravel v9.3.1

## 需求：

@overtrue 大佬发了一贴 https://github.com/w7corp/easywechat/issues/2444 ，所以提个需求给大佬肝肝。

Before: Form+Array+File，不够easy
```php
        // $qrcode 为已请求的临时二维码

        $options = Form::create(
            [
                'media' => File::withContents($qrcode, "qrcode_$time.png"),
            ]
        );

        $media = $client->post('cgi-bin/media/upload?type=image', $options->toArray());
```

期望: 参考#2444，类似with一把梭

```php
        // $qrcode 为请求的临时二维码
        $media = $client->withFile($qrcode)->post('cgi-bin/media/upload?type=image');
```

**Comment by jiangslee** [comment]
最好一个with自动识别是file还是content

**Comment by jiangslee** [comment]
> ```
> // withFile(string $localPath, string $formName)
> $media = $client->withFile($path, 'media')->post('cgi-bin/media/upload?type=image');
> 
> // withFileContents(string $contents, string $formName, string $filename = null)
> $media = $client->withFileContents($qrcode, 'media', 'filename.png')->post('cgi-bin/media/upload?type=image');
> ```

那个filename.png不可以默认值吗？

**Comment by overtrue** [comment]
> > ```
> > // withFile(string $localPath, string $formName)
> > $media = $client->withFile($path, 'media')->post('cgi-bin/media/upload?type=image');
> > 
> > // withFileContents(string $contents, string $formName, string $filename = null)
> > $media = $client->withFileContents($qrcode, 'media', 'filename.png')->post('cgi-bin/media/upload?type=image');
> > ```
> 
> 那个filename.png不可以默认值吗？

看上面注释部分，有默认值 null，你可以不传

**Comment by overtrue** [comment]
```php
$client->withFiles([
    'name1' => $path1,
    'name2' => $path2,
])
```

这样？

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/commit/889bb4a8e808ea1fcc2b49dfd47b1156bd5b94b8

**Comment by overtrue** [comment]
#2444
