### ISSUE TITLE
阿里云镜像安装6.3版本 composer require w7corp/easywechat 6.3

### ISSUE THREAD

**Issue by DoctorWei** [w7corp/easywechat#2458]
## 我用的环境

* PHP 版本：8
* overtrue/wechat 版本：6
* 框架名称：laravel8.7
* composer 版本：2.3.5
## 问题及现象
**无法安装指定版本**

composer require w7corp/easywechat 6.3
./composer.json has been updated
Running composer update w7corp/easywechat
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires w7corp/easywechat 6.3, found w7corp/easywechat[1.0, 1.0.1, 1.x-dev, 2.0.0, ..., 2.x-dev, 3.0, ..., 3.x-dev, 4.0.0-alpha1, ..., 4.x-dev, 5.0.0, ..., 5.x-dev, 6.0-beta1, ..., 6.x-dev] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by overtrue** [comment]
这是阿里云的问题
