### ISSUE TITLE
8.1 专有函数 array_is_list() 导致：Call to undefined function 错误

### ISSUE THREAD

**Issue by iFreeshine** [w7corp/easywechat#2468]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.5
* 是否使用了框架？框架名称：CI4

## 问题及现象
EasyWeChat\Pay\Merchant->normalizePlatformCerts() 调用了 8.1 专有函数 array_is_list() 导致：Call to undefined function 错误

**Comment by overtrue** [comment]
怎么安装的啊？ `composer dump` 一下？

**Comment by iFreeshine** [comment]
> 怎么安装的啊？ `composer dump` 一下？

composer 源的问题，阿里的源一大堆问题
