### ISSUE TITLE
EasyWeChat\Work\Account::__construct(): Argument #3 ($token) must be of type string, null given

### ISSUE THREAD

**Issue by JoeZing** [w7corp/easywechat#2483]
## 我用的环境

* PHP 版本：8.1.4
* overtrue/wechat 版本：6.0.0
* 是否使用了框架？框架名称：Laravel

## 问题及现象
实例化App后报错，看了源码，获取account时，要求传入corp_id，secret，token，aes_key，但我调用的是企信打卡应用，没有token和aes_key，
也尝试传入空值，但$app->config->get()方法传空会返回默认值null， new Account() 入参类型又必须是string，所以类型报错；

```
TypeError
EasyWeChat\Work\Account::__construct(): Argument #3 ($token) must be of type string, null given
```

## 问题代码
```
$app = new Application([
            'corp_id' => 'id',
            'secret'  => 'secret'
        ]);
$app->getOAuth();
```

**Comment by moniang** [comment]
你要不试试传个空字符串看看

**Comment by JoeZing** [comment]
更新到dev版本后没问题了
