### ISSUE TITLE
postJson() 方法找不到

### ISSUE THREAD

**Issue by badongdyc** [w7corp/easywechat#2492]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本："w7corp/easywechat": "^6.0.0"
* 是否使用了框架？框架名称：laravel 版本9.15

## 问题及现象

`$app=app('easywechat.mini_app.default');`
`$data=['code'=>$request->code];`
`$res=$app->getClient()->postJson('wxa/business/getuserphonenumber',$data);`
以下是报错截图
![8AC KD 4`6F 92(R$T8XE2T](https://user-images.githubusercontent.com/17975624/171694502-61cc5c61-30bc-4cec-a43e-e1139c409bdf.png)

**Comment by badongdyc** [comment]
已解决

**Comment by imfoggy** [comment]
遇到了同样的问题  请问是怎么解决的

**Comment by badongdyc** [comment]
@imfoggy 版本问题，删除镜像源，重新下载就对了

**Comment by imfoggy** [comment]
@badongdyc 可以了  非常感谢！
