### ISSUE TITLE
6. x微信支付回调没有执行

### ISSUE THREAD

**Issue by xiaoweipeng** [w7corp/easywechat#2493]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.x
* 是否使用了框架？框架名称：laravel

直接使用post是可以获取未解密的数据，但是handlePaid方法始终进不去

**Comment by xiaoweipeng** [comment]
![image](https://user-images.githubusercontent.com/54565603/172747274-e984397f-512e-4846-921e-706cba1bdfab.png)

**Comment by xiaoweipeng** [comment]
日志始终没有打印..应该是没有进去

**Comment by overtrue** [comment]
看 nginx 访问日志

**Comment by xiaoweipeng** [comment]
应该不是nginx导致的  我自己解密没问题了 暂时没有使用你们的方法
