### ISSUE TITLE
企业微信网页授权登录回调接口中获取不到code参数以及code值

### ISSUE THREAD

**Issue by wqjohnston** [w7corp/easywechat#2496]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：laravel5.8+laravels

#### 文件路径为 vendor/overtrue/socialite/src/Providers/WeWorkProvider.php

![image](https://user-images.githubusercontent.com/26755234/172747214-5d609a3d-bc26-4c3c-9c26-a6ea01ee4d7c.png)

### 打印结果
<img width="753" alt="35a1d64fa3e49bed6ca6e245d0ad69f" src="https://user-images.githubusercontent.com/26755234/172747638-f957e68b-de8e-4353-b412-d454d286c955.png">

**Comment by overtrue** [comment]
非 fpm 环境请自行解决兼容问题哈。

**Comment by wqjohnston** [comment]
> 非 fpm 环境请自行解决兼容问题哈。

好的老板
