### ISSUE TITLE
能否考虑将AuthorizerAccessToken的获取和刷新从OpenPlatform里抽出来？

### ISSUE THREAD

**Issue by millsguo** [w7corp/easywechat#2501]
## 我用的环境

* PHP 版本：8.1.6
* overtrue/wechat 版本：6.6.1
* 是否使用了框架？框架名称：ZF1

## 问题及现象

希望单独处理AuthorizerAccessToken，好像没有办法来替换这个，写死在OpenPlatform\Application.php了。或者有没有别的办法来手工来获取和更新呢？

**Comment by overtrue** [comment]
Application 类只是一个工厂类，你完全可以抛弃它使用，参考里面的写法

**Comment by millsguo** [comment]
好的，谢谢指点

**Comment by overtrue** [comment]
> 好的，谢谢指点

不客气
