### ISSUE TITLE
企业微信，获取客户群详情时，日志有记录返回数据，但是接口返回的数据为空

### ISSUE THREAD

**Issue by Dagsi** [w7corp/easywechat#2507]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.18
* 是否使用了框架？框架名称：Phalcon

## 问题及现象
排查了一下，是因为EasyWeChat\Kernel\Http\Response的removeControlCharacters导致的数据为空，估计是因为表情符号导致的，在preg_replace语句修改为\preg_replace('/[\x00-\x1F\x80-\x9F]/u', '', mb_convert_encoding($content, 'UTF-8', 'UTF-8'))可以解决，问题和issues/1101类似
![image](https://user-images.githubusercontent.com/39049329/174778450-aa80bee3-6018-4cf5-ba92-c8864fe837de.png)
![image](https://user-images.githubusercontent.com/39049329/174778652-49622cf3-4f7d-4fce-8d4d-1accacfcbe54.png)

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/compare/5.27.0...5.27.2
