### ISSUE TITLE
使用了PSR扩展的框架无法重新绑定缓存

### ISSUE THREAD

**Issue by Dagsi** [w7corp/easywechat#2532]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.27.2
* 是否使用了框架？框架名称：Phalcon4.0

## 问题及现象

easywechat在重新绑定缓存的时候，判断是否继承接口的时候，报错了，报错代码：
![image](https://user-images.githubusercontent.com/39049329/177521462-faf9a0c5-3f48-4655-a603-0cbdbde56e6c.png)
打印出来的$cache
![image](https://user-images.githubusercontent.com/39049329/177521660-1da41098-3aef-44ce-aeb6-33afcd0f024e.png)
$cache实例是继承了Psr\Cache\CacheItemPoolInterface的，但是因为psr扩展路径变为了PsrExt\Cache\CacheItemPoolInterface

**Comment by overtrue** [comment]
严格来讲，这根本就不是PSR，只是实现了和PSR一样的一个扩展而已
