### ISSUE TITLE
"Credential \"component_verify_ticket\" does not exist in cache."

### ISSUE THREAD

**Issue by dovvvvvvv** [w7corp/easywechat#2539]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.x
* 是否使用了框架？框架名称：ThinkPHP5.1

## 问题及现象

![image](https://user-images.githubusercontent.com/95133030/178888174-1ae56d61-6d68-42b4-8f8b-7c0a631570a4.png)
显示缓存中不存在这个key，然后我在
    /**
     * Put the credential `component_verify_ticket` in cache.
     *
     * @param string $ticket
     *
     * @return $this
     *
     * @throws \EasyWeChat\Kernel\Exceptions\InvalidArgumentException
     * @throws \EasyWeChat\Kernel\Exceptions\RuntimeException
     * @throws \Psr\SimpleCache\InvalidArgumentException
     */
    public function setTicket(string $ticket)
    {
        $this->getCache()->set($this->getCacheKey(), $ticket, 3600);
        dd($this->getCache($this->getCacheKey()));
        if (!$this->getCache()->has($this->getCacheKey())) {
            throw new RuntimeException('Failed to cache verify ticket.');
        }

        return $this;
    }
这个方法中添加了一个断点，发现并没有执行这个方法。是我中间缺少了步骤吗？
![image](https://user-images.githubusercontent.com/95133030/178888489-308e0e66-6481-4406-91d2-0088e4a4b53f.png)
报错是缓存中没有这个键  "Credential \"component_verify_ticket\" does not exist in cache."

**Comment by overtrue** [comment]
麻烦先搞懂这个东西是哪儿来的，谢谢
