### ISSUE TITLE
关于XXE风险的疑问

### ISSUE THREAD

**Issue by ETOCheney** [w7corp/easywechat#2548]
为什么在这个版本后删除了禁用外部实体，是评估后没有XXE风险吗？
https://github.com/w7corp/easywechat/commit/ba2879579c4e21e43fac09284a61157a3f9d950a#diff-42f55d4ee7dbdd7ae29106fab7b8e24d9274cbbb0b59d186931ccbe6c5b69e82L30

**Comment by TheNorthMemory** [comment]
see [here](https://www.php.net/manual/zh/function.libxml-disable-entity-loader.php#125661)

In PHP 8.0 and later, PHP uses libxml versions from 2.9.0, `libxml_disable_entity_loader` is deprecated.
so it is now safe to remove all `libxml_disable_entity_loader` calls on php8

if you want Backwards Compatibility

use this snippet

```php
if (\PHP_VERSION_ID < 80000) {
    libxml_disable_entity_loader(true);
}
```

**Comment by ETOCheney** [comment]
好的 感谢

**Comment by overtrue** [comment]
？

Cheney ***@***.***>于2022年7月21日 周四13:58写道：
