### ISSUE TITLE
请问一下laravel wechat7.x怎么配置日志文件？

### ISSUE THREAD

**Issue by fansj91** [w7corp/easywechat#2552]
## 我用的环境

* PHP 版本：8

这样是不是不对，我看文档好像没有最新版的配置？
    /*
     * 默认配置，将会合并到各模块中
     */
    'defaults' => [
        'http' => [
            'timeout' => 5.0,
        ],
        'log' => [
//            'level' => env('WECHAT_LOG_LEVEL', 'debug'),
//            'level' => env('WECHAT_LOG_LEVEL', 'info'),
            'level' => env('WECHAT_LOG_LEVEL', 'error'),
            'file' => env('WECHAT_LOG_FILE', storage_path('logs/wechat.log')),
        ],

    ],

**Comment by overtrue** [comment]
7.x SDK 没有日志了
