### ISSUE TITLE
hyperf3.0   swoole如何使用easychat呢？发送http请求报错

### ISSUE THREAD

**Issue by qq1415551519** [w7corp/easywechat#2558]
![31778f9c9698b7ae182f3934bbec129](https://user-images.githubusercontent.com/35022279/181879972-cfba8e0f-b651-4ec1-93ee-4434bced8738.png)
报错信息：
 Could not resolve host: api.weixin.qq.com for "https://api.weixin.qq.com/sns/jscode2session?appid=wx9a9b&secret=8c029369c8ef&js_code=053vFWml2vusE94ilwol2vWbmc2vFWmo&grant_type=authorization_code".

**Comment by overtrue** [comment]
这么明显的问题，错误消息已经告诉你答案了啊🤔

**Comment by qq1415551519** [comment]
大佬，指点一下吧 ，百度没搜到，不清楚怎么改

**Comment by qq1415551519** [comment]
swoole4.8版本  php8.0  hyperf3.0

**Comment by overtrue** [comment]
你真的搜索过这个错误消息？这不都说了解析不了域名吗？DNS问题啊，和框架，SDK有啥关系呢？

**Comment by qq1415551519** [comment]
dns？我直接通过浏览器可以访问，没开vpn，麻烦指点下怎么解决呢？

**Comment by overtrue** [comment]
抱歉这类问题没有标准答案，只能自己排查为啥PHP环境下解析不了DNS。

**Comment by qq1415551519** [comment]
好的多谢
