### ISSUE TITLE
企业微信代开发应用oauth2授权获取访问用户敏感信息，生成oauth2错误

### ISSUE THREAD

**Issue by zio-zhang** [w7corp/easywechat#2564]
## 我用的环境

* PHP 版本 7.4.28
* overtrue/wechat 版本：5.29.0
* 是否使用了框架？框架名称：hyperf

## 问题及现象

企业微信代开发应用oauth2授权，生成的授权链接不对，因含有agentId，变成了第三方网页应用登录（扫码登录）

正确链接为：
`
https://open.weixin.qq.com/connect/oauth2/authorize?appid=CORPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&agentid=AGENTID&state=STATE#wechat_redirect
`
对应文档：[构造网页授权文档](https://developer.work.weixin.qq.com/document/path/91120)

企业微信最近做了很多安全升级，增加了部分接口
[自建应用与第三方应用的对接](https://developer.work.weixin.qq.com/document/path/95884)
1、userid转换：将代开发应用或第三方应用获取的密文open_userid转换为明文userid。
2、external_userid转换：将代开发应用或第三方应用获取的externaluserid转换成自建应用的externaluserid。

希望5.x能支持一下

**Comment by overtrue** [comment]
应该是什么样的 URL ？

**Comment by zio-zhang** [comment]
> 应该是什么样的 URL ？

上面问题中有说明啊？？？？
正确链接为：
https://open.weixin.qq.com/connect/oauth2/authorize?appid=CORPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&agentid=AGENTID&state=STATE#wechat_redirect
对应文档：[构造网页授权文档](https://developer.work.weixin.qq.com/document/path/91120)

**Comment by overtrue** [comment]
你的代码呢？怎么用的？

**Comment by zio-zhang** [comment]
> 你的代码呢？怎么用的？

$work->oauth->scopes(['snsapi_privateinfo'])->redirect($url)

**Comment by overtrue** [comment]
$work 是哪个应用？OpenWork 还是 Work

**Comment by overtrue** [comment]
你给的链接是第三方，所以你这里的 $work 应该是 open work 的实例

**Comment by zio-zhang** [comment]
work,文档上也是企业微信代开发应用
现在也可以了用，获取到代码后，替换加agentid进行处理，
不能直接设agentid就变成另外一个链接 了，与文档 不一致

**Comment by overtrue** [comment]
![image](https://user-images.githubusercontent.com/1472352/185856577-9cd32a12-244d-4977-9628-a78a8d49b6de.png)
麻烦你看清楚你给的链接是第三方，不是企业微信自由应用开发

**Comment by zio-zhang** [comment]
> ![image](https://user-images.githubusercontent.com/1472352/185856577-9cd32a12-244d-4977-9628-a78a8d49b6de.png) 麻烦你看清楚你给的链接是第三方，不是企业微信自建应用开发

微信的文档是这样的，没办法，企业代开发应用做了升级，也一样的要授权获取敏感信息，scope使用snsapi_privateinfo,构造的就是下面的那个，这个已测试过，获取了用户敏感信息。

我也找遍了easywechat，也没有找到一个对应的，只有这个是比较相同的，只是少了一个agentid，easywechat怎么用你是专家，我只是提一下建议，可能有不对的地方
这个没有，自己构建也不难，提出来只是为了方便使用组件的人而已。

**Comment by overtrue** [comment]
我的意思是，既然是第三方，就应该按第三方的文档用就好了，我不能把自建应用的文档改成第三方啊，这是错误的。

**Comment by overtrue** [comment]
我看了一眼旧的（5.x）代码，没有专门的生成服务商的 OAuth 的 URL 的方法，所以如果使用 5.x 可以使用 https://github.com/overtrue/socialite/blob/4.x/src/Providers/WeWork.php 来实现

**Comment by overtrue** [comment]
其实 easywechat 里的 oauth 都是https://github.com/overtrue/socialite 这个包实现的。

**Comment by zio-zhang** [comment]
具体实现和开发都清楚，自己处理没什么问题。 
只是5.x找不到相关的文档说明，一般可以在代码中直接搜文档中请求的接口，找到对应的实例及方法。

代开发应用，主要是因为企业微信相关升级，没升级前是属于work级的，升级后又和第三方有点相关

**Comment by zio-zhang** [comment]
> 我的意思是，既然是第三方，就应该按第三方的文档用就好了，我不能把自建应用的文档改成第三方啊，这是错误的。

代开发应用，主要是因为企业微信相关升级，没升级前，它跟自建应用是一样的，升级后，又和第三方有点像，位置不好放

**Comment by zio-zhang** [comment]
> 其实 easywechat 里的 oauth 都是https://github.com/overtrue/socialite 这个包实现的。

业务处理，自己都已实现处理，只是想着组件统一，就提一下；

**Comment by overtrue** [comment]
是，不过最近企业微信的变态更新让开发者很难受，还要收费，又搞什么待开发，让原本屎一样的 API 更难用了，只能说祝早日倒闭吧。

感谢提醒哈。
