### ISSUE TITLE
v4版本,微信退款证书放在oss上 接口还是报SSL证书找不到

### ISSUE THREAD

**Issue by siyecoo** [w7corp/easywechat#2568]
## 我用的环境

* PHP 版本：
* overtrue/wechat 版本：4
* 是否使用了框架？框架名称：tp6

**Comment by overtrue** [comment]
从来就没有支持过远程证书啊

**Comment by siyecoo** [comment]
嗯 我刚才也去问微信技术了,他们也说不支持远程证书 谢谢了
