### ISSUE TITLE
企业微信服务商调用 获取企业授权信息 问题！

### ISSUE THREAD

**Issue by 287640817** [w7corp/easywechat#2569]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：5.X
* 是否使用了框架？框架名称：TP

## 问题及现象

$work = $app->work('授权企业的corp_id','授权企业的永久授权码');
这里的授权企业的corp_id 从哪获取。
我这边是用的代开发模板，授权回调的时候可以拿到 permanent_code\":\"f6adUF6-CqTYeeApHwhlSSScCx5T_wWOB0FM_-P3Kss 永久授权码，auth_corp_info\":{\"corpid\":\"wpHylaFgAAZSqam2uawB3_8m6TDvhtdd\  这个也能拿到，但调用接口的时候
$this->openWork->work('wpHylaFgAAZSqam2uawB3_8m6TDvhtdd','f6adUF6-CqTYeeApHwhlSSScCx5T_wWOB0FM_-P3Kss')->agent->get('1000005')  报这个错误！Request access_token fail: {"errcode":40084,"errmsg":" invalid authorizer permanent code , hint: 请问这是哪个地方参数错了。

**Comment by overtrue** [comment]
看提示就是永久授权码错误哦，SDK 只是一个传递参数的作用，没有修改你的授权码，所以请自己检查上下文逻辑是否有问题。
