### ISSUE TITLE
5.x切换到php8.1网页登陆报错

### ISSUE THREAD

**Issue by chaituan** [w7corp/easywechat#2570]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：5.29.1
* 是否使用了框架？框架名称：codeigniter 4

## 问题及现象
php7.4是正常的，
切换到php8.1网页授权登陆后提示，请教一下这是什么问题？
`ErrorException #1
During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Overtrue\Socialite\User::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/wwwroot/fqsqs.chaituans.com/vendor/overtrue/socialite/src/Traits/HasAttributes.php:53 Stack trace: #0 /home/wwwroot/fqsqs.chaituans.com/vendor/overtrue/socialite/src/User.php(11): CodeIgniter\Debug\Exceptions->errorHandler() #1 /home/wwwroot/fqsqs.chaituans.com/fanqie/Autoloader/Autoloader.php(282): include_once('...') #2 /home/wwwroot/fqsqs.chaituans.com/fanqie/Autoloader/Autoloader.php(259): CodeIgniter\Autoloader\Autoloader->includeFile() #3 /home/wwwroot/fqsqs.chaituans.com/fanqie/Autoloader/Autoloader.php(237): CodeIgniter\Autoloader\Autoloader->loadInNamespace() #4 /home/wwwroot/fqsqs.chaituans.com/vendor/overtrue/socialite/src/Providers/WeChat.php(181): CodeIgniter\Autoloader\Autoloader->loadClass() #5 /home/wwwroot/fqsqs.chaituans.com/vendor/overtrue/socialite/src/Providers/Base.php(112): Overtrue\Socialite\Providers\WeChat->mapUserToObject() #6 /home/wwwroot/fqsqs.chaituans.com/vendor/overtrue/socialite/src/Providers/WeChat.php(146): Overtrue\Socialite\Providers\Base->userFromToken() #7 /home/wwwroot/fqsqs.chaituans.com/app/Controllers/Fanqie/Login.php(71): Overtrue\Socialite\Providers\WeChat->userFromCode() #8 /home/wwwroot/fqsqs.chaituans.com/fanqie/CodeIgniter.php(898): App\Controllers\Fanqie\Login->signin() #9 /home/wwwroot/fqsqs.chaituans.com/fanqie/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController() #10 /home/wwwroot/fqsqs.chaituans.com/fanqie/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest() #11 /home/wwwroot/fqsqs.chaituans.com/index.php(22): CodeIgniter\CodeIgniter->run() #12 {main} 
`

**Comment by overtrue** [comment]
```bash
$ composer require overtrue/socialite:^3.5.2
```
