### ISSUE TITLE
如何强制刷新access_token

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2582]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.7.3
* 是否使用了框架？框架名称：Laravel 9.0

## 问题及现象

如何强制刷新access_token

**Comment by hihuangwei** [comment]
````
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest rid: 630b6db2-67134d6f-09abfa92"}
````

过期或失效无法自动刷新，或者提供强制刷新的api

**Comment by overtrue** [comment]
哪个模块啊

**Comment by hihuangwei** [comment]
> 哪个模块啊

`$response = $api->get('/cgi-bin/user/info', [
            'query' => [
                'openid' => $weChatUser['open_id'],
                'lang' => 'zh_CN',
            ],
        ]);`

**Comment by overtrue** [comment]
公众号还是小程序还是企业微信还是开放平台

**Comment by hihuangwei** [comment]
> 公众号还是小程序还是企业微信还是开放平台

公众号

**Comment by overtrue** [comment]
https://easywechat.com/6.x/official-account/config.html#%E9%85%8D%E7%BD%AE 配置里启用自动重试

**Comment by hihuangwei** [comment]
> https://easywechat.com/6.x/official-account/config.html#%E9%85%8D%E7%BD%AE 配置里启用自动重试

开启重试，依然还是40001

**Comment by overtrue** [comment]
如果凭证本身就有问题重试多次也无效，先检查配置吧

**Comment by zymeli** [comment]
注意cache的序列化问题，特别是跨多个服务器环境的共享

**Comment by overtrue** [comment]
> https://github.com/w7corp/easywechat/blob/6.x/src/OfficialAccount/AccessToken.php#L101

```php
$app->getAccessToken()->refresh();
```
