### ISSUE TITLE
微信用户授权规则调整，默认返回虚拟数据

### ISSUE THREAD

**Issue by dancelion** [w7corp/easywechat#2604]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.8.0
* 是否使用了框架？框架名称：Thinkphp 6

## 问题及现象
微信用户授权规则调整
当开发者在网页中在不规范使用发起 snsapi_userinfo 网页授权时，微信将默认打开网页快照页模式进行基础浏览（[公告链接](https://developers.weixin.qq.com/community/minihome/doc/000c2c34068880629ced91a2f56001)）。能力调整将于 2022 年 7 月 12 日 24 时生效。
当`scope=snsapi_userinfo` 时现在用户第一次跳转到回调地址后实际进入快照页，返回的信息为虚拟的用户信息，并且通过 code 换取网页授权access_token时增加了返回参数`is_snapshotuser | 是否为快照页模式虚拟账号，只有当用户是快照页模式虚拟账号是返回，值为1`，能否在UserInterface里增加is_snapshotuser属性，用于在业务里判断是否提示用户点击下方授权获取真实用户信息。

公告截图
![快照1](https://user-images.githubusercontent.com/7478515/195566211-ecc498b7-86f1-465f-9074-1a5e2973c79b.png)
code 换取网页授权access_token时参数
![快照2](https://user-images.githubusercontent.com/7478515/195566210-2316bafd-5101-4639-90bb-9782ffba7d0b.png)

**Comment by wjfz** [comment]
UserInterface有个getRaw()方法，可以取到原始参数。

**Comment by dancelion** [comment]
> UserInterface有个getRaw()方法，可以取到原始参数。

多谢，在您的提示下，找到了。不是在getRaw()方法，是在getAttributes()方法里的token_response属性里

**Comment by williamqian** [comment]
> UserInterface有个getRaw()方法，可以取到原始参数。

这个只有scope是snsapi_userinfo才有用，我用的是5.0版本
