### ISSUE TITLE
企业微信授权scopes=snsapi_privateinfo报错agent_id必填，需要额外调用withAgentId，是否可优化呢？

### ISSUE THREAD

**Issue by lyt8384** [w7corp/easywechat#2619]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.9.2
* 是否使用了框架？框架名称：否

## 问题及现象

伪代码如下
```
$config = [
    'agent_id' => '1000005'
    'corp_id' => 'xxxxx', //企业ID
    'secret'   => 'xxxxx', // 应用的 secret
];
$app = new EasyWeChat\work\Application($config);
$url = $app->getOAuth()->scopes(['snsapi_privateinfo'])->redirect('CallBack URL');
```
会报错`agent_id is require when qrcode mode or scopes is 'snsapi_privateinfo'`
分析代码，在[/src/Work/Application.php L143](https://github.com/w7corp/easywechat/blob/60f0b4ba2ac3144df1a2291193daa34beb949d26/src/Work/Application.php#L143) 调用`Overtrue\Socialite\Providers\WeWork`时未传入`agent_id`, 但是在[overtrue/socialite](https://github.com/overtrue/socialite/blob/4.x/src/Providers/WeWork.php#L35) 那一侧又支持带入agent_id，这里是否可优化呢？

ps.虽然可以在`getOAuth()`后`withAgentId($agent_id)`去解决这个问题，但是总感觉能配置的不应该再在调用中去带入用。
thx~

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/6.9.3 试试看

**Comment by jiangslee** [comment]
这个agentId是不是过不了phpunit？

```
Script phpstan analyse --memory-limit=-1 handling the phpstan event returned with error code 1
> phpunit --colors
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

...............................................................  63 / 176 ( 35%)
............................................................... 126 / 176 ( 71%)
................................E.................              176 / 176 (100%)

Time: 00:00.191, Memory: 18.00 MB

There was 1 error:

1) EasyWeChat\Tests\Work\ApplicationTest::test_get_oauth
ReflectionException: Cannot access non-public property Overtrue\Socialite\Providers\WeWork::$agentId

/Users/jiangslee/php/easywechat-git/tests/Work/ApplicationTest.php:270

ERRORS!
Tests: 176, Assertions: 523, Errors: 1.
Script phpunit --colors handling the test event returned with error code 2
```

**Comment by overtrue** [comment]
```
➜ composer test
> phpunit --colors
PHPUnit 9.5.25 #StandWithUkraine

...............................................................  63 / 176 ( 35%)
............................................................... 126 / 176 ( 71%)
..................................................              176 / 176 (100%)

Time: 00:00.257, Memory: 16.00 MB

OK (176 tests, 526 assertions)
```

我擦嘞？php 几？

**Comment by jiangslee** [comment]
> ```
> 
> ➜ composer test
> 
> > phpunit --colors
> 
> PHPUnit 9.5.25 #StandWithUkraine
> 
> 
> 
> ...............................................................  63 / 176 ( 35%)
> 
> ............................................................... 126 / 176 ( 71%)
> 
> ..................................................              176 / 176 (100%)
> 
> 
> 
> Time: 00:00.257, Memory: 16.00 MB
> 
> 
> 
> OK (176 tests, 526 assertions)
> 
> ```
> 
> 
> 
> 我擦嘞？php 几？

我好像是8.0.1x，还有fork那的ci php-8-lowest和php-8.1-lowest过不了，https://github.com/jiangslee/easywechat/actions/runs/3501977162
