### ISSUE TITLE
这个 externalUserId在哪里获取呢？

### ISSUE THREAD

**Issue by msmax** [w7corp/easywechat#2620]
## 我用的环境

* PHP 版本：  "php": "^7.3|^8.0",
* overtrue/wechat 版本： "w7corp/easywechat": "^5.30"
* 是否使用了框架？框架名称："laravel/framework": "^8.75",

## 问题及现象

```
  public function serve()
    {
        $config = config('wechat.work');
        $app = Factory::work($config);
        $app->server->push(function($message){
            Log::warning($message);
        });
        $response = $app->server->serve();
        return $response;
    }
```

**执行后写入日志有这些内容**

```
[2022-11-14 09:22:44] local.WARNING: array (
  'ToUserName' => '3771108b0',
  'CreateTime' => '1668417764',
  'MsgType' => 'event',
  'Event' => 'kf_msg_or_event',
  'Token' => 'ENC8SgHsWogZdFDom1StKe3iYBc8Sf3M7uLtgcmCJhjMjD',
)  
```

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/15795938/201811242-c185ff11-fea3-4c43-9a50-bec8a3007e59.png">

> 我想调用这里的接口把，拿到客户发的文字内容进行一些关键字回复，比如，回复微信，我就把个人微信号推送过去。做一些定制化的操作。
> 其中有一个externalUserId 参数，我没有找到在哪里获取呢？

### 微信的官方文档上这里和上面得到的$message是一致的。

```
<xml>
   <ToUserName><![CDATA[78910]]></ToUserName>
   <CreateTime>1348831860</CreateTime>
   <MsgType><![CDATA[event]]></MsgType>
   <Event><![CDATA[kf_msg_or_event]]></Event>
   <Token><![CDATA[ENCApHxnGDNAVNY4AaSJKj4Tb5mwsEMzxhFmHVGcra996NR]]></Token>
</xml>
```

##  在微信官方文档中的读取消息接口有这样的说明。

<img width="929" alt="image" src="https://user-images.githubusercontent.com/15795938/201811889-f429c4c6-3f14-4730-a7b6-514ff0c10edd.png">

但这个cursor参数又在哪获取呢？

在这里看到有这个externalUserId但就需要上一步的cusor。
```
{
    "errcode": 0,
    "errmsg": "ok",
    "next_cursor": "4gw7MepFLfgF2VC5npN",
	"has_more": 1,
    "msg_list": [
        {
            "msgid": "from_msgid_4622416642169452483",
            "open_kfid": "FhToWMFea0xAFfd3Q",
            "external_userid": "wmAJ2GCAAAme1XQRC-NI-q0_ZM9ukoAw",
            "send_time": 1615478585,
            "origin": 3,
			"servicer_userid": "Zhangsan",
            "msgtype": "MSG_TYPE"
        }
    ]
}
```

**Comment by tourze** [comment]
你可以理解为kf_msg_or_event是企微通知你，有新的客服消息产生了。

然后你在知晓这个事件后，主动调用 https://kf.weixin.qq.com/api/doc/path/94745 去拉取聊天内容。

cursor 值是企微他们维护的，第一次拉取不用传还是传空的这里忘记，第二次的话就用上一次返回的next_cursor来拉取下一批消息。
也因此，你需要本地存储好这个 cursor 值，要不拉取的消息就可能重复。

虽然这个流程看起来冗余且诡异，但是谁叫你不是张小龙呢，哎。

**Comment by msmax** [comment]
谢谢，这个我算是明白了。
