### ISSUE TITLE
微信发起授权中laravel跳转问题

### ISSUE THREAD

**Issue by fss815** [w7corp/easywechat#2626]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.0
* 是否使用了框架？框架名称：laravel 8.*

## 使用官网文档中
return \redirect($redirectUrl);
报错，应改为return $redirectUrl;

**Comment by wjfz** [comment]
如果外层有跳转操作，当然要返回跳转地址的 string。
官网文档说的是在“控制器”中。

后续讨论移步：https://github.com/w7corp/easywechat/discussions
