### ISSUE TITLE
Read the $certificate failed, please check it whether or nor correct

### ISSUE THREAD

**Issue by northFlyX** [w7corp/easywechat#2639]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.10.0
* 是否使用了框架？框架名称：thinkphp6

## 问题及现象
无法解析微信证书文件,会报错
Read the $certificate failed, please check it whether or nor correct
![WX20221225-173140@2x](https://user-images.githubusercontent.com/116325855/209463017-ba008c17-27a0-4456-814c-7b7b958863d7.png)

**Comment by TheNorthMemory** [comment]
嗖，你的入参 `$this->certificate` 是什么？

**Comment by northFlyX** [comment]
![WX20221225-175115@2x](https://user-images.githubusercontent.com/116325855/209463508-6cd5dd14-5b75-4e6c-ac64-662d79d8bca2.png)
$this->certificate是官方config示例当中的platform_certs参数，报错截图中的代码是EasyWeChat的初始化方法

**Comment by TheNorthMemory** [comment]
写绝对路径 `file:///path/to/certs/wechatpay_xxxx.pem`
