### ISSUE TITLE
Laravel 10 需要升级 monolog 3.0

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2653]
## 我用的环境

Laravel 10 需要升级 monolog 3.0

* PHP 版本：8.1
* overtrue/wechat 版本：6.0
* 是否使用了框架？框架名称：laravel 10.0

**Comment by zeevin** [comment]
+1 ，有同样的需求

**Comment by Wangzh0927** [comment]
楼主这个还没有发布版本吧，https://github.com/overtrue/laravel-wechat 这里引用了 6.0，然后又跟monolog 冲突
