### ISSUE TITLE
公众号刷新 access_token 无效

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2657]
## 我用的环境

* PHP 版本：8.1.0
* overtrue/wechat 版本：6.11.1
* 是否使用了框架？框架名称：Laravel 10

## 问题及现象

刷新 access_token 无效 $app->getAccessToken()->refresh();

**Comment by overtrue** [comment]
什么叫无效？

**Comment by hihuangwei** [comment]
> 什么叫无效？

执行刷新，还是旧的access-token

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/blob/6.x/src/OfficialAccount/AccessToken.php#L101-L122  你看看这里的逻辑哈，看看到哪一步没生效
