### ISSUE TITLE
使用 getAccessToken的时候报CURLOPT_SHARE option is not supported，请问怎么回事

### ISSUE THREAD

**Issue by Lazybin** [w7corp/easywechat#2662]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.7
* 是否使用了框架？框架名称：hyperf

## 问题及现象

报CURLOPT_SHARE option is not supported

![image](https://user-images.githubusercontent.com/2576969/221473455-8c51c473-54da-4154-ad30-a1782363aaf5.png)

代码
```php
use EasyWeChat\MiniApp\Application;
$config = [
            'app_id' => env('WECHAT_APPID'),
            'secret' => env('WECHAT_SECRET'),
        ];


        $app = new Application($config);
        $accessToken = $app->getAccessToken();
        var_dump($accessToken->getToken());
```

**Comment by overtrue** [comment]
https://github.com/swoole/swoole-src/issues/4606
