### ISSUE TITLE
Cannot assign EasyWeChat\Kernel\Config to property EasyWeChat\MiniApp\Application::$config of type EasyWeChat\Kernel\Contracts\Config

### ISSUE THREAD

**Issue by yulin1115** [w7corp/easywechat#2663]
## 我用的环境

* PHP 版本：8.1.11
* overtrue/wechat 版本："w7corp/easywechat": "^6.8"
* 是否使用了框架？框架名称：laravel8

## 问题及现象
"Cannot assign EasyWeChat\Kernel\Config to property EasyWeChat\MiniApp\Application::$config of type EasyWeChat\Kernel\Contracts\Config"
`<?php

namespace App\Application\Front;

use App\Exceptions\CommonException;
use Core\Member\Model\Member;
use Core\Member\Service\MemberService;
use EasyWeChat\MiniApp\Application;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Application\Common\AreaApplication;

class MemberApplication
{
    /**
     * @var MemberService
     */
    protected $member_service;
    protected $area_application;

    /**
     * MemberApplication constructor.
     */
    public function __construct()
    {
        $this->member_service = resolve('MemberService');
        $this->area_application = new AreaApplication();
    }

    public function wxLogin($code, $area_id): array
    {
        //根据area_id获取微信配置
        $area_wechat_config = $this->area_application->getWechatConfigByAreaId($area_id);
        if (empty($area_wechat_config)) {
            throw new CommonException('未查询到微信配置', 1, 200);
        }
        $config = [
            'app_id' => $area_wechat_config['app_id'],
            'secret' => $area_wechat_config['app_secret'],
        ];
        $app = new Application($config);
        echo 2;
        exit;

    }
}
`

$config 是数组

**Comment by overtrue** [comment]
1.  是否用了 hyperf 或者 swoole 之类的扩展
2. 是否重写了 `EasyWeChat\Kernel\Config` 类
3. 是否改动过 `vendor/` 的任何文件
4. 是否使用第三方 composer 源

如果都没有，则删掉 vendor 目录和 composer.lock 重新安装后再试。

**Comment by yulin1115** [comment]
> 1. 是否用了 hyperf 或者 swoole 之类的扩展
> 2. 是否重写了 `EasyWeChat\Kernel\Config` 类
> 3. 是否改动过 `vendor/` 的任何文件
> 4. 是否使用第三方 composer 源
> 
> 如果都没有，则删掉 vendor 目录和 composer.lock 重新安装后再试。

好像知道原因了，之前装过overtrue/wechat，可能冲突了，多谢

**Comment by overtrue** [comment]
好的哈
