### ISSUE TITLE
4.x版本文档里面有api叫用的方法但实际上代码没有

### ISSUE THREAD

**Issue by hujianjian187** [w7corp/easywechat#2669]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：4.6.0
* 是否使用了框架？框架名称：thinkphp5.1.42

## 问题及现象

`

        $app = Factory::officialAccount($config);
        $app->getClient();
`
4.x文档中有显示通用api调用的方法 
$api = $app->getClient();
但是结果getClient()方法并不能调用 且未定义

**Comment by overtrue** [comment]
请问你是不是看错了，https://easywechat.com/4.x/official-account/index.html 4.x 没有这个方法，6.x 才有哈

**Comment by hujianjian187** [comment]
https://easywechat.com/4.x/client.html 这里 最下面 ‘通用’ 里面

**Comment by overtrue** [comment]
文档有误，你可以使用 `$app->base->httpPost()` 这样子

**Comment by hujianjian187** [comment]
> 文档有误，你可以使用 `$app->base->httpPost()` 这样子

好的 谢谢  我看了你们之前好些有提交这个代码 好像没合并
![image](https://user-images.githubusercontent.com/22463383/225509201-c38a4dcf-7863-409b-8c0e-dfe87a72634e.png)

我现在用的这种方式
`
        $app = Factory::openPlatform($config);
        // $app->getClient();
        $cliect = new \EasyWeChat\Kernel\BaseClient($app);
        $cliect->httpPostJson();
`

**Comment by hujianjian187** [comment]
我主要是搞开放平台 Factory::openPlatform 没有base属性  好像只能实例化 \EasyWeChat\Kernel\BaseClient($app)

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/4.8.0 是忘记发版哈哈哈

**Comment by hujianjian187** [comment]
> https://github.com/w7corp/easywechat/releases/tag/4.8.0 是忘记发版哈哈哈

额。。。。 好像 composer 下的版本 还是4.6.0

**Comment by overtrue** [comment]
应该是你的源的问题哈，https://packagist.org/packages/w7corp/easywechat 这里都能看到最新的版本 4.8.0
