### ISSUE TITLE
4.x API 调用不需要$app->getClient()

### ISSUE THREAD

**Issue by chengnan199** [w7corp/easywechat#2672]
## 我用的环境

* PHP 版本：7.2
* overtrue/wechat 版本：4.x
* 是否使用了框架？框架名称：thinkphp

## 问题及现象

![image](https://user-images.githubusercontent.com/45030296/228154507-78a7d73b-5bd7-4dd2-9af0-3a4ea2ac9ac6.png)

API 调用可直接 ` $app->httpPostJson()` 不需要  ` $api = $app->getClient()->httpPostJson() `

**Comment by overtrue** [comment]
谢谢
