### ISSUE TITLE
最新版本的 laravel 10 无法正常安装

### ISSUE THREAD

**Issue by worldwillgood** [w7corp/easywechat#2680]
## 我用的环境

* PHP 版本：8.2.5
* overtrue/wechat 版本：6.11.3
* 是否使用了框架？框架名称：laravel

## 问题及现象

```composer require w7corp/easywechat:^6.11.3```
<img width="573" alt="image" src="https://user-images.githubusercontent.com/127164764/232647066-9d2d097e-e0e7-44da-a031-42f4bbdb871d.png">

**Comment by overtrue** [comment]
```bash
composer require w7corp/easywechat:^6.11.3 -W
```
