### ISSUE TITLE
6.x新版本的回调中如果逻辑报错，如何告知微信通知失败，让微信发起轮询通知策略

### ISSUE THREAD

**Issue by yuhanyo** [w7corp/easywechat#2689]
## 我用的环境

* PHP 版本：php8.8
* overtrue/wechat 版本：6.x
* 是否使用了框架？框架名称：laravel

## 问题及现象

新版本的回调中如果我的逻辑报错，如何像下图5.x版本告诉微信，让微信认为通知失败。微信会通过一定的策略定期重新发起通知，通知频率为15s/15s/30s/3m/10m/20m/30m/30m/30m/60m/3h/3h/3h/6h/6h - 总计 24h4m）

![image](https://user-images.githubusercontent.com/14796430/236165296-1a6a5489-1a52-4f4d-b1da-41694a89de4d.png)

##我的代码：
按照我的代码返回失败 微信不会轮询通知。
![image](https://user-images.githubusercontent.com/14796430/236166853-0a2773dd-11ec-4057-b729-201e6160b836.png)

**Comment by TheNorthMemory** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_3_5.shtml

<h3 style="margin: 30px 0px 10px; padding: 0px; font-size: 22px; font-weight: 700; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 黑体, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">通知应答</h3><p style="margin: 10px 0px; padding: 0px; line-height: 28px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 黑体, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>接收成功：</strong>HTTP应答状态码需返回200或204，无需返回应答报文。</p><p style="margin: 10px 0px; padding: 0px; line-height: 28px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 黑体, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>接收失败：</strong>HTTP应答状态码需返回5XX或4XX，同时需返回应答报文，格式如下：</p><div class="table-wrp" style="margin-bottom: 20px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 黑体, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

参数名 | 变量 | 类型[长度限制] | 必填 | 描述
-- | -- | -- | -- | --
返回状态码 | code | string[1,32] | 是 | 错误码，SUCCESS为清算机构接收成功，其他错误码为失败。示例值：FAIL
返回信息 | message | string[1,64] | 是 | 返回信息，如非空，为错误原因。示例值：失败

</div><br style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 黑体, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="section-box" style="color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, 黑体, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="section-tab"><ul class="clr" style="margin: 0px; padding: 0px; list-style: none; zoom: 1; border-bottom: 1px solid rgb(235, 235, 235);"></ul></div><div class="section-cnt" id="cnt-json" style="border-right: 1px solid rgb(235, 235, 235); border-bottom: 1px solid rgb(235, 235, 235); border-left: 1px solid rgb(235, 235, 235); border-image: initial; border-top: none; max-height: 430px; min-height: 40px; overflow-y: auto; background: rgb(24, 48, 85); width: 803.559px; padding-left: 10px;"><pre class="hljs" style="margin: 0px; padding: 0.5em; hyphens: none; overflow: auto; tab-size: 2; direction: ltr; font-size: 14px; background: rgb(24, 48, 85); text-align: left; word-break: normal; font-family: &quot;Source Code Pro&quot;, Consolas, Menlo, Monaco, Courier, monospace; line-height: 1.4; word-spacing: normal; border-radius: 3px; display: block; color: rgb(236, 232, 227);"><code class="auto hljs json" style="word-break: normal; width: auto; white-space: pre-wrap; overflow-wrap: break-word; overflow: auto; max-width: 680px; hyphens: none; tab-size: 2; direction: ltr; font-size: 14px; background: rgb(24, 48, 85); text-align: left; font-family: &quot;Source Code Pro&quot;, Consolas, Menlo, Monaco, Courier, monospace; line-height: 1.4; word-spacing: normal; border-radius: 3px; display: block; padding: 0.5em; color: rgb(236, 232, 227);">
{  
    <span class="hljs-attr">"code"</span>: <span class="hljs-string" style="color: rgb(136, 155, 74);">"FAIL"</span>,
    <span class="hljs-attr">"message"</span>: <span class="hljs-string" style="color: rgb(136, 155, 74);">"失败"</span>
}</code></pre></div></div>

依据上述官方开发文档说明，想办法让你的HTTP响应头statusCode 是 4xx/5xx ，微信支付即会再次通知。
