### ISSUE TITLE
上传素材图文接口已经不支持了

### ISSUE THREAD

**Issue by ken678** [w7corp/easywechat#2693]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.x
* 是否使用了框架？框架名称：

## 问题及现象
新增素材图文已经下线 https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11644831863qFQSh&version=&lang=zh_CN
{"errcode":45106,"errmsg":"This API has been unsupported. For more details, please view https:\/\/mp.weixin.qq.com\/cgi-bin\/announce?action=getannouncement&announce_id=11644831863qFQSh&version=&lang=zh_CN hint: [KRi93a0734d106] rid: 6458abbe-15e2270c-1d009592"}

**Comment by ken678** [comment]
原来的图文素材已经变更为草稿箱了

**Comment by overtrue** [comment]
接口下线了 SDK 不会删除该方法哈。

**Comment by ken678** [comment]
> 接口下线了 SDK 不会删除该方法哈。

嗯 但是文档上面没看到获取草稿箱接口

**Comment by overtrue** [comment]
嗯，目前没空跟踪微信的变化哈，你要是有空可以 PR 一个，或者直接用 client 调用 API 也是可以用的。

**Comment by ken678** [comment]
> 嗯，目前没空跟踪微信的变化哈，你要是有空可以 PR 一个，或者直接用 client 调用 API 也是可以用的。

好的  草稿列表是这么调用 $app->draft->batchGet($offset, $count);
