### ISSUE TITLE
微信公众号如何替换JsApiTicket?

### ISSUE THREAD

**Issue by 153264** [w7corp/easywechat#2697]
## 我用的环境

* PHP 版本：8.0.2
* overtrue/wechat 版本：6.8
* 是否使用了框架？框架名称：

## 问题及现象

看了一下代码是setTicket固定了类型
使用实现了`JsApiTicket`类api，提示类型异常
能否像`AccessToken`一样实现对应 implements 就能setTicket
![1684399009431](https://github.com/w7corp/easywechat/assets/36463512/101a93fa-3b63-496f-b743-2cc4099d34e6)

**Comment by overtrue** [comment]
我刚才看了一下它本身是一个工具类，所以如果你去实现一个接口意味着你全部方法都得实现一遍，所以建议你继承重载比较简单方便：

```php
class MyTicket extends JsApiTicket 
{
    // 覆盖你想要覆盖的方法
}

$app->setTicket(new MyTicket(...))
```

**Comment by 153264** [comment]
我看 `EasyWeChat\OfficialAccount\JsApiTicket` 主要功能就是 `getTicket`函数。
感觉可以把`JsApiTicket`的`configSignature`逻辑放在`EasyWeChat\OfficialAccount\Utils`类中。
这样就能把`JsApiTicket`类也弄成可以完全自定义

**Comment by overtrue** [comment]
#2703
