### ISSUE TITLE
laravel重定向微信公众号授权链接提示跨域

### ISSUE THREAD

**Issue by FH8023** [w7corp/easywechat#2702]
![微信图片_20230519165713](https://github.com/w7corp/easywechat/assets/49626993/18943bfc-18b8-4d9c-aa66-1cb486bb799c)
![微信图片_20230519165807](https://github.com/w7corp/easywechat/assets/49626993/2ce3056f-9a45-4812-8900-186f4a1c064a)
![微信图片_20230519165732](https://github.com/w7corp/easywechat/assets/49626993/ca42cc92-7cc0-47c8-91f9-7d0b78925184)
![微信图片_20230519165747](https://github.com/w7corp/easywechat/assets/49626993/fb5d38de-36ed-4392-b821-259ea61d57fb)
代码如上
前端请求我test接口，接口里边直接重定向跳转授权链接，但是在微信开发工具中提示跨域问题（也在路由上添加了中间件但是无效）
但是直接在微信客户端访问授权链接是可以直接执行授权回调的代码拿到最后返回的数据
请问是我这边哪里配置不对还是少做了什么，万望指教，急急急！！！！！！！！

**Comment by overtrue** [comment]
这不是 SDK 的问题请不要提为 issue,感谢！

**Comment by FH8023** [comment]
追加：php版本8.0.2
easywechat版本6.8
laravel版本9.2

**Comment by FH8023** [comment]
> 

那应该提在哪个地方呢

**Comment by overtrue** [comment]
你不是已经在讨论区发过了么?https://github.com/w7corp/easywechat/discussions/2701
