### ISSUE TITLE
为什么公众号网页授权`$user->getRaw()`被画了删除线？

### ISSUE THREAD

**Issue by 153264** [w7corp/easywechat#2704]
## 我用的环境

* PHP 版本：8.0.2
* overtrue/wechat 版本：6.8
* 是否使用了框架？框架名称：

## 问题及现象

是有什么原因吗？

**Comment by overtrue** [comment]
`$user` 哪里来的？截图看看

**Comment by 153264** [comment]
https://easywechat.com/6.x/oauth.html#%E5%BE%AE%E4%BF%A1-oauth
这里
![1684717794804](https://github.com/w7corp/easywechat/assets/36463512/756808bc-fcc9-4ec1-bf29-263cd0b1ef92)

**Comment by overtrue** [comment]
OK

**Comment by 153264** [comment]
w7corp/easywechat 需要升级一下 overtrue/socialite 
现在调用`$user->getAttributes()` 
类型提示Undefined method 'getAttributes'
![1684718036263](https://github.com/w7corp/easywechat/assets/36463512/5c1337d8-836a-4bdc-8f18-f746c13bd3db)

**Comment by overtrue** [comment]
@153264 暂时不能这么直接发版，因为有的用户自己实现了 UserInterface, 如果直接发版他们的项目就崩了，这里的警告你可以先备注一下 $user 就好了：

```php
/** @var Overtrue\Socialite\User $user */
$user = xxxx // 你得到 $user 的地方
```

不过我还是建议你用 getRaw(),  https://github.com/w7corp/easywechat/pull/2413 我看了一下是这个 PR 加的删除线，我打算回滚这个操作，其实本身它就是返回数组，我修复一下这个实现就好了。

**Comment by 153264** [comment]
好的
