### ISSUE TITLE
微信官方新增，获取稳定版接口调用凭据 Stable Access token

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2707]
## 问题及现象

微信官方新增，获取稳定版接口调用凭据 Stable Access token

**Comment by 153264** [comment]
我是直接自己实现了AccessToken类`RefreshableAccessToken`跟`AccessTokenInterface`
直接`setAccessToken`替代内置的`AccessToken`

感觉如果框架兼容这个，我感觉应该是配置项加个`stable`配置，`AccessToken`根据传入配置请求不同接口
