### ISSUE TITLE
laravel10 安装6.X报错

### ISSUE THREAD

**Issue by yulin1115** [w7corp/easywechat#2718]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.8
* 是否使用了框架？框架名称：laravel10

## 问题及现象

Problem 1
    - w7corp/easywechat[6.11.0, ..., 6.12.1] require nyholm/psr7-server ^1.0 -> satisfiable by nyholm/psr7-server[1.0.0, 1.0.1, 1.0.2].
    - w7corp/easywechat[6.8.0, ..., 6.10.0] require monolog/monolog ^2.2 -> found monolog/monolog[2.2.0, ..., 2.9.1] but the package is fixed to 3.4.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - nyholm/psr7-server 1.0.0 requires php ^7.1 -> your php version (8.2.3) does not satisfy that requirement.
    - nyholm/psr7-server[1.0.1, ..., 1.0.2] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires w7corp/easywechat ^6.8 -> satisfiable by w7corp/easywechat[6.8.0, ..., 6.12.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by overtrue** [comment]
加-W

**Comment by cnjackven** [comment]
加了-W也还是一样，laravel版本：10.10，PHP版本：8.2
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires w7corp/easywechat 6.7 -> satisfiable by w7corp/easywechat[6.7.0].
    - w7corp/easywechat 6.7.0 requires monolog/monolog ^2.2 -> found monolog/monolog[2.2.0, ..., 2.9.1] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - w7corp/easywechat 6.7.0 requires monolog/monolog ^2.2 -> found monolog/monolog[2.2.0, ..., 2.9.1] but these were not loaded, likely because it conflicts with another require.
    - overtrue/laravel-wechat 7.2.0 requires w7corp/easywechat ^6.0.0 -> satisfiable by w7corp/easywechat[6.7.0].
    - overtrue/laravel-wechat is locked to version 7.2.0 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by cnjackven** [comment]
已安装了，请忽略

**Comment by brianping7** [comment]
> 已安装了，请忽略

怎么安装的呀兄弟

**Comment by cnjackven** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
