### ISSUE TITLE
请问5.x版本中，是否预留了自定义请求路径的功能？如6.x版本中的自定义api请求

### ISSUE THREAD

**Issue by rwqccazmlli97** [w7corp/easywechat#2727]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.x
* 是否使用了框架？框架名称：thinkphp

## 问题及现象

请问5.x版本中，是否预留了自定义请求路径的功能？如6.x版本中的自定义api请求

$api = $app->getClient();

$response = $api->post();

目前遇到的问题是，企业微信新增了一些接口，目前的做法只能是通过获取access_token，手动执行http请求

👉  https://opencollective.com/wechat/donate -->

**Comment by i838847058** [comment]
RP 呀

**Comment by overtrue** [comment]
具体模块的实例上都可以直接 `httpPostJson()`，比如公众号：`$officialAccount->base->httpPostJson(...)`，具体语法参考源码：https://github.com/w7corp/easywechat/blob/5.x/src/Kernel/BaseClient.php#L70-L121
