### ISSUE TITLE
微信支付 getClient(), postJson

### ISSUE THREAD

**Issue by menthe** [w7corp/easywechat#2728]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.12
* 是否使用了框架？框架名称：laravel/framework 9.19

## 问题及现象

官方文档上微信支付的getClient()返回的client，是有postJson的方法的，但是我翻看了从6.0到6.12所有分支的代码，都是没有postJson的方法的。

就想问一下，官方文档是测试过的吗？

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/blob/6.x/src/Kernel/HttpClient/HttpClientMethods.php

我也不清楚你是如何翻遍代码的，但是它肯定存在。
