### ISSUE TITLE
think-swoole环境下报错swoole_curl_setopt(): option[10100] is not supported

### ISSUE THREAD

**Issue by 23022340** [w7corp/easywechat#2745]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.7
* 是否使用了框架？框架名称：thinkphp8.0+think-swoole

## 问题及现象

在swoole环境下调用小程序jscode2session接口报错，swoole_curl_setopt(): option[10100] is not supported；如果安照easywechat5版本常见问题说明替换Handle是不支持的。
```php
$config = [
    'app_id' => 'wx25b562afb9bb8e30',
    'secret' => 'xxxxxxx',
    'http' => [
        'throw'  => false
    ]
];
$app = new Application($config);
$response = $app->getClient()->get('/sns/jscode2session', [
    'appid' => 'wx25b562afb9bb8e30',
    'secret' => 'xxxxxxx',
    'js_code' => '0b1B6Ull2npNYb4Oa3ol2mVdJh4B6Ul3',
    'grant_type' => 'authorization_code',
]);
dump($response);
```
![微信截图_20230910114923](https://github.com/w7corp/easywechat/assets/60733665/f78b81b2-05b2-410f-9827-e8e4629d4019)

**Comment by overtrue** [comment]
非 fpm 环境不在此SDK考虑范围内，还请自行解决。
