### ISSUE TITLE
laravel 10 无法安装最新的版本，只能安装2.1.14 ，这么老的版本。能不能适配 larvavel 10 的。

### ISSUE THREAD

**Issue by jasonccs** [w7corp/easywechat#2747]
## 我用的环境

* PHP 版本：8.2.5
* overtrue/wechat 版本： 
* 是否使用了框架？框架名称：larvavel 10

## 问题及现象
laravel 10 无法安装最新的版本，只能安装2.1.14 ，这么老的版本。能不能适配 larvavel 10 的。

**Comment by overtrue** [comment]
光凭这句话没有任何有用信息……

**Comment by BadJacky** [comment]
<img width="1183" alt="CleanShot 2023-09-19 at 21 05 00@2x" src="https://github.com/w7corp/easywechat/assets/113529280/36da97b1-9a0f-4c39-92c5-e63b5c07f89d">
<img width="672" alt="CleanShot 2023-09-19 at 21 05 35@2x" src="https://github.com/w7corp/easywechat/assets/113529280/1b837190-3105-4609-b415-1a0a9c250f07">
<img width="906" alt="CleanShot 2023-09-19 at 21 05 51@2x" src="https://github.com/w7corp/easywechat/assets/113529280/d7153d14-52c9-4b4a-8307-6bc0950bff7a">

解决方案就是不要安装使用 6.x 
<img width="620" alt="CleanShot 2023-09-19 at 21 06 54@2x" src="https://github.com/w7corp/easywechat/assets/113529280/ad354807-8370-4954-91da-13cb27d60950">

@jasonccs

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。

**Comment by echoyl** [comment]
2024了 还要-W可解吗？

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。

**Comment by jasonccs** [comment]
要的啊&nbsp;


风起时，想你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月9日(星期六) 中午1:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [w7corp/easywechat] laravel 10 无法安装最新的版本，只能安装2.1.14 ，这么老的版本。能不能适配 larvavel 10 的。 (Issue #2747)





 
2024了 还要-W可解吗？
