### ISSUE TITLE
一直安装不上去

### ISSUE THREAD

**Issue by chunbobo** [w7corp/easywechat#2758]
## 我用的环境

* PHP 版本：7.3.4
* overtrue/wechat 版本：5.0.0
* 是否使用了框架？框架名称：无

## 问题及现象
composer require "overtrue/wechat:^5.0" -vvv
![image](https://github.com/w7corp/easywechat/assets/16535982/58c79406-8956-4224-9808-9b101283935c)

**Comment by overtrue** [comment]
因为你使用了已经好久没维护的packagist 源
