### ISSUE TITLE
企业微信  服务端 推送事件 部门相关事件 的疑问

### ISSUE THREAD

**Issue by shijie1991** [w7corp/easywechat#2760]
## 我用的环境

* PHP 版本：PHP 8.2.10 
* overtrue/wechat 版本：v6
* 是否使用了框架？框架名称：laravel

## 问题及现象

handlePartyCreated 这个方法用的是 InfoType  而我回调显示的是 Event 无法使用
<img width="1065" alt="image" src="https://github.com/w7corp/easywechat/assets/11606404/93e2c59c-1e35-4939-a69e-6e1afcbd8251">

![image](https://github.com/w7corp/easywechat/assets/11606404/5ceaf0e3-7afa-4120-899f-205154b0f09c)

**Comment by overtrue** [comment]
https://developer.work.weixin.qq.com/document/path/92655 
<img width="720" alt="image" src="https://github.com/w7corp/easywechat/assets/1472352/178c4beb-c9ff-4849-93a4-31445a59a052">

**Comment by shijie1991** [comment]
看样子是企业微信第三方服务商专用字段
<img width="846" alt="image" src="https://github.com/w7corp/easywechat/assets/11606404/7329be04-98a7-4266-8b7d-435eda864214">

**Comment by shijie1991** [comment]
https://developer.work.weixin.qq.com/document/path/90240#%E6%96%B0%E5%A2%9E%E9%83%A8%E9%97%A8%E4%BA%8B%E4%BB%B6

<img width="944" alt="image" src="https://github.com/w7corp/easywechat/assets/11606404/724f1733-0303-48ca-bfbb-b7716041b502">

**Comment by wjfz** [comment]
你是 企业内部开发 还是 第三方应用开发？

**Comment by shijie1991** [comment]
> 你是企业内部开发还是第三方应用开​​发？

企业内部应用呀

**Comment by overtrue** [comment]
> > 你是企业内部开发还是第三方应用开​​发？
> 
> 
> 
> 企业内部应用呀

你看看这个issue你的标题？

**Comment by shijie1991** [comment]
羞羞

**Comment by overtrue** [comment]
@shijie1991 的确是，我改好了，更新一下新版。
