### ISSUE TITLE
6.13无法在php8.0安装

### ISSUE THREAD

**Issue by tongxin3267** [w7corp/easywechat#2763]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.13.0
* 是否使用了框架？框架名称：thinkphp

## 问题及现象
![image](https://github.com/w7corp/easywechat/assets/6961093/ca05d574-068e-4a90-bf65-f65a8bde446b)
需要什么条件才能安装

**Comment by overtrue** [comment]
看起来你用了一个非官方 packagist 源，盲猜阿里？阿里已经停止维护了。
