### ISSUE TITLE
psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x.

### ISSUE THREAD

**Issue by vscing** [w7corp/easywechat#2777]
## 我用的环境

* PHP 版本：8.2
* overtrue/wechat 版本：^6.7
* 是否使用了框架？框架名称：thinkphp

## 问题及现象

psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x.

**Comment by overtrue** [comment]
升级 symfony/cache to 6.0+
