### ISSUE TITLE
基于微信公众号微信支付v3,回调报错

### ISSUE THREAD

**Issue by quweiie** [w7corp/easywechat#2778]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.13
* 是否使用了框架？框架名称：没有
支付成功了，但回调时用官网给的代码，报错
## 问题及现象
2023/12/24 14:51:04 [error] 12415#0: *645 FastCGI sent in stderr: ＂PHP message: PHP Fatal error:  Uncaught TypeError: {closure}(): Argument #1 ($message) must be of type Message, EasyWeChat\Pay\Message given, called in /www/wwwroot/myweb/vendor/w7corp/easywechat/src/Pay/Server.php on line 86 and defined in /www/wwwroot/myweb/wxpay/notify.php:25

**Comment by overtrue** [comment]
你的代码贴一下
