### ISSUE TITLE
疑问：配置项参数

### ISSUE THREAD

**Issue by szy4211** [w7corp/easywechat#2780]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.8
* 是否使用了框架？框架名称：laravel

## 问题及现象
- 配置项 `http.retry.http_codes` 是否应为 `http.retry.status_codes`
<img width="1998" alt="image" src="https://github.com/w7corp/easywechat/assets/22878430/fb17743b-6269-427f-b4c0-0d5c97117baf">

**Comment by overtrue** [comment]
感谢反馈，已更新。
