### ISSUE TITLE
 生成小程序二维码报错

### ISSUE THREAD

**Issue by pasawu** [w7corp/easywechat#2781]
## 我用的环境

* PHP 版本：8.1
* overtrue/wechat 版本：6.x
* 是否使用了框架？框架名称：thinkphp8

## 问题及现象

生成小程序二维码

$response = $app->getClient()->postJson('/wxa/getwxacodeunlimit', [
          'scene'      => $id,
          'page'       => 'pages/home/home',
          'width'      => 430,
          'check_path' => false,
      ]);

报错提示：EasyWeChat\Pay\Merchant::__construct(): Argument #1 ($mchId) must be of type string|int, null given, called in /www/wwwroot/lingshuigonghui/vendor/w7corp/easywechat/src/Pay/Application.php on line 53
请问怎么解决

**Comment by TheNorthMemory** [comment]
```php
$app->getClient()
```
请求的是公众号的接口，而获取的是支付的实例的吧

**Comment by pasawu** [comment]
是的，解决了，谢谢

**Comment by pasawu** [comment]
> ```
> $app->getClient()
> ```
> 
> 请求公众是号的接口，而获取是支付的实例吧

是的，解决了，谢谢
