### ISSUE TITLE
能不能升级下symfony/cache的依赖包版本？

### ISSUE THREAD

**Issue by millsguo** [w7corp/easywechat#2787]
## 我用的环境

* PHP 版本：8.2
* overtrue/wechat 版本：6.14
* 是否使用了框架？框架名称：Zend Framework 1

## 问题及现象
由于别的包需要symfony/cache 7.0版本，但我们的EW目前只写了兼容 5.4|6.0版本，能不能兼容到7.0版本？

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/6.15.0
