### ISSUE TITLE
有视频号的接口吗? 后期会添加吗

### ISSUE THREAD

**Issue by pifeifei** [w7corp/easywechat#2795]
## 我用的环境

* PHP 版本：8.1.x
* overtrue/wechat 版本： 任意版本
* 是否使用了框架？框架名称：laravel 9.x

最近需要对接视频号，来这里看看， 好像是没有这个接口

**Comment by overtrue** [comment]
视频号开放接口了么？

**Comment by pifeifei** [comment]
> 视频号开放接口了么？

https://developers.weixin.qq.com/doc/channels/API/product/add.html

**Comment by overtrue** [comment]
6.x 默认支持几乎所有接口
