### ISSUE TITLE
关于新的商家发起转账到零钱接口的实现（非企业转账）

### ISSUE THREAD

**Issue by T-name** [w7corp/easywechat#2799]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：4.0
* 是否使用了框架？框架名称：tp

## 问题及现象

微信官方接口文档：https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch/initiate-batch-transfer.html
--
好像没有这个接口的实现，希望可以补上

**Comment by overtrue** [comment]
4.0系列不再修改，仅做安全更新哈

**Comment by T-name** [comment]
> 4.0系列不再修改，仅做安全更新哈



> 4.0系列不再修改，仅做安全更新哈

在其他版本中有实现吗。

**Comment by overtrue** [comment]
v3 接口只有最新的 6.x 才支持哈，细节请看文档

**Comment by lkiarest** [comment]
> v3 接口只有最新的 6.x 才支持哈，细节请看文档

请问有这部分的文档地址吗，没有找到~~
