### ISSUE TITLE
关注和被动回复消息都没有触发

### ISSUE THREAD

**Issue by Batman0506** [w7corp/easywechat#2806]
## 我用的环境

* PHP 版本：8.0
* overtrue/wechat 版本：6.x, ^6.7
* 是否使用了框架？框架名称：laravel9

## 问题及现象
```
public function serve()
{    
        $input = file_get_contents('php://input');    
        Log::debug('0000000', [$input]);
        $config = config('wechat');
        $app = new Application($config);
        $server = $app->getServer();
        $server->addMessageListener('text', function($message, \Closure $next) {
            Log::debug('1111', [$message]);
            return $message->content;
        });
        $server->addEventListener('subscribe', function($message, \Closure $next) {
            Log::debug('22222', [$message]);
            return '感谢您关注 EasyWeChat!';
        });
        $response = $server->serve();
        return $response;
}
```

- 关注的时候，日志里面存在tag0000 和1111的标识，并且返回response也是success。

- 但是公众号就是没有回复消息，关注的时候没有，发消息的时候也没有。也就是说这一部分的代码我没有跑通
![image](https://github.com/w7corp/easywechat/assets/43673757/298fb664-18d5-4cb8-a7ff-40d6e2aa0571)

**Comment by Batman0506** [comment]
https://easywechat.com/6.x/troubleshooting.html 我找到这个了。虽然还没成功，但我可以继续尝试

**Comment by ellisfan** [comment]
解决了吗？
我使用`$server->addMessageListener`处理不了任何消息和事件
只有使用`$server->with(function($message, \Closure $next)`才可以处理到消息

**Comment by lishuncoder** [comment]
> 解决了吗？ 我使用`$server->addMessageListener`处理不了任何消息和事件 只有使用`$server->with(function($message, \Closure $next)`才可以处理到消息

我这里更奇怪，我能收到微信的回调，也能针对关注事件做回复，但我就是不能回复消息
