### ISSUE TITLE
请问小程序是不支持API加密及签名校验吗

### ISSUE THREAD

**Issue by user599** [w7corp/easywechat#2810]
我在微信公众平台开启了API加密及签名校验，但返回值一直是明文的。

**Comment by overtrue** [comment]
SDK 有自动解密

**Comment by user599** [comment]
> SDK 有自动解密

感谢回复，请问该在哪里配置ras参数和证书信息呢
![QQ截图20240428105734](https://github.com/w7corp/easywechat/assets/41457884/4bbf4764-fbcc-4e8c-9dcb-7b6770f54dec)

**Comment by user599** [comment]
@overtrue 感谢回复。请问在哪里配置验签和解密用的ras参数和证书信息呢
![QQ截图20240428105734](https://github.com/w7corp/easywechat/assets/41457884/55840728-88b2-4a84-9e53-83d2cebbb6f9)

**Comment by overtrue** [comment]
www.easywechat.com 文档有写
