### ISSUE TITLE
恕我直言，6.X是最垃圾的版本。垃圾微擎，独裁主义。

### ISSUE THREAD

**Issue by lidongyooo** [w7corp/easywechat#2818]
如果不想维护，可以交还给社区主导。一个好好的开源项目，被垃圾公司改成这样。

**Comment by lidongyooo** [comment]
这背后有没有商业利益的驱动？提高对接的难度，让更多的用户选择直接用微擎？微擎收买这个项目的起因是什么？从6.X的改版来看，ES成了引流的渠道之一。

**Comment by lidongyooo** [comment]
![image](https://github.com/w7corp/easywechat/assets/49540545/7bc41455-bb7d-4d57-9cc0-2db7468691b7)
我请问，封装的意义是什么？不就是简化学习成本吗？提高代码的复用性吗？从软件的设计哲学层面来讲，微擎这般话无异于说这项目我们不维护了，你们自己学吧。

我请问，开源的意义是什么？不就是让一个轮子跑在万千台车子上吗？如果每个用户都自己去造轮子重头学习，还要你何用？微擎在毁掉一个开源项目。让商业远离开源，把微擎踢出社区。我同时呼吁所有贡献者停止对微擎的所有项目PR。

**Comment by suktec** [comment]
要不超哥帮你干活，你领工资吧

**Comment by overtrue** [comment]
👍

**Comment by overtrue** [comment]
你觉得它不好用，你可以用旧版本对不？ 5.x 没有禁用吧？😂
