### ISSUE TITLE
关于微信支付平台证书的疑问

### ISSUE THREAD

**Issue by gaoxu529** [w7corp/easywechat#2819]
## 我用的环境

* PHP 版本：7.4
* overtrue/wechat 版本：5.8
* 是否使用了框架？框架名称：

## 问题及现象

我的代码运行正常，但是遇到了一个问题，需要确认一下；在微信支付平台中，有一个平台证书，提示5年有效期到期了。我不确定更换这个证书后是否会对程序造成影响，因为我不确定这个库中是否使用了这个平台证书；我确定代码中使用了微信支付API证书，而且API证书我已经更换过了。
![image](https://github.com/w7corp/easywechat/assets/5687897/3fd284b0-5010-4296-a1e2-552a7d080a37)

**Comment by TheNorthMemory** [comment]
用到了「平台证书」

https://github.com/w7corp/easywechat/blob/a954805fb4be0d3dbcde9517e0364588ff546b37/src/Pay/Merchant.php#L78-L95

### 概念

+ **商户 API 证书**，是用来证实商户身份的。证书中包含商户号、证书序列号、证书有效期等信息，由证书授权机构（Certificate Authority ，简称 CA）签发，以防证书被伪造或篡改。详情见 [什么是商户API证书？如何获取商户API证书？](https://kf.qq.com/faq/161222NneAJf161222U7fARv.html) 。

+ **商户 API 私钥**。你申请商户 API 证书时，会生成商户私钥，并保存在本地证书文件夹的文件 apiclient_key.pem 中。为了证明 API 请求是由你发送的，你应使用商户 API 私钥对请求进行签名。

+ **微信支付平台证书**。微信支付平台证书是指：由微信支付负责申请，包含微信支付平台标识、公钥信息的证书。你需使用微信支付平台证书中的公钥验证 API 应答和回调通知的签名。

+ **证书序列号**。每个证书都有一个由 CA 颁发的唯一编号，即证书序列号。

**Comment by gaoxu529** [comment]
@TheNorthMemory 感谢您的回复，我使用的是5.x的easywechat，我让微信支付客服给我查了一下，他们说没有用到「平台证书」。
