### ISSUE TITLE
如何适配Hyperf 框架 swoole

### ISSUE THREAD

**Issue by cxyqx** [w7corp/easywechat#2822]
## 我用的环境

* PHP 版本：8.2
* overtrue/wechat 版本：6.15
* 是否使用了框架？框架名称：Hyperf 框架

## 问题及现象

如何适配Hyperf 框架，否则执行后报错：swoole_curl_setopt(): option[10100] is not supported

**Comment by overtrue** [comment]
请自行适配，仅做 PHP 官方版本支持，第三方扩展需要自己兼容哈

**Comment by yuzihui** [comment]
处理了吗？我也遇到这个问题了。 token 可以验证，就是被动回复不行
