### ISSUE TITLE
三方发起授权 当授权模式为：snsapi_base时 提示：api unauthorized

### ISSUE THREAD

**Issue by Dummercn** [w7corp/easywechat#2834]
## 我用的环境

* PHP 版本：8.2
* overtrue/wechat 版本：6
* 是否使用了框架？框架名称：thinkphp8

## 问题及现象

第三方授权管理微信公众号 发起用户授权 当授权模式为：snsapi_base时，当全新用户发起授权时 id 为空 提示：api unauthorized，下面是 返回信息。
只有有过授权 就可以正常返回信息 信息包含了全部的用户信息
$app->getOAuth()->scopes(['snsapi_base'])->redirect($authCallbackUrl);

// 下面的返回以下数据
$app->getOAuth()->userFromCode($code);

{
    "id": null,
    "name": null,
    "nickname": null,
    "avatar": null,
    "email": null,
    "raw": {
        "errcode": 48001,
        "errmsg": "api unauthorized, rid: 66c32540-7f06d757-5468df87"
    },
    "access_token": "83_0_fJRGunWPeBFtGU3NSVY5V79EmBgiEzfA9wlPqlRF3S-6WxYulyJJa9AFs6zQsz7ZqrY4ksNV-8xUtqW4J1VZnZ4UL1lRBlU",
    "refresh_token": "83_7OtRSzY8gOg3vvHX6lQtOqHqcNVmgZ6hFxz11O0kLwHFAGeh-DvP8NZ4T6tVcBBfuebNrXDCl2lIbRuiY76z3k7VM0yQPWXo",
    "expires_in": 7200,
    "token_response": {
        "access_token": "83_0_fJRGunWPeBFt3NSVY5V79EmBgiEzfA9wlPqlRF3S-6WxYulyJJa9AFs6zQsz7ZqrY4ksNV-8xUtqW4J1VZnZ4UL1lRBlU",
        "expires_in": 7200,
        "refresh_token": "83_7OtRSzY8gOg39LjP9vvHX6lQtOqHqcNVmgZ6hFxz11O0kLwHFAGeh-DvP8NZ4T6tVcBBfuebNrXDCl2lIbRuiY76z3k7VM0yQPWXo",
        "openid": "oqGoxwwIv4dbqguJGlGrqIbS0",
        "scope": "snsapi_base"
    }
}

**Comment by overtrue** [comment]
和 SDK 无关
