### ISSUE TITLE
Identifier "shipping" is not defined.

### ISSUE THREAD

**Issue by froginfog** [w7corp/easywechat#2837]
## 我用的环境

* PHP 版本：7.4.33
* overtrue/wechat 版本：5.30.0
* 是否使用了框架？框架名称：thinkphp5.0

## 问题及现象
小程序发货信息管理 报错Identifier "shipping" is not defined.
`$config = [
                'app_id' =>‘XXXX‘’’,
                'secret' => ‘xxxxxxxxx’,
                'response_type' => 'array'
            ];
 `
`$app = Factory::miniProgram($config);`
`dump($app->shipping);`

**Comment by overtrue** [comment]
```shell
composer info w7corp/easywechat
```

或者 

```shell
composer info overtrue/easywechat
```

贴一下全部结果

**Comment by froginfog** [comment]
> ```shell
> composer info w7corp/easywechat
> ```
> 
> 或者
> 
> ```shell
> composer info overtrue/easywechat
> ```
> 
> 贴一下全部结果

![1](https://github.com/user-attachments/assets/d0f0b8f2-b620-4d48-a70c-ba5597ec043e)

**Comment by froginfog** [comment]
> ```shell
> composer info w7corp/easywechat
> ```
> 
> 或者
> 
> ```shell
> composer info overtrue/easywechat
> ```
> 
> 贴一下全部结果

![4](https://github.com/user-attachments/assets/30154594-8705-488b-9cf5-63771e0f5a6d)

**Comment by overtrue** [comment]
改成 w7corp 的版本
