### ISSUE TITLE
【bug】src/Pay/Validator.php的 openssl_verify函数返回值

### ISSUE THREAD

**Issue by ledccn** [w7corp/easywechat#2843]
## 我用的环境

* PHP 版本：8.3
* overtrue/wechat 版本：6.15.2
* 是否使用了框架？框架名称：webman

## 问题及现象

`vendor/w7corp/easywechat/src/Pay/Validator.php`的 openssl_verify函数返回值：
如果签名正确返回 1，签名错误返回 0，错误时返回 -1 或 [false]
应改为：
```php
if (\openssl_verify(
    $message,
    base64_decode($signature),
    strval($publicKey),
    OPENSSL_ALGO_SHA256
) !== 1) {
    throw new InvalidSignatureException('Invalid Signature');
}
```

**Comment by overtrue** [comment]
直接 PR 一个？

**Comment by ledccn** [comment]
> 直接 PR 一个？
已PR，盼审批。(:
